### ISSUE TITLE
 App crashes on clicking "Create Center" from menu.

### ISSUE THREAD

**Issue by OgieBen** [openMF/android-client#1003]
**Summary:** 

App crashes on  clicking "Create Center" from menu. 

**Steps to reproduce:** 

->Open Dashboard
->Click the menu icon on toolbar
->Select "Create Center" from menu

**Expected behaviour:** 
Open fragment for creating New Center

**Observed behaviour:** 
App crashes

**Device and Android version:** 
Samsung S8 Android 8.0 Oreo
Nexus 5X Android 8.1 Oreo

**Screenshots:** 

![mifosdroid_create_center](https://user-images.githubusercontent.com/26555009/47814834-fd338600-dd4e-11e8-9050-039bc49b4e48.gif)

**Comment by bensoft2k5** [comment]
@tarun0  Can i work on this issue?

**Comment by tarun0** [comment]
@bensoft2k5 Yes, you can. Reply here and I'll assign it to you.

**Comment by bensoft2k5** [comment]
> @bensoft2k5 Yes, you can. Reply here and I'll assign it to you.

Yea @tarun0. I would like to work on this

**Comment by tarun0** [comment]
@bensoft2k5 Done

**Comment by bensoft2k5** [comment]
@AkshGautam great job

**Comment by Siddharth-Singhs** [comment]
@tarun0 Is this issue has been resolved ?

**Comment by Siddharth-Singhs** [comment]
Till Now app crashes while creating the Create Center menu

**Comment by vaibhav2203** [comment]
@bensoft2k5  can i work on this issue?

**Comment by AbhilashG97** [comment]
I am closing this issue as it has been resolved.
