### ISSUE TITLE
Glitched DropDown

### ISSUE THREAD

**Issue by ThisIsNSH** [openMF/android-client#1010]
**Summary:** 

Main Screen DropDown is not smooth. It seems two dropdowns rolling for microseconds.

**Steps to reproduce:** 

Press on options icon on top-right.

**Expected behaviour:** 

Smooth rolling down of menu.

**Observed behaviour:** 

Lagged rolling down.

**Device and Android version:** 

Redmi 3S Prime

**Gif:** 

![ezgif com-crop](https://user-images.githubusercontent.com/32385519/50721303-7d75bf00-10e3-11e9-99f1-e9f4b1cbbc4d.gif)

**Comment by ThisIsNSH** [comment]
@droidchef Please assign me this issue. :)

**Comment by vaibhav2203** [comment]
@droidchef  hey, can i work on this issue?

**Comment by Aditya-gupta99** [comment]
The issue has already been resolved
