### ISSUE TITLE
App Crashes on Create Center

### ISSUE THREAD

**Issue by ThisIsNSH** [openMF/android-client#1011]
**Summary:** 

App Crashes. Its an NPE where the id requested to be invisible doesn't exist.

**Steps to reproduce:** 

Press on Create Center item in dropdown menu.

**Expected behaviour:** 

Fragment should open.

**Observed behaviour:** 

App Crashes

**Device and Android version:** 

Redmi 3S Prime, Android 6.0.1

**Gif:** 

![ezgif com-resize](https://user-images.githubusercontent.com/32385519/50721362-405dfc80-10e4-11e9-93af-cf7deaf85601.gif)

**Comment by ThisIsNSH** [comment]
@droidchef Please assign me this issue :)

**Comment by ThisIsNSH** [comment]
This issue is mentioned in many other issues, but isn't resolved till now

**Comment by AkshGautam** [comment]
@ThisIsNSH this issue is already addressed and solved in #997 I'll try to get that merged soon.

**Comment by Aditya-gupta99** [comment]
The issue has already been resolved
