### ISSUE TITLE
App Crash on uploading the Signature.

### ISSUE THREAD

**Issue by Siddharth-Singhs** [openMF/android-client#1015]
**Summary:** 

If we upload the signature of client, the app crashes after selecting the image if we have not clicked the upload button at toolbar which ask the permission for storage.

**Steps to reproduce:** 

1.Install the app.
2.Search for the client and try to select the image from gallery.
3.The app will crash.
![whatsapp image 2019-01-08 at 7 26 15 pm](https://user-images.githubusercontent.com/31280485/50835152-fa22ca80-137b-11e9-90fe-51d09892b226.jpeg)

4.Now If we first click the upload button at top bar, it will ask user permission and now we can select the image from the gallery and there will be no error.

**Expected behaviour:** 

What did you expect the app to do?

There should be no app crash while selecting the image from gallery.

** App Crash**
![mifoscrash](https://user-images.githubusercontent.com/31280485/50835365-859c5b80-137c-11e9-9735-c50e6d6197ed.gif)

**App Not Crash**
![mifosnotcrash](https://user-images.githubusercontent.com/31280485/50835377-8fbe5a00-137c-11e9-8441-524d18d53645.gif)

**Comment by Siddharth-Singhs** [comment]
@tarun0 @therajanmaurya I want to work on this issue.

**Comment by Siddharth-Singhs** [comment]
please review the pull request.

**Comment by robustTechie** [comment]
Now the uploaded signature is showing in the signature list ?
