### ISSUE TITLE
Update compile and target SDK versions of the app

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/android-client#1033]
**Summary:** 
The compileSdkVersion and targetSdkVersion which are set to versions 27 and 27, respectively, must be changed to 28( Android Pie) as the latest Android APIs must be used to make use of the latest features.

@therajanmaurya @droidchef Can you please review this issue. I am interested in updating the SDK versions.

**Comment by moksh-mahajan** [comment]
@RajaVamsi11 Can I claim this issue?

**Comment by RajaVamsi11** [comment]
Yeah sure @moksh-mahajan. You can start working on this issue.
