### ISSUE TITLE
Menu Glitch In Run Reports

### ISSUE THREAD

**Issue by iadeelzafar** [openMF/android-client#1049]
**Summary:** 

Menu overrides appbar heading.

**Steps to reproduce:** 

* Go to Run Reports
* Click on the mneu

**Expected behaviour:** 

* It should not override it.
* The menu should popup from the right corner.
* Also, it's color should be white.

**Observed behaviour:** 

* It overrides the app bar Title.
* It has blue color that is also the color of the app bar which looks not so good.

**Device and Android version:** 

NEXUS 5X EMULATOR (API 28)

**Screenshots:** 

<img src = "https://user-images.githubusercontent.com/36811908/52584416-d7d90c80-2e53-11e9-906f-9a8823ccfbc6.gif" height="700" width="394">

**Comment by iadeelzafar** [comment]
@tarun0 What do you think? Shall I start working on this issue? Any suggestions are welcomed.

**Comment by Aditya-gupta99** [comment]
The issue has already been resolved
