### ISSUE TITLE
Stop Tracking Action Doesn't Works 

### ISSUE THREAD

**Issue by iadeelzafar** [openMF/android-client#1050]
**Summary:** 

Stop Tracking Action Doesn't Works 

**Steps to reproduce:** 

* Open Path Tracker
* Click on Track my path menu button
* Notification will appear
* Click on "Stop Tracking"
* It doesn't works

**Expected behaviour:** 

It should stop tracking when clicking on this action.

**Observed behaviour:** 

Right now, it doesn't responds to the click action.

**Device and Android version:** 

NEXUS 5X (API 28)

**Screenshots:** 

<img src = "https://user-images.githubusercontent.com/36811908/52796908-81a7db80-3096-11e9-882c-0df6e8d03a86.gif" height="700" width="394">

**Comment by PraneethVankayala** [comment]
@tarun0 I want to work on this issue

**Comment by sats98** [comment]
@iadeelzafar  i works on my device Android 7.0 API 24
![gggg](https://user-images.githubusercontent.com/33027508/52912530-8cea4980-32d8-11e9-8552-9c6a5327a812.gif)

the issue needs more details i think.

**Comment by iadeelzafar** [comment]
@sats98 Try it on API 28 and then let me know if it's working on API 28 for you or not.

**Comment by PatelVatsalB21** [comment]
For me also stop tracking isn't working. Niether does contentIntent nor ActionIntent. Even though my android version is 7 (Nougat)

![GIF-201210_222556 1](https://user-images.githubusercontent.com/70195106/101805127-66923f80-3b38-11eb-8313-23c0a968cfb8.gif)

**Comment by PatelVatsalB21** [comment]
Stop tracking is not working for me also. My device is Lenovo Tab 7 and Android 7

![GIF-201210_225058 1](https://user-images.githubusercontent.com/70195106/101807227-e3beb400-3b3a-11eb-975b-1c290b3f3a6d.gif)
