### ISSUE TITLE
Account number should not contain special characters

### ISSUE THREAD

**Issue by PraneethVankayala** [openMF/android-client#1054]
Current Account number format accepts special characters like(**'.'**,**' '**, **\n**) but it should not accept it.

**Steps to reproduce:** 
- Go to clients.
- Click on any client
- Go to one of the savings account
- On the menu bar you will be seeing **More Savings Account Info**
- Click on additional account and click on new then you will  enter the bank account details

**Expected behaviour:** 

The bank account number format must not accept any special charaacters

**Observed behaviour:** 

The current format accepts special characters

**Device and Android version:** 

Samsung Galaxy C9 Pro(c9lte)

Android Version 8(Oreo)

**Screenshots:** 

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/40353347/52913834-c080a000-32e7-11e9-895b-2a557445d990.gif)

**Comment by PraneethVankayala** [comment]
@tarun0, @therajanmaurya I would like to work on this issue

**Comment by theabhishekavi** [comment]
@PraneethVankayala are you still working on this issue?

**Comment by santoshconflux** [comment]
@PraneethVankayala , @theabhishekavi , Bank account number is captured through datatable. By changing the datatable configuration, you can avoid special characters in the filed.
