### ISSUE TITLE
No search toolbar in some activities

### ISSUE THREAD

**Issue by jasnasuresh** [openMF/android-client#1062]
**Summary:**
 
There is no search toolbar in activities like Groups, Clients and Centers.

**Steps to reproduce:** 

- Login to the app.
- Click on the hamburger icon on the top left corner.
- Click on Groups/Clients/Centers.

**Expected behaviour:** 

There should be a search bar for ease of use.

**Observed behaviour:** 

There is no search bar in any of theses activities.

**Device and Android version:** 

Device: Redmi note 5 Pro
Android version:8.1.0

**Comment by jasnasuresh** [comment]
I would like to work on this issue

**Comment by Aditya-gupta99** [comment]
The issue has already been resolved
