### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by Priyanka488** [openMF/android-client#1073]
**Summary:** 
While building the project , there were compilation errors related to annotation processors ,independent Os paths , although the settings were set as true.

**Steps to reproduce:** 

1. Import the project into Android Studio 3.3 with the annotations enabled
2. Build the project.
3. See the compilation errors

**Expected behaviour:** 

A successful build .

**Observed behaviour:** 

An unsuccessful build with compilation errors -
1. Annotation processor must be explicitly declared now.
2. More than one file was found with OS independent path.
3. Program type already present.

**Screenshots:** 

![screenshot 124](https://user-images.githubusercontent.com/33698440/53799205-e2bd2380-3f5f-11e9-8eb2-10b99af8f88f.png)
![44](https://user-images.githubusercontent.com/33698440/53799371-3c255280-3f60-11e9-97a5-5c2fbda57b73.png)

**Comment by iKlsR** [comment]
Was this properly tested?
