### ISSUE TITLE
Adding dashboard to menu option.

### ISSUE THREAD

**Issue by moksh-mahajan** [openMF/android-client#1078]
**Summary:** 
When a Create 'Entity' fragment is opened by clicking on the menu options, there is no option to go back to the Dashboard from that Create 'Entity' screen except for the Navigation drawer. My idea is to add a menu option for Dashboard too.

**Steps to reproduce:** 
Go to Dashboard.
Click on 3 dots on the top right corner.
Tap on any Create 'Entity' option (say Create Client).

**Expected behaviour:** 
Include an option for Dashboard in the menu.

**Observed behaviour:** 
There is no option for Dashboard in the menu options.

**Screenshots:** 
![photo6338866675557968169](https://user-images.githubusercontent.com/36201975/53819986-fb91fd00-3f90-11e9-8d2d-0fa4dd07a765.jpg)

**Comment by moksh-mahajan** [comment]
@droidchef @therajanmaurya Can I work on this?

**Comment by tavishjain** [comment]
@moksh-mahajan I guess Dashboard can be accessed from the navigation drawer and there is no need to add it to 2 places. It would have been another issue if the navigation drawer wasn't available, but there seems no point doing this
