### ISSUE TITLE
White Status bar

### ISSUE THREAD

**Issue by tavishjain** [openMF/android-client#1081]
**Summary:** 

After entering my PIN, as the next screen appears, the status bar for that activity becomes white in colour

**Steps to reproduce:** 

Open the app and enter your PIN, then have a look at the status bar

**Expected behaviour:** 

The status bar was supposed to be of the primaryDark colour

**Observed behaviour:** 

The status bar was white in colour

**Device and Android version:** 

Redmi Note 4
Android Nougat

**Screenshots:** 

![whatsapp image 2019-03-05 at 11 49 18 pm](https://user-images.githubusercontent.com/31106411/53827729-cb9f2580-3fa1-11e9-9c2f-0741fa74aae8.jpeg)

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by robustTechie** [comment]
I will work on this.
