### ISSUE TITLE
Making more informative toast message.

### ISSUE THREAD

**Issue by moksh-mahajan** [openMF/android-client#1087]
**Summary:** 
When back button is pressed in an Create 'Entity' screen, it displays a toast message "Please press back again to exit". This message can be changed to something like "Press again to go to Dashboard"

**Steps to reproduce:** 
Go to Dashboard.
Tap 3 dots.
Choose a Create 'Entity' option (say Create Client).
Press back button.

**Expected behaviour:** 
The toast message should be more informative.

**Observed behaviour:** 

Toast simply says - "Please press back again to exit"

**Comment by shivakanthsujit** [comment]
Are you working on a PR for this issue? If you aren't I would like to.

**Comment by moksh-mahajan** [comment]
@shivakanthsujit Yes, I'm submitting a PR soon.
