### ISSUE TITLE
Add AutoCompleteTextView for selecting offices in Collection Sheet

### ISSUE THREAD

**Issue by harshitbansal05** [openMF/android-client#1090]
**Summary:** 

The number of offices in the `Collection Sheet` fragment is very large, making it difficult to select from the spinner. An AutocompleteTextView would greatly simplify the task.

**Steps to reproduce:** 

Open `Collection Sheet` fragment from the navigation drawer. Select offices from the spinner.

**Comment by bryophyllum1** [comment]
I am working on this issue.

**Comment by bryophyllum1** [comment]
@harshitbansal05 can you please help me with this- when I run ```./gradlew check``` it gives the error that it can't find DaggerApplicationComponent and build fails.
![Screenshot from 2020-04-03 12-21-36](https://user-images.githubusercontent.com/51085133/78332716-2b517100-75a6-11ea-810e-1074bc8a677c.png)
