### ISSUE TITLE
No exception shown in Individual Collection Sheet and RunReports fragments for no internet

### ISSUE THREAD

**Issue by harshitbansal05** [openMF/android-client#1114]
**Summary:** 

No exception is shown in `Individual Collection Sheet` and `RunReports` fragments for no internet.

**Steps to reproduce:** 

Open the `Individual Collection Sheet` and `RunReports` fragments with no internet.

**Expected behaviour:** 

An exception must show up similar to `Collection Sheet` fragment.

**Observed behaviour:** 

No exception shows up.

**Device and Android version:** 

Moto E5 Plus, Android O

**Comment by AathmanT** [comment]
Sorry Wrong reference please discard this reference.
