### ISSUE TITLE
No Snackbar feedback is shown in Create Center and Create Group when there is no internet connection.

### ISSUE THREAD

**Issue by moksh-mahajan** [openMF/android-client#1116]
**Summary:** 

When there is no internet connection, and Create Client is opened, it shows a Snackbar message "Failed to Fetch Client template" but it is not shown in Create Group and Create Center when there is no internet.

**Steps to reproduce:** 
Turn off your internet connection.
Go to Create Client (Snackbar is shown)
Go to Create Group (Snackbar is not shown)
Go to Create Center (Snackbar is not shown)
How can we reproduce the issue?

**Expected behaviour:** 

Snackbar feedback should be shown saying "Failed to fetch center template" and "Failed to fetch Group Template"

**Observed behaviour:** 

No Snackbar is shown in Create Group and Create Center when there is no internet connection.

**Comment by moksh-mahajan** [comment]
@droidchef Can I work on this issue?

**Comment by RajaVamsi11** [comment]
@moksh-mahajan When I reproduce the above issue, presently there are toasts (probably wrong toast messages) in the Create Group and Create Center when there is no Internet connection. As you said Snackbar is necessary like in Create Client. Can I work on this Issue?

I am attaching the screenshots for your reference.

![Screenshot_2020-02-29-14-00-15-427_com mifos mifosxdroid](https://user-images.githubusercontent.com/30550059/75604188-40953480-5afc-11ea-93d3-bc63b42a054c.jpg)
![Screenshot_2020-02-29-14-00-20-576_com mifos mifosxdroid](https://user-images.githubusercontent.com/30550059/75604189-41c66180-5afc-11ea-9e96-bbadf59bf243.jpg)
![Screenshot_2020-02-29-14-00-24-702_com mifos mifosxdroid](https://user-images.githubusercontent.com/30550059/75604190-425ef800-5afc-11ea-90a1-c080eddc9fd3.jpg)
