### ISSUE TITLE
Incorrect design of Upload Document fragment

### ISSUE THREAD

**Issue by 0xamogh** [openMF/android-client#1119]
**Summary:** 
Unable to upload documents for a particular client. After choosing the file to upload/update, on pressing the upload button a toast saying "name can not be left empty" pops up. However, there is no text field visible to enter the name in the first place.
**Steps to reproduce:** 
Open App>Navigation Drawer>Client>Choose a client profile>Press 3 dots>Document> Press + button on the top right>Upload Document>Browse> Choose file> Press Upload
**Expected behaviour:** 
Upload request is made to API
**Observed behaviour:** 
Toast saying "name can not be left empty" pops up.
And file does not get uploaded.
**Device and Android version:** 
OnePlus 3T Android 8.0.0, Stock ROM
**Screenshots:** 
![videotogif_2019 03 10_19 00 50](https://user-images.githubusercontent.com/31567169/54085852-92cbcb80-4368-11e9-83b7-50e572a98830.gif)

I am working on this issue.

**Comment by AathmanT** [comment]
You can just change the layout_width of the big Linear Layout like my commit, instead of changing individual Text Views.
