### ISSUE TITLE
Text and image saying charges not found even if charges are present in Client Charges layout 

### ISSUE THREAD

**Issue by amogh-jrules** [openMF/android-client#1122]
**Summary:** 
Displays messages "No charges to display" while simultaneously displaying charges

**Steps to reproduce:** 
Go to a particular client's charges page where a few charges are already present and you will observe the issue.

**Expected behaviour:** 
Text and image which says charges not found should not be displayed

**Observed behaviour:** 
Text and image which says charges not found is displayed which might cause a common user to get confused, and in general is not correct information being provided to the user.

**Device and Android version:** 
OnePlus 3T, Android 8.0, Stock ROM

**Screenshots:** 
![Screenshot (11-Mar-2019 12_23_54 PM)](https://user-images.githubusercontent.com/31567169/54105505-3f558e00-43f9-11e9-9a89-69385b16b83b.jpg)

**Comment by laxyapahuja** [comment]
hey, i can't seem to reproduce this error. are you sure that it still exists?

**Comment by elirehema** [comment]
Hello @rachittt If you go to the client with no charges the message doesn't appear . 
Also you should consider artitecture pattern appropriately. Thanks

**Comment by rachittt** [comment]
@elirehema Updated the PR. Kindly check 😄
