### ISSUE TITLE
UI improvement: White space is created above the app bar.

### ISSUE THREAD

**Issue by moksh-mahajan** [openMF/android-client#1128]
**Summary:** 

Whenever a fragment is changed from Groups or Centers to any other fragment like Client, Search Client or any Create 'Entity', a white space is shown at the top of the app bar.

**Steps to reproduce:** 

Navigation Drawer > Choose "Groups" or "Centers" > Then Open Clients or Dashboard or Create 'Entity' from menu options.

**Expected behaviour:** 

White space should not be shown.

**Observed behaviour:** 

Changing above stated fragments will result in a white space creation above the app bar.

**Device and Android version:** 

Poco F1 (Android Pie, Stock)

**Screenshots:** 

![photo6068660387361957968](https://user-images.githubusercontent.com/36201975/54123291-4eeacc00-4425-11e9-8ef6-04e54905835b.jpg)

**Comment by DylanRobson** [comment]
Made PR for this issue.
