### ISSUE TITLE
Duplication of Charges on pressing the "No charges available" image

### ISSUE THREAD

**Issue by shivakanthsujit** [openMF/android-client#1129]
**Summary:** 
If there are two charges for a client, the "No Charges available" message is still found. Futhurmore if you press the message, the items in the list duplicate. And this duplication continues each time you press it.

**Steps to reproduce:** 
1. Open any client with two charges.
2. The "No Charges available" error is wrongly displayed.
3. If the user clicks the message, the charges are duplicated.

**Expected behaviour:** 
There shouldn't be any duplication to the list items.

**Observed behaviour:** 
The items of the list duplicate.

**Device and Android version:** 
Redmi Note 4 Lineage OS 15.1

**Screenshots:** 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/38406074/54128808-dee34280-4432-11e9-8946-b892e43da148.gif)

**Comment by amogh-jrules** [comment]
***you go gurl***

**Comment by elirehema** [comment]
i'm working on this

**Comment by AbhilashG97** [comment]
This issue has been resolved. Thank you for your contribution.
