### ISSUE TITLE
Removing @SuppressWarnings tags

### ISSUE THREAD

**Issue by 0xamogh** [openMF/android-client#1139]
**Summary:** 
While @SuppressWarnings can be used to ignore warnings that the developers know about and allow them to focus on more important, serious warnings, this is a bad coding practice as suppressing warnings will cause the code to break one day without the developers having any previous knowledge. 
Issue is solved by removing redundant renditions of the tag.

**Comment by refactor-droidyy** [comment]
@amogh-jrules can I work on this issue.

**Comment by amogh-jrules** [comment]
Yes.
