### ISSUE TITLE
No Feedback when ListView with no elements is clicked

### ISSUE THREAD

**Issue by shivakanthsujit** [openMF/android-client#1140]
**Summary:** 

No feedback when Listview, in ClientDetailsFragment, with no elements clicked.

**Steps to reproduce:** 

In Client Activity, press a Loan or Savings or Recurring Account tab with no elements.

**Expected behaviour:** 

Some Feedback that there are no accounts available.

**Observed behaviour:** 

No feedback.

**Device and Android version:** 

Redmi Note 4 Lineage OS 15.1

**Screenshots:** 

![Screenshot_20190315-160010_MifosXDroid](https://user-images.githubusercontent.com/38406074/54425584-acd82600-473b-11e9-803c-4801582ca678.png)

**Comment by mananvirmani611** [comment]
@shivakanthsujit Is this issue resolved ??
