### ISSUE TITLE
Back Button not working when sync surveys dialog opens in settings tab

### ISSUE THREAD

**Issue by RashulChutani** [openMF/android-client#1142]
**Summary:** 
Back Button not working when sync surveys dialog is opened on pressing sync surveys in settings tab available in navigation drawer .The desired functionality must be that Background area should not be functional (on pressing) but back button must work and dialog should get dismissed on pressing back.

**Steps to reproduce:** 
1. Open Navigation Drawer.
2. Click on settings.
3. Toggle on the sync surveys button.
4. Sync Surveys dialog will appear.
5. Click on back and nothing will happen

**Expected behaviour:** 
The desired functionality must be that Background area should not be functional (on pressing) but back button must work and dialog should get dismissed on pressing back.

**Observed behaviour:** 
Back Button not working when sync surveys dialog is opened on pressing sync surveys in settings tab available in navigation drawer

**Device and Android version:** 

Same behaviour on all devices but screenshot attached of Moto E (Android 5.1)

**Screenshots:** 
![Screenshot_2019-03-17-14-33-06](https://user-images.githubusercontent.com/41239718/54487999-91e3ee00-48c2-11e9-9803-59688350c073.png)

**Comment by RashulChutani** [comment]
I am working on this issue.

**Comment by thefossguy** [comment]
This issue is still open. If its not resolved can I start working on it?
