### ISSUE TITLE
Groups Activity keeps on loading when Create client is selected in offline

### ISSUE THREAD

**Issue by AathmanT** [openMF/android-client#1144]
**Summary:** 

The screen keeps loading if create client is chosen from the over flow menu while in the Group Activity and back button is pressed.

**Steps to reproduce:** 

Turn off Mobile Data.
Navigation drawer->Groups->Create Client from the overflow menu->Press back button

**Expected behaviour:** 

Groups Activity must show up Failed to fetch groups as before.

**Observed behaviour:** 

Groups Activity keeps on loading

**Device and Android version:** 

Samsung Galaxy J7 Prime (Nougat 7.0, stock)

**Screenshots:** 

![issue](https://user-images.githubusercontent.com/35717580/54675065-b985c100-4b23-11e9-82a0-4d80583518ae.gif)

**Comment by RashulChutani** [comment]
I am working on this

**Comment by AathmanT** [comment]
I have already started working on this.

**Comment by AathmanT** [comment]
A different progress bar will be displayed for online mode. And your solution won't fix that.

**Comment by AathmanT** [comment]
Fix #1154
