### ISSUE TITLE
Invidual collection list dropdown includes text box description.

### ISSUE THREAD

**Issue by apoorva-mk** [openMF/android-client#1150]
**Summary:** 

In 'Individual Collection List' activity the drop down list shouldn't include the text box description.

**Steps to reproduce:** 

- Open Individual Collection List from Navigator menu
- When 'Select Office' drop down list is clicked the 'Select office' option shouldn't appear as an office. Similarly with 'Select loan officer'. 

**Expected behaviour:** 

Should only list the valid offices and not the text box description

**Observed behaviour:** 

Text box description also included in drop down list.

**Device and Android version:** 

Redmi Y2
Android 8.1.0

**Screenshots:** 

<img src=https://user-images.githubusercontent.com/42450012/54874836-14b3fe00-4e19-11e9-8182-e0d4475b66a6.png  alt="drawing" width="300"/>

**Comment by apoorva-mk** [comment]
I'm working on it.

**Comment by ShankarNara** [comment]
I understand your point , but I don't think it really is an issue
This is a standard practice to include the textbox description in the drop down list in other apps.

**Comment by apoorva-mk** [comment]
Oh alright then, I'll close this issue.
