### ISSUE TITLE
App crashes on clicking path tracker

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/android-client#1165]
**Summary:** 

When trying to run path tracker service, the app just crashes throwing null pointer exception.

**Steps to reproduce:** 

From Dashboard, just click Path Tracker

**Expected behavior:** 

The app should show the tracked paths and allow the user to track his path.

**Observed behavior:** 

App crash.

**Device and Android version:** 

Device: Samsung and 6.1.0

**Comment by laxyapahuja** [comment]
@luckyman20 This issue seems to have been solved. I think it can be closed now.
