### ISSUE TITLE
No options to upload existing photo in Edit client page. 

### ISSUE THREAD

**Issue by santoshconflux** [openMF/android-client#1182]
1) Go to left navigation page and tap on Clients.
 2) In clients list page, click on '+' icon.
 3) In next create client page, tap on image and then select take photo.
 4) Submit client with other mandatory fields.
5) Go to the client page, and tap on the image.
Expected: It should show both 'Take photo' and Upload Photo options.
Actual: Its only showing take photo option. Uploading existing photo is not  available.

**Comment by elirehema** [comment]
I think [this issue in mifos-mobile](https://github.com/openMF/mifos-mobile/issues/1214) repository will conflict with this one. 

If  mifos-mobile will allow client to edit his profile picture the same as here. Both client and organization will be able to edit the same photo. 

Who is real responsible to upload the client photo ? A client or organization. @santoshconflux @edcable

**Comment by luckyman20** [comment]
@elirehema Not all clients are self service users and even if both are able to edit the photo then also it isn't a very big problem. Although we can (in future) restrict editing photo of self service user by admin.

**Comment by elirehema** [comment]
@luckyman20 my point was to make a clear cut on who is supporsed to update a client image. If we allow both organization and client to update the same client image it may lead to conflict i.e. organization update image and client update the same image(profile pic)

**Comment by laxyapahuja** [comment]
I've solved this issue. Making a PR.

**Comment by jsahil730** [comment]
@luckyman20 I think it probably has issues when uploaded image sizes are very high, like 3-4 MB, could you take a look into this?
