### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#1183]
**Summary:** 

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)

**Steps to reproduce:** 

How can we reproduce the issue?

**Expected behaviour:** 

What did you expect the app to do?

**Observed behaviour:** 

What did you see instead?  Describe your issue in detail here.

**Device and Android version:** 

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:** 

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by theabhishekavi** [comment]
@edcable what is this issue about?

**Comment by santoshconflux** [comment]
@theabhishekavi , this is the template which we have to follow for every ticket raised.

**Comment by RavirajMhalsekar** [comment]
Hi. I'm Raviraj 
I'm a first year engineering student and  I have just  started with  android development.
I want to fix this issue. but I don't know how.
Can u help by pointing me in a right  direction?

**Comment by asaikarthikeya** [comment]
> Hi. I'm Raviraj
> I'm a first year engineering student and I have just started with android development.
> I want to fix this issue. but I don't know how.
> Can u help by pointing me in a right direction?

Hello Ravi,
This is a test issue. there is nothing to work on this. Search for another issue that needs to be worked upon.
