### ISSUE TITLE
Issues related to Keyboard.

### ISSUE THREAD

**Issue by myselfanuj** [openMF/android-client#1185]
**Summary:** 

Whenever the user tapping anywhere on the screen there is no shutdown of the keyboard on the login page. This affects the user experience.

**Steps to reproduce:** 

Just tap anywhere on the screen after opening the keyboard in login.

**Expected behaviour:** 

The keyboard must be closed after tapping anywhere on the screen

**Observed behavior:** 

Whenever the user tapping elsewhere on the screen there is no shutdown of the keyboard on
login/signup page.

**Device and Android version:** 

Vivo V5
Android 7.0

**Screenrecording:** 

<img src = "https://raw.githubusercontent.com/myselfanuj/Issues-Recording/master/openMF/Recording2.gif">

**Comment by corneliuze** [comment]
why is the issue still opened?
