### ISSUE TITLE
hard coded string xml

### ISSUE THREAD

**Issue by sukhbeer** [openMF/android-client#1188]
**Summary:** 

some XML file has hard-coded text.  convert a hard-coded String to a string ressource.

**Comment by harshshinde07** [comment]
@sukhbeer Can I take up this issue?

**Comment by sukhbeer** [comment]
this issue is for GCI students. @santoshconflux add GCI tag.

**Comment by santoshconflux** [comment]
@sukhbeer , Done

**Comment by PiyushSharma99** [comment]
I am working on this issue - https://codein.withgoogle.com/dashboard/task-instances/5892336647667712/ Thanks!
