### ISSUE TITLE
App sometimes crashes when navigation drawer is opened after navigating to groups

### ISSUE THREAD

**Issue by Grandolf49** [openMF/android-client#1189]
**Summary:** 

App sometimes crashes when navigation drawer icon is pressed after the user has navigated to Groups

**Steps to reproduce:** 

1. Open Navigation Drawer
2. Go to groups
3. Click Navigation drawer icon again
Try this a few times, the app crashes

**Expected behaviour:** 

App should not crash while navigating

**Observed behaviour:** 

What did you see instead?  Describe your issue in detail here.

**Device and Android version:** 

Android 10
OnePlus 6
Stock ROM

**Screenshots:** 
![android-client-app-crash-groups](https://user-images.githubusercontent.com/30969403/68988686-41fa6400-0861-11ea-96e3-c05f7dd73c01.gif)

**Comment by laxyapahuja** [comment]
@luckyman20 already merged #1227 which solves this problem. This can be closed now.
