### ISSUE TITLE
Add Margin to ClientActivity [GCI] 

### ISSUE THREAD

**Issue by harshshinde07** [openMF/android-client#1191]
**Summary:** 

This task involves adding start and end margin to `ClientActivity` 

**Steps to reproduce:** 
- Open navigation drawer
- Click on Clients
- Click on any individual client from the list
- You can see that the details screen does not have the required start and  end margin

**Screenshots:** 

<img src="https://user-images.githubusercontent.com/25999879/68996816-4fe1d080-08c5-11ea-98bc-ba4e76bbaf09.png" width=200 />

**Comment by PiyushSharma99** [comment]
I have claimed this task here https://codein.withgoogle.com/dashboard/task-instances/5748205438894080/ and am working on it. Thanks
