### ISSUE TITLE
Add Margin to GroupActivity [GCI] 

### ISSUE THREAD

**Issue by harshshinde07** [openMF/android-client#1192]
**Summary:** 

This task involves adding start and end margin to `GroupActivity` 

**Steps to reproduce:** 
- Open navigation drawer
- Click on Groups
- Click on any individual group from the list
- You can see that the details screen does not have the required start and  end margin

**Screenshots:** 

<img src="https://user-images.githubusercontent.com/25999879/68996863-c67ece00-08c5-11ea-86e4-7a032a8f6061.png" width=200 />

**Comment by santoshconflux** [comment]
@harshshinde07 , Are you working on this?

**Comment by PiyushSharma99** [comment]
I have claimed this task here - https://codein.withgoogle.com/dashboard/task-instances/6607590839025664/ and am working on it!
