### ISSUE TITLE
Add Margin to CenterActivity [GCI] 

### ISSUE THREAD

**Issue by harshshinde07** [openMF/android-client#1193]
**Summary:** 

This task involves adding start and end margin to `CenterActivity` 

**Steps to reproduce:** 
- Open navigation drawer
- Click on Centers
- Click on any individual center from the list
- You can see that the details screen does not have the required start and  end margin

**Screenshots:** 

<img src="https://user-images.githubusercontent.com/25999879/68996865-ce3e7280-08c5-11ea-9ea9-24496bf89716.png" width=200 />

**Comment by santoshconflux** [comment]
@harshshinde07, Are you working on this?

**Comment by harshshinde07** [comment]
@santoshconflux this isssue and all others with `[GCI]` in the title are for GCI.
