### ISSUE TITLE
"Failed to fetch LoanProducts" toast when on Loan Application

### ISSUE THREAD

**Issue by laxyapahuja** [openMF/android-client#1214]
**Summary:** 

When adding a loan account in the clients details page, a toast shows up titled "Failed to fetch LoanProducts". After I fill the external ID and clicking Submit, the app crashes.

**Steps to reproduce:** 

Clients -> any client -> options -> Add loan account -> Toasts shows up -> Enter External ID -> Submit -> App crashes

**Expected behaviour:** 

Certain fields should get filled and the app should not crash.

**Observed behaviour:** 

The fields are not filled and the app crashes after submitting.

**Device and Android version:** 

Android 9, Mi A3

**Screenshots:** 

![image](https://user-images.githubusercontent.com/31318248/70385927-4a554300-19b8-11ea-8fa9-582550a745e3.png)

**Comment by Saransh0905** [comment]
I would like to solve this issue. Can someone guide me?
