### ISSUE TITLE
Action Bar shifts a bit down

### ISSUE THREAD

**Issue by laxyapahuja** [openMF/android-client#1226]
**Summary:** 

After browsing through several fragments, the action bar shifted a bit downwards and stayed there.

**Steps to reproduce:** 

Clients -> Groups -> Centers -> More fragments till the action bar drops

**Expected behaviour:** 

Action bar shouldn't shift.

**Observed behaviour:** 

The action bar shifts.

**Device and Android version:** 

Android 9, Mi A3

**Screenshots:** 
![ezgif-5-50dec29592c7](https://user-images.githubusercontent.com/31318248/70547755-724ecd00-1b97-11ea-98b1-173443730438.gif)
--------------------------------------------------------------
![image](https://user-images.githubusercontent.com/31318248/70547615-33207c00-1b97-11ea-8131-5023e4b0a9f4.png)

**Comment by jsahil730** [comment]
@luckyman20 Can it be a GCI task?

**Comment by luckyman20** [comment]
@jsahil730 Yes, it can be.

**Comment by moksh-mahajan** [comment]
@laxyapahuja @luckyman20 The issue and the fix has already been created and submitted before.

**Comment by luckyman20** [comment]
@jsahil730 please make sure that we don't have task for it.
