### ISSUE TITLE
Saving client name even if number is entered in first, middle, last name.

### ISSUE THREAD

**Issue by iamsh4shank** [openMF/android-client#1237]
**Summary:** 

Saving client name even if number is entered in first, middle, last name.

**Steps to reproduce:** 

Go to client saving option and type number in first, middle, last number instead of alphabets.

**Expected behaviour:** 

If number is entered then it must show the toast notification like "First name/last name/ middle name should only contain alphabets"

**Observed behaviour:** 

It is saving the client information even if number is entered.

**Device and Android version:** 
Realme 5 
Android Version 9.0

**Screenshots:** 

![issue2](https://user-images.githubusercontent.com/52889867/71417170-ffab1a80-2689-11ea-9e9c-d9045544b25f.gif)

**Comment by robustTechie** [comment]
I will work on this issue.
