### ISSUE TITLE
Wrong toast message appears in collection sheet 

### ISSUE THREAD

**Issue by iamsh4shank** [openMF/android-client#1246]
**Summary:** 

After selecting office name in collection sheet wrong toast message appears as "Please select center name"  instead of "Please select staff name"

**Steps to reproduce:** 

Open nav drawer>Collection sheet>select office

**Expected behaviour:** 

Show toast message as "Please select a staff"

**Observed behaviour:** 

After selecting office name, toast message appears as "Please select center name" instead of "Please select staff name"

**Device and Android version:** 

Android version 9.0
Realme 5

**Screenshots:** 
![issue6](https://user-images.githubusercontent.com/52889867/72164612-05c02b80-33ec-11ea-99f4-9d8ef115fc17.gif)

**Comment by robustTechie** [comment]
I will work on this issue.

**Comment by Priyansh-Kedia** [comment]
Is this issue still open?
May I work on this?

**Comment by rachittt** [comment]
> Is this issue still open?
> May I work on this?

You should not work on the issues which already have an open PR as it awaits project maintainer's review. Please read contributor's guidelines 🙂
