### ISSUE TITLE
Clear button not working

### ISSUE THREAD

**Issue by iamsh4shank** [openMF/android-client#1248]
**Summary:** 

Clear button not working in Individual Collection Sheet.

**Steps to reproduce:** 

Open nav drawer>Select Office and Loan Officer>Press Clear button.

**Expected behaviour:** 

Clear button clear the selected choice.

**Observed behaviour:** 

Clear button not working in Individual Collection Sheet.

**Device and Android version:** 

Android Version 9.0
Realme 5

**Screenshots:** 

![issue7](https://user-images.githubusercontent.com/52889867/72163391-c42e8100-33e9-11ea-9b1d-977dfad6ab65.gif)

**Comment by robustTechie** [comment]
I will work on this.

**Comment by Priyansh-Kedia** [comment]
Is this issue still open?
May I work on this?

**Comment by robustTechie** [comment]
I sent the PR for this.
