### ISSUE TITLE
Detect cause of a Failed Login Attempt

### ISSUE THREAD

**Issue by ishan1604** [openMF/android-client#125]
Many customers have complaint about a problem while logging in. Due to some failure the App Throws a toast that says "There was some error processing the request." 

It would be helpful if could implement a simple Logging module that user can review and contact the developers with in case there is some sort of an error.

Currently this use case only applies to the Login system, it can be extended further as and when need arises.

**Comment by chhavip** [comment]
I just compiled the code on my system and am facing a SSL certificate problem on the login page, what are the demo values or how can i sign in?
