### ISSUE TITLE
Save button not working properly

### ISSUE THREAD

**Issue by robustTechie** [openMF/android-client#1250]
**Summary:** 

After pressing Save button in charges menu save dialog button does not disappears. That affects user experience.

**Steps to reproduce:** 

Open nav drawer>Clients>Press any client name>Click on options and then on Charges>Click on plus button>Enter amount then press save button

**Expected behaviour:** 

After pressing save button current dialog box disappears.

**Observed behaviour:** 

After pressing save button then dialog button doesn't disappears that affects user experience. 

**Device and Android version:** 
Android Version 9.0
Realme 5

**Screenshots:** 

![issue9](https://user-images.githubusercontent.com/52889867/71751506-c9e40e00-2ea1-11ea-9de9-7bc616154e4e.gif)

**Comment by robustTechie** [comment]
I will work on this.

**Comment by laxyapahuja** [comment]
It seems to a permission issue. What account are you using?

**Comment by robustTechie** [comment]
Mifos

**Comment by laxyapahuja** [comment]
The issue here is that your account doesn't have the appropriate permission to create charges. I don't think it requires an issue to be made because of it. The most you can do is make the snackbar text more comprehensible to the general user.

**Comment by robustTechie** [comment]
Yes the user don't have permissions for saving but after pressing the save button the dialog box must be closed by showing a toast notification whether it saved or not.
