### ISSUE TITLE
Save dialog box not closed in Charges of Loan account

### ISSUE THREAD

**Issue by iamsh4shank** [openMF/android-client#1254]
**Summary:** 

After pressing save button in charges of loan accounts the dialog box was not closing. It affects the user experience  

**Steps to reproduce:** 
open nav drawer>clients>Click on any client>go to Loan account and open any one > Go to options and click on charges> then click on add button > and then save

**Expected behaviour:** 

If there will be any error while saving charges then save dialog box will close and show the error message.

**Observed behaviour:** 

When there is error while saving it just shows the error on previous fragment.

**Device and Android version:** 

Android Version 9.0
Realme 5

**Screenshots:** 

![issue11](https://user-images.githubusercontent.com/52889867/72163724-5c2c6a80-33ea-11ea-818c-bc7718f42ed8.gif)

**Comment by robustTechie** [comment]
I will work on this issue
