### ISSUE TITLE
Space between Toolbar and Status bar

### ISSUE THREAD

**Issue by 991rajat** [openMF/android-client#1256]
**Summary:** 
After navigating through fragments and coming back to dashboard unnecessary space between Toolbar and Status bar.

**Steps to reproduce:** 

Dashboard > Group > Dashboard(White Space Visible) > Client (White Space Visible) etc.

**Expected behaviour:** 

No unnecessary space should appear.

**Observed behaviour:** 

Unnecessary space between Toolbar and Status bar.

**Device and Android version:** 
Motorola Moto E2
Android Nougat 7.1.2
Custom Rom Lineage OS

Android Virtual Device (Nexus S) API 24
Android Nougat 7.0

**Screenshots:** 
![GIF-200110_145723](https://user-images.githubusercontent.com/38184186/72142086-f9bb7600-33b9-11ea-90f9-25045b844c36.gif)

**Comment by 991rajat** [comment]
I would like to implement it.

**Comment by robustTechie** [comment]
Hey @991rajat  this issue is present there #1081
