### ISSUE TITLE
Lag in toolbar title change in ClientActivity

### ISSUE THREAD

**Issue by ashu10832** [openMF/android-client#1258]
**Summary:** 

Lag in updating the toolbar title in client activity. 

**Steps to reproduce:** 

1. Go the client list from the sidebar.
2. Choose any client.
3. Check the toolbar title.

**Expected behaviour:** 

Toolbar should show the name of the client chosen immediately because we already have that information. 

**Observed behaviour:** 

On choosing a client, the toolbar shows 'ClientActivity' for a few seconds while the data is getting retrieved from the server and then the title changes to the last name which shouldn't happen.

**Device and Android version:** 

POCO F1 
Android 9
MIUI

**Screenshots:** 

![clientactivity](https://user-images.githubusercontent.com/19621727/72146995-9e8e8100-33c3-11ea-9339-6b97980cb45d.gif)

**Comment by ashu10832** [comment]
I would like to work on this issue.

**Comment by elirehema** [comment]
@ashu10832 are you still working on this issue ?
