### ISSUE TITLE
Up Button not present in Submit Survey and Survey Question page

### ISSUE THREAD

**Issue by iamsh4shank** [openMF/android-client#1259]
**Summary:** 

Up button not present in survey submit page and survey question page. It affects the user experience.

**Steps to reproduce:** 
open nav drawer>clients>click on any client> click on other options then survey>fill the survey> submit 

**Expected behaviour:** 

Submit Survey page and Survey Question page must contain an Up button. 

**Observed behaviour:** 

Up button not present in survey question page and in submit page. It affects the user experience.

**Device and Android version:** 

Android Version 9.0
Realme 5

**Screenshots:** 

![issue14](https://user-images.githubusercontent.com/52889867/72166954-373af600-33f0-11ea-87e0-0304967783c4.gif)

**Comment by robustTechie** [comment]
I will work on this.
