### ISSUE TITLE
Upload Document not showing toast message

### ISSUE THREAD

**Issue by iamsh4shank** [openMF/android-client#1264]
**Summary:** 

If uploading document failed then it do not shows a toast message as "Failed to upload document".

**Steps to reproduce:** 

open nav drawer> Clients>open any client then go on more options>docment>click on plus button>save new document.

**Expected behaviour:** 

If uploading document failed then it show a toast messages as "Upload document failed"

**Observed behaviour:** 

If uploading document failed then it do not shows a toast message as "Failed to upload document".

**Device and Android version:** 

Android Version 9.0
Realme5

**Screenshots:** 
![Issue17](https://user-images.githubusercontent.com/52889867/72258404-06e39980-3634-11ea-89b1-d425e578307a.gif)

**Comment by robustTechie** [comment]
I will work on this.
