### ISSUE TITLE
Switch not closed in sync surveys in offline mode

### ISSUE THREAD

**Issue by iamsh4shank** [openMF/android-client#1266]
**Summary:** 

When no internet is available then if you try to sync survey by making switch on then it will show a toast message but it does not automatically does not off the switch.  

**Steps to reproduce:** 

open nav drawer> switch on Offline mode> then settings>Sync Surveys

**Expected behaviour:** 

After showing toast message as "Network is not available" sync survey switch must get automatically off.

**Observed behaviour:** 

When no internet is available then if you try to sync survey by making switch on then it will show a toast message but it does not automatically does not off the switch.  

**Device and Android version:** 

Android Version 9.0
Realme5

**Screenshots:** 

![Issue18](https://user-images.githubusercontent.com/52889867/72418831-9ce90280-37a1-11ea-8bf3-e54a078b4be2.gif)

**Comment by robustTechie** [comment]
I will work on this.
