### ISSUE TITLE
No toast message in wrong Username/Password

### ISSUE THREAD

**Issue by iamsh4shank** [openMF/android-client#1268]
**Summary:** 

If user enters wrong username and password then no warning toast message comes.

**Steps to reproduce:** 

Enter either wrong username or wrong password or both.

**Expected behaviour:** 

If wrong username or password is entered then it must show a toast message as "Wrong username or password"

**Observed behaviour:** 

It first start showing the dialog box for logging then dialog box closes without any toast notification.

**Device and Android version:** 

Android Version 9.0
Realme5

**Screenshots:** 
![issue19](https://user-images.githubusercontent.com/52889867/72427589-0f61de80-37b2-11ea-8fd0-5e09dd3288e8.gif)

**Comment by robustTechie** [comment]
I will work on this.

**Comment by 207ashu** [comment]
I tried logging into the app with the credentials mifos and password, but didn't found any progress. 
Do we need to configure anything from the connection settings tab

**Comment by robustTechie** [comment]
Yes, press connection setting then change the URL to demo.mifos.io

**Comment by 207ashu** [comment]
I tried logging in with the url you mentioned and the port was 8080 and default was the value for tenant Identifier, the dialog was visible but login wasn't successful.

**Comment by 207ashu** [comment]
Well I guess port and tenant identifier wasn't needed

**Comment by laxyapahuja** [comment]
@207ashu were you able to login?

**Comment by 207ashu** [comment]
Yes

**Comment by Siddharth-Singhs** [comment]
@robustTechie  Can I work on this issue.

**Comment by robustTechie** [comment]
I am working on this issue.

**Comment by sachin-0102** [comment]
@robustTechie , are you still working on this issue or the PR was generated?. If none is the case, can I work on this issue?

**Comment by Aditya-gupta99** [comment]
The issue has already been resolved
