### ISSUE TITLE
Group name not aligned

### ISSUE THREAD

**Issue by iamsh4shank** [openMF/android-client#1272]
**Summary:** 

Group name not perfectly aligned. 

**Steps to reproduce:** 

open nav drawer>groups>click on any group name

**Expected behaviour:** 

Group name should be aligned

**Observed behaviour:** 

Group name not perfectly aligned. 

**Device and Android version:** 

Android version 9.0
Realme5

**Screenshots:** 
![Issue21](https://user-images.githubusercontent.com/52889867/72666344-3715a880-3a37-11ea-8d6e-58a60c7bad2a.png)

**Comment by robustTechie** [comment]
I will work on this.
