### ISSUE TITLE
Client not added in groups

### ISSUE THREAD

**Issue by robustTechie** [openMF/android-client#1274]
**Summary:** 

In group client option even after creating new client it is also not showing the newly created client.

**Steps to reproduce:** 

open nav drawer>group and then select any group>more options> group client>create new  and activate it

**Expected behaviour:** 

After creating a new client it must show in group client page.

**Observed behaviour:** 

In group client option even after creating new client it is also not showing the newly created client.

**Device and Android version:** 

Android Version 9.0
Realme5

**Screenshots:** 
![issue22](https://user-images.githubusercontent.com/52889867/72677918-3debfc00-3ac7-11ea-8196-6fae23022fea.gif)

**Comment by robustTechie** [comment]
I will work on this.

**Comment by laxyapahuja** [comment]
already fixed in #1233
