### ISSUE TITLE
Security feature enhancement

### ISSUE THREAD

**Issue by robustTechie** [openMF/android-client#1277]
**Summary:** 

After adding required credentials like username, password, connection setting there is choice to apply a local passcode for more security. No forget passcode feature is available for the same.

**Expected behaviour:** 

It will show a forget passcode option so that user can change his passcode without doing login again from his username and password after answering some questions.

**Device and Android version:** 

Android Version 9.0
Realme5

**Screenshots:** 

![Issue23](https://user-images.githubusercontent.com/52889867/72737542-c81a8a00-3bc5-11ea-988a-1ff0aa454636.gif)

**Comment by robustTechie** [comment]
I will work on this.

**Comment by laxyapahuja** [comment]
It's not supposed to change passcode. The passcode is there to bypass logging in again and again. If a user forgets the passcode, he/she can login with his/her account details.

**Comment by robustTechie** [comment]
So the user need to do login again but what if there would some security questions, after answering user can change that bypass password. Also there is no option for changing it again without logging out.

**Comment by laxyapahuja** [comment]
When the user logs in after clicking forgot password, the passcode automatically gets reset and the user can change it the next time he/she logs into the app.

**Comment by robustTechie** [comment]
I think it will be good if the whole logout process doesn't occur just that passcode will reopen to change the passcode after asking some security questions.
