### ISSUE TITLE
Gender options in create client improper

### ISSUE THREAD

**Issue by Grandolf49** [openMF/android-client#1284]
**Summary:** 

The gender options available while creating a client are improper

**Steps to reproduce:** 

1. Dashboard -> Options -> Create Client
2. Select gender to expand options
3. 9 options available 

**Expected behaviour:** 

Only 3 options are expected under gender
1. Male
2. Female
3. Not disclosing

**Observed behaviour:** 

Unnecessary 9 options appear in different languages

**Device and Android version:** 

Android 10
OnePlus 6
Stock ROM

**Screenshots:** 

![gender options in create client improper](https://user-images.githubusercontent.com/30969403/73092340-7134ed80-3f02-11ea-9f4e-560ca71b45cd.gif)

**Comment by robustTechie** [comment]
Can I work on this ?

**Comment by Grandolf49** [comment]
@robustTechie Sure. Go ahead

**Comment by Priyansh-Kedia** [comment]
May I work on this?

**Comment by rachittt** [comment]
@robustTechie are you working on it?

**Comment by robustTechie** [comment]
Yes

**Comment by robustTechie** [comment]
What all genders I should give in the spinner?

**Comment by Grandolf49** [comment]
@robustTechie we can have these options: 1. Male 2. Female 3. Other

**Comment by robustTechie** [comment]
Ok I wil do it ASAP.

**Comment by Aditya-gupta99** [comment]
Issue has been resolved.
