### ISSUE TITLE
Run Reports toolbar font inconsistent

### ISSUE THREAD

**Issue by Grandolf49** [openMF/android-client#1285]
**Summary:** 

The toolbar text font in Run Report activity is larger than normal toolbar font, making it inconsistent. Options, don't go with the theme.

**Steps to reproduce:** 

1. Nav bar -> RunReports
2. Toolbar font inconsistent

**Expected behavior:** 

The toolbar font size should follow normal size

**Observed behavior:** 

Font size is inconsistent
 
**Device and Android version:** 

Android 10
OnePlus 6
Stock ROM

**Screenshots:** 

![font size on toolbar of Run Reports inconsistent](https://user-images.githubusercontent.com/30969403/73093092-d806d680-3f03-11ea-9da9-9ab3cfe17361.gif)

**Comment by robustTechie** [comment]
Can I work on this

**Comment by Grandolf49** [comment]
@robustTechie Sure. Go ahead

**Comment by Aditya-gupta99** [comment]
Issue has been already resolved.
