### ISSUE TITLE
Improve UX by providing a button to directly enter the next edittext section

### ISSUE THREAD

**Issue by iamsh4shank** [openMF/android-client#1293]
**Summary:** 

While creating new client a fragment comes, in its editText, no keyboard next click is present.

**Steps to reproduce:** 

open create new client page > press submit button

**Expected behaviour:** 

Keyboard should have feature to enter the next editText section form previous editText.

**Observed behaviour:** 

While creating new client a fragment comes, in its editText, no keyboard next click is present.

**Device and Android version:** 

Android Version 9.0
Realme 5

**Screenshots:** 

![issue26](https://user-images.githubusercontent.com/52889867/73851760-0ebde480-4854-11ea-9e7c-366683abbf78.png)

**Comment by robustTechie** [comment]
I will work on this.

**Comment by Priyansh-Kedia** [comment]
Is this issue still open?
May I work on this?
