### ISSUE TITLE
Change passcode not present

### ISSUE THREAD

**Issue by iamsh4shank** [openMF/android-client#1301]
**Summary:** 

There is no option to change the passcode, user can only change it after doing log out.

**Expected behaviour:** 

There should be an option in setting to change the passcode without doing log out.

**Comment by robustTechie** [comment]
I will work on this issue.

**Comment by Priyansh-Kedia** [comment]
May I work on this issue?

**Comment by robustTechie** [comment]
I am working on this issue.
