### ISSUE TITLE
splashscreen

### ISSUE THREAD

**Issue by som23ya** [openMF/android-client#1302]
Adding a splashscreen on start of app.

**Comment by som23ya** [comment]
I would be working on this one.

**Comment by elirehema** [comment]
@som23ya i think there is one [here]( https://github.com/openMF/android-client/blob/master/mifosng-android/src/main/java/com/mifos/mifosxdroid/SplashScreenActivity.java). Is this what you want to say ?

![GIF-200214_112100](https://user-images.githubusercontent.com/29277048/74513958-c02bdc80-4f1c-11ea-8f61-f7ac383f9807.gif)

**Comment by robustTechie** [comment]
Hey @som23ya it is there in the application.

**Comment by som23ya** [comment]
@robustTechie @elirehema i guess then there is some issues in it, becuase i have tested on 3 phones, it is not working. nexus 5, moto g6 and honor lite. Maybe we should see into this?

**Comment by robustTechie** [comment]
Try reinstalling the application or just run it on emulator, as in my case it is working.

**Comment by rohanprasadofficial** [comment]
@som23ya  I tested it on many devices and it worked fine.

**Comment by Aditya-gupta99** [comment]
The issue has already been resolved
