### ISSUE TITLE
Bold text in Offline Sync

### ISSUE THREAD

**Issue by iamsh4shank** [openMF/android-client#1307]
**Summary:** 

In offline Sync option text are in a bold format which affects the UX. 

**Steps to reproduce:** 

open nav drawer> click on Offline sync> open any of the option.

**Expected behaviour:** 

The text should be in normal text format.

**Observed behaviour:** 

In offline Sync option text are in a bold format which affects the UX. 

**Device and Android version:** 

Android Version 9.0
Realme 5

**Screenshots:** 

![issue1](https://user-images.githubusercontent.com/52889867/74758596-90266580-529d-11ea-8c0d-cde385fb6e3b.png)

**Comment by robustTechie** [comment]
I will work on this issue.
