### ISSUE TITLE
Wrong text alignment

### ISSUE THREAD

**Issue by iamsh4shank** [openMF/android-client#1309]
**Summary:** 

In the client page, the wrong alignment (right side alignment) of text is present, which affects the user experience.

**Steps to reproduce:** 

open any client's info

**Expected behaviour:** 

Text alignment should be perfect so that the UI looks good

**Observed behaviour:** 

In the client page, the wrong alignment of text is present, which affects the user experience.

**Device and Android version:** 

Android Version 9.0
Realme 5

**Screenshots:** 

![issue 32](https://user-images.githubusercontent.com/52889867/74844502-895a2a00-5353-11ea-9a88-869b789b095d.png)

**Comment by robustTechie** [comment]
I will work on this
