### ISSUE TITLE
Need Journal Entry option in Mobile App

### ISSUE THREAD

**Issue by MayaDuruva** [openMF/android-client#1311]
If any one have developed a Journal entry option mobile app same as a mifos X web?

currently we need a option in mobile phone

**Comment by robustTechie** [comment]
I think the backend for this feature is not available, so it will hard to implement.

**Comment by MayaDuruva** [comment]
Okay

**Comment by maektwain** [comment]
The backend is there, but the rationale behind developing such feature inside the mobile app is not actually useful.
