### ISSUE TITLE
Run reports toolbar expanded text color doesnt follow the theme

### ISSUE THREAD

**Issue by dreadpool2** [openMF/android-client#1318]
**Summary:** 

As we can see in the picture below, the UI doesnt follow theme.

**Screenshots:** 

![Screenshot_20200221-194612_MifosXDroid](https://user-images.githubusercontent.com/28607714/75041881-79715000-54e3-11ea-896b-f3457e37d7d3.jpg)

**Working on it**

**Comment by Grandolf49** [comment]
This issue is already addressed #1285 
Please close this issue
