### ISSUE TITLE
Fix UI in Center Details Page

### ISSUE THREAD

**Issue by dreadpool2** [openMF/android-client#1320]
**Summary:** 

The padding is not correct in the page as shown in below screenshot.

**Screenshots:** 

![WhatsApp Image 2020-02-21 at 20 20 01](https://user-images.githubusercontent.com/28607714/75044442-a889c080-54e7-11ea-8845-397ffeafccb4.jpeg)

**Comment by Grandolf49** [comment]
Hey @dreadpool2 This issue was already solved during GCI:
Issue Number: #1193 
PR Number: #1207

Please close the issue
