### ISSUE TITLE
No smooth transition after opening connection settings while logging in

### ISSUE THREAD

**Issue by Grandolf49** [openMF/android-client#1330]
**Summary:** 

There is no smooth transition of UI when user clicks **Connection Settings** on the Login Page

**Steps to reproduce:** 

1. Login Activity -> Click Connection Settings
2. No transition when settings are shown or hidden

**Expected behaviour:** 

There should be a smooth transition when layout changes are happening

**Device and Android version:** 

Android 10
OnePlus 6
Stock ROM

**Screenshots:** 

![android-client - no smooth transition after opening connection settings](https://user-images.githubusercontent.com/30969403/75079977-9f711180-5530-11ea-8e65-d91ddb225f3d.gif)

**Comment by Priyansh-Kedia** [comment]
May I work on this?
