### ISSUE TITLE
Wrong TextDrawable text shown in search results

### ISSUE THREAD

**Issue by dreadpool2** [openMF/android-client#1332]
**Summary:** 

The TextDrawable only shows 'C' in results. This should not happen

**Screenshots:** 
![WhatsApp Image 2020-02-22 at 12 13 45](https://user-images.githubusercontent.com/28607714/75087982-ed0b6f80-556c-11ea-9bf4-1bffbd50a317.jpeg)

**Comment by robustTechie** [comment]
Check once I think it shows the C because they all are clients and if it is a group then it will show G, etc

**Comment by dreadpool2** [comment]
Yeah! I got a bit confused on receiving all C's. I guess we can change the UI later for ease of viewing .
Closing this
