### ISSUE TITLE
UI Enhanced for Login Activity 

### ISSUE THREAD

**Issue by rohanprasadofficial** [openMF/android-client#1339]
**Summary:** 

The UI for the login page is not looking so good , i tried out to revamp it with the same dependency.

**Before :** 
![before login](https://user-images.githubusercontent.com/30728574/75377314-82a15900-58f7-11ea-98c7-4ef1a19ddb67.png)

**After** 
![after login page](https://user-images.githubusercontent.com/30728574/75377320-892fd080-58f7-11ea-8c14-3bb9d56567a5.png)

**Device and Android version:** 

I tested on physical device ( Samsung J700) and all the emulators and its looks great.

**Design:** 
![loginpage revamped](https://user-images.githubusercontent.com/30728574/75377337-9220a200-58f7-11ea-9097-2ca4a1448ee2.png)

**Comment by rohanprasadofficial** [comment]
Can i work on this ?

**Comment by Priyansh-Kedia** [comment]
Is this issue still open?
May I work on this?

**Comment by rohanprasadofficial** [comment]
@Priyansh-Kedia  i will work on it , once it gets assigned by maintainers

**Comment by rohanprasadofficial** [comment]
I am working on it @Priyansh-Kedia

**Comment by Priyansh-Kedia** [comment]
@rohanprasadofficial Thanks for the update.

**Comment by robustTechie** [comment]
What if the user clicks on connection settings?

**Comment by rohanprasadofficial** [comment]
@robustTechie  its  working ,  it loads up as defined

**Comment by robustTechie** [comment]
Great

**Comment by rachittt** [comment]
hey @rohanprasadofficial, you should consider adding the screenshot of the implemented design on the **Pull Request's markdown** file and not on the Issues' markdown.

**Comment by rohanprasadofficial** [comment]
@rachittt  okay but same the as the issue one , actually i implemented it and made a issues and PR .

**Comment by rachittt** [comment]
> @rachittt okay but same the as the issue one , actually i implemented it and made a issues and PR .

yeah, but while reviewing a PR, the maintainer expects the screenshot on PR's md file.

Also, ideally the person should upload the picture of **proposed design on Issue** and **implemented screenshot on PR**

**Comment by rohanprasadofficial** [comment]
@rachittt  Oh really sorry , was my first issues and PRs on this platform , i will rectify this mistakes in future .

**Comment by rohanprasadofficial** [comment]
@rachittt  for this issues i implemented the feature then generated a issues , so it was a mistake next will do a proposed design in issues and implemented gif in PR , 
Thanks for the clarification , will follow from now .
