### ISSUE TITLE
Recurring Accounts Option goes off-screen

### ISSUE THREAD

**Issue by chhavip** [openMF/android-client#134]
In ClientDetailsFragment, the recurring accounts option goes off-screen of savings account is opened.

**Comment by ishan1604** [comment]
@chhavip Will you be able to add a screenshot here in the issue ? please :)

**Comment by chhavip** [comment]
![screenshot_20151021-152241](https://cloud.githubusercontent.com/assets/7212638/10633411/15ab343a-7808-11e5-90e8-d9a25704dc0e.png)

**Comment by chhavip** [comment]
that is the maximum scroll down possible after savings have been opened

**Comment by ishan1604** [comment]
Quick Fix : Change `Account Number` text to `Account No#` this should probably created some space for us.

Or if you could come up with any other solution, feel free to suggest/implement it.

**Comment by chhavip** [comment]
done, please review

**Comment by ishan1604** [comment]
It would be awesome if you could Squash your commits. If you need help in squashing let me know.

**Comment by chhavip** [comment]
I would need some help with that and what newline are you referring to in
the commit?

Chhavi P. Gupta

**Comment by chhavip** [comment]
Got the newline error, removing it

Chhavi P. Gupta
