### ISSUE TITLE
Backpressed should not exit app in client activity

### ISSUE THREAD

**Issue by Priyansh-Kedia** [openMF/android-client#1341]
**Summary:** 
It would be better if onbackpressed in create client form takes to the client page.

**Expected behaviour:** 

Onbackpressed on the create client form will open the clients page.

**Screenshots:** 
![WhatsApp Image 2020-02-27 at 12 08 58 PM](https://user-images.githubusercontent.com/52661249/75418677-13108580-595a-11ea-809e-f338e9e34eb4.jpeg)

**Comment by Priyansh-Kedia** [comment]
I would like to work on this issue

**Comment by robustTechie** [comment]
I think adding back button will of no use as we can access nav drawer also from here.

**Comment by Aditya-gupta99** [comment]
Issue has been already resolved.
