### ISSUE TITLE
Feature: Saving Account Summary to PDF

### ISSUE THREAD

**Issue by Siddharth-Singhs** [openMF/android-client#1343]
**Summary:** 

There should an option for a client to download the saving account summary as PDF. 

**Screenshots:** 

![issue1](https://user-images.githubusercontent.com/31280485/75431262-9c33b680-5972-11ea-9216-976af5cbb69c.jpg)

**Comment by Siddharth-Singhs** [comment]
I want to work on this issue.

**Comment by robustTechie** [comment]
Are you working on this issue?

**Comment by Siddharth-Singhs** [comment]
yes
