### ISSUE TITLE
issue fix: Login activity -  bottom toaster message invisible due to keyboard for wrong credentials 

### ISSUE THREAD

**Issue by rohanprasadofficial** [openMF/android-client#1345]
**Summary:** 
Whenever a user login with correct credentials its directs the user to dashboard or passcode activity and user gets the login was successful but whenever user enter any wrong credentials or incorrect password or username length , user is shown with error toaster message at bottom but due to keyboard unhidden , user cannot see error message  when he/she clicks on login button without hiding the keyboard.   Please refer screenshot.

**Steps to reproduce:** 

1. Go to login activity 
2. Enter the wrong credentials
3. Click on login button , it doesn't hides keyboard
4. You can't see the error message.

**Expected behaviour:** 

**Observed behaviour:** 

Keyboard gets hidden when click on login button and user can see error message.

**Device and Android version:** 

Realme X 

**Screenshots:** 
![loginerrortoast](https://user-images.githubusercontent.com/30728574/75521070-ed07e580-5a2c-11ea-9cda-598c02819c89.gif)

**Comment by rohanprasadofficial** [comment]
I am working on this.

**Comment by neeraj0403** [comment]
@rohanprasadofficial  are u working on this issue?

**Comment by rohanprasadofficial** [comment]
@neeraj0403  yes

**Comment by rohanprasadofficial** [comment]
@Grandolf49 @droidchef  can you please review it ?
