### ISSUE TITLE
Keyboard pops up bug

### ISSUE THREAD

**Issue by Siddharth-Singhs** [openMF/android-client#1357]
**Summary:** 

While withdrawing the money from Group Saving Account, the keyboard pops up.

**Steps to reproduce:** 

1. Login into app
2. Go the groups
2. Open any group which have a saving account and make withdrawals request.

**Expected behaviour:** 

A keyboard should not pop up.

**Observed behaviour:** 

Keyboard pops up after making withdrawals request.

**Screenshots:** 
![ezgif-5-57702b8055b3](https://user-images.githubusercontent.com/31280485/75609131-080d4f00-5b2c-11ea-8d9c-2ea2a0336b47.gif)

**Comment by Siddharth-Singhs** [comment]
I will work on this issue.

**Comment by robustTechie** [comment]
#1290 is the fix for the issue. This issue is already fixed.

**Comment by Siddharth-Singhs** [comment]
okay @robustTechie I am closing this issue.
