### ISSUE TITLE
Indefinite length time of snack bars in Login Activity

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/android-client#1359]
**Summary:** 

The Snack bars which are occurring in Login Activity have an indefinite length which shows the Snackbar indefinitely.

**Steps to reproduce:** 

Go to Login Activity and try to login with empty or incorrect credentials. You will see the Snack bars at the bottom.

**Expected behaviour:** 

The Snack bars should have either a short period of time or a long period of time but not Indefinite.

**Observed behaviour:** 

The Snack bars are having Indefinite length time.

**Device and Android version:** 

Device: RedMi Note 8 Pro
Android Version: 9

**Screenshots:** 

![Screenshot_2020-02-29-18-03-31-337_com mifos mifosxdroid 1](https://user-images.githubusercontent.com/30550059/75607511-f02ece80-5b1d-11ea-9e26-f999561c2a42.jpg)

**Comment by rachittt** [comment]
Do we really need this? As long as the user has the option to press "OK", it should be indefinite.
We can think of changing it to a material snackbar though.

**Comment by RajaVamsi11** [comment]
In my point of view, Toasts and Snack bars are used for short time information or error messages. So I think we need this. You idea of converting them to material snackbar is also good. I can do it if it is necessary.

**Comment by RajaVamsi11** [comment]
As we can see in the other parts of the application, Toast and Snackbar are of either Short or Long period of time but not indefinite.

**Comment by rachittt** [comment]
messages which have the option of 'confirming' should be indefinite. 
So there are two options, either remove the "OK" button and make its duration long or keep the "OK" button and make the duration indefinite because if it the snackbar disappears itself after some time, we don't need the user to confirm by pressing "OK" before it.

**Comment by rachittt** [comment]
Also about the error message, don't you think the appropriate message in this case would be "Please Enter the Credentials" ?

**Comment by RajaVamsi11** [comment]
Okay @rachittt , I will look into this. I will update the snackbar messages according to the error. According to you what will be the best option to proceed with? Either to remove Ok option or keep length indefinite.

**Comment by rachittt** [comment]
> Okay @rachittt , I will look into this. I will update the snackbar messages according to the error. According to you what will be the best option to proceed with? Either to remove Ok option or keep length indefinite.

Indefinite length looks appropriate in this case until we redesign the whole application using material design. 
Regarding the snackbar message, create a new issue regarding it and fix it in a different PR

**Comment by RajaVamsi11** [comment]
Okay Thanks. I am on it.

**Comment by robustTechie** [comment]
@rachittt is correct as messages which have a confirming option are of indefinite length
