### ISSUE TITLE
UI enhancement of CenterDetails Fragment

### ISSUE THREAD

**Issue by rohanprasadofficial** [openMF/android-client#1368]
**Summary:**

The UI of CenterDetails Fragment doesn't look good with not such good color combinations.

**Steps to reproduce:**

1. Go to side drawer
2. Open center
3. Click on a center from center list.

**Expected behaviour:**

The UI should look greatly formatted with good tables format.

**Observed behaviour:**

UI is imperfect, it doesn't have proper colors and display text combination.

**Device and Android**

Android Version 9.0

Realme X

![Screenshot_20200301-231921](https://user-images.githubusercontent.com/30728574/75630719-239f5500-5c13-11ea-9e34-eae208045b49.png)

**Comment by rohanprasadofficial** [comment]
i am working on it.

**Comment by Aditya-gupta99** [comment]
This issue has been already resolved.
