### ISSUE TITLE
UI enhancement of Individual Collection Sheet Spinner

### ISSUE THREAD

**Issue by rohanprasadofficial** [openMF/android-client#1369]
Summary:

The UI of Individual Collection Sheet Spinner doesn't look good with transparent spinner 

Steps to reproduce:

1. Go to side drawer
2. Open Individual collection sheet
3. Click on spinner

Expected behaviour:

The UI should look greatly formatted and spinner should not be transparent.

Observed behaviour:

UI is imperfect, it doesn't have proper good looking spinner.

Device and Android

Android Version 9.0

Realme X

![Screenshot_20200301-232625](https://user-images.githubusercontent.com/30728574/75631001-3d419c00-5c15-11ea-831d-2d05f43eef69.png)

**Comment by rohanprasadofficial** [comment]
i am working on it.

**Comment by Aditya-gupta99** [comment]
Issue has been already resolved.
