### ISSUE TITLE
Alphabetical order is missing in Clients List and Centers List

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/android-client#1374]
**Summary:** 

Alphabetical order is missing in the Clients and Centers List. It has been implemented in the Groups List but not in the Clients List and Centers List. Alphabetical order of lists helps the user to find the desired name quickly and easily. Implementing this feature will be a great UX.

**Steps to reproduce:** 

Go to Clients List and Centers List, you can see the list of items are not sorted according to the Alphabetical order as in Groups List.

**Expected behaviour:** 

The Lists must be sorted in Alphabetical order.

**Observed behaviour:** 

The Lists are not sorted in Alphabetical order

**Device and Android version:** 

Device: RedMi Note 8 Pro
Android Version: 9

**Screenshots:** 

**Clients List: (No Alphabetical Order)**

![Screenshot_2020-03-02-22-47-45-448_com mifos mifosxdroid](https://user-images.githubusercontent.com/30550059/75702657-e0f57f80-5cdb-11ea-914f-badf18641f83.jpg)

**Centers List: (No Alphabetical Order)**

![Screenshot_2020-03-02-22-46-15-172_com mifos mifosxdroid](https://user-images.githubusercontent.com/30550059/75702701-f10d5f00-5cdb-11ea-98db-aab3806f7726.jpg)

**Groups List: (Alphabetical Order)**

![Screenshot_2020-03-02-22-47-24-574_com mifos mifosxdroid](https://user-images.githubusercontent.com/30550059/75702619-ce7b4600-5cdb-11ea-9be4-4e4516cc5717.jpg)

**Comment by RajaVamsi11** [comment]
I would like to work on this issue.

**Comment by robustTechie** [comment]
@RajaVamsi11  may be some sorting options is provided what if the user field officer want to see the client list on the basis when they are created or maybe some other filter

**Comment by RajaVamsi11** [comment]
@robustTechie As the Groups List already contains this feature, I don't think there will be any problem implementing in other lists too. If the list created by the officer is too long (for suppose more than 1000), he needs to check every name to find the desired name. Instead, it will be easy for the field officer to find the name if the list is sorted.

**Comment by robustTechie** [comment]
For just searching the app has Dashboard where the officer can search for clients, groups, etc

**Comment by RajaVamsi11** [comment]
Yes, the dashboard has the search feature but implementing extra features will not cause any harm.
Let us take other's point of view on this issue :)
@rachittt @tarun0 @moksh-mahajan Whar are your views?

**Comment by rachittt** [comment]
instead of making it only in alphabetical order, why don't we give a filter option which let's the user decide if they want the list in 'alphabetical order' or 'Newest to Oldest' or 'Oldest to Newest,' etc.

**Comment by robustTechie** [comment]
Yes I totally agree with @rachittt adding a filter option will be perfect.

**Comment by robustTechie** [comment]
Are you working on this issue?

**Comment by RajaVamsi11** [comment]
Yes, I am working on it.

**Comment by NikunjGarg2000** [comment]
Hey @RajaVamsi11, have you done resolving it? If you are not working on this, I would like to. Thanks.
