### ISSUE TITLE
Progress Bar loading in Group Clients endlessly

### ISSUE THREAD

**Issue by iamsh4shank** [openMF/android-client#1378]
**Summary:** 

In group clients, the progress bar is loading endlessly even after fetching the clients.

**Steps to reproduce:** 

open any group> from overflow menu open group client  

**Expected behaviour:** 

After fetching the clients the progress bar should stop

**Observed behaviour:** 

In group clients, the progress bar is loading continuously it is not stopping even after fetching the clients.

**Device and Android version:** 

Android Version 9.0
Realme 5

**Screenshots:** 

![issue37](https://user-images.githubusercontent.com/52889867/75715634-bd3e3380-5cf3-11ea-85d5-6142da16631b.gif)

**Comment by robustTechie** [comment]
I will work on this.
