### ISSUE TITLE
Search result not update

### ISSUE THREAD

**Issue by iamsh4shank** [openMF/android-client#1379]
**Summary:** 

If we change the filter and no such search result is found then it will show the previous search result.

**Steps to reproduce:** 

Search any name in the dashboard and then change the filter such that the filter doesn't have search results.

**Expected behaviour:** 

If no result is found then it should clean the search result.

**Observed behaviour:** 

If we change the filter and no such search result is found then it will show the previous search result.

**Device and Android version:** 

Android Version: 9.0
Realme 5

**Screenshots:** 

![issue39-1](https://user-images.githubusercontent.com/52889867/75754018-f1e0d800-5d51-11ea-9a33-dfbcf1e84c48.gif)

**Comment by robustTechie** [comment]
I will work on this issue.

**Comment by Aditya-gupta99** [comment]
This issue has been resolved.
