### ISSUE TITLE
Improve Savings Account UI of Group

### ISSUE THREAD

**Issue by dreadpool2** [openMF/android-client#1402]
**Summary:** 

The UI of Savings Account Page must be improved. Alignment and padding must be improved.

**Screenshots:** 
![WhatsApp Image 2020-03-09 at 22 53 42](https://user-images.githubusercontent.com/28607714/76240223-e19c9180-6258-11ea-88b6-8f2f093a85f6.jpeg)

**Comment by RajaVamsi11** [comment]
@dreadpool2 Can I work on this issue?
