### ISSUE TITLE
Path Tracker issue

### ISSUE THREAD

**Issue by MayaDuruva** [openMF/android-client#1416]
Path Tracker crash the app

**Comment by MayaDuruva** [comment]
![Screenshot (531)](https://user-images.githubusercontent.com/56622978/77052247-899d2200-69f2-11ea-9280-53da17b74cab.png)

**Comment by Grandolf49** [comment]
@MayaDuruva  This issue is already created. [Issue No.](https://github.com/openMF/android-client/issues/1165)
Please close this issue.
