### ISSUE TITLE
Unnecessary variable declared

### ISSUE THREAD

**Issue by dreadpool2** [openMF/android-client#1420]
**Summary:** 

Unnecessary variable declared in LoanChargeDialogFragment.java file. We don't use the value of variable in further cases.

**Comment by EstherBrown1** [comment]
Currently working on addressing this ticker: Remove unnecessary variable declartion #1421

**Comment by EstherBrown1** [comment]
The current variable declation is:
if (chargeId != -1) {

                } else {

                    Toast.makeText(getActivity(), getString(R.string.error_select_charge)
                            , Toast.LENGTH_SHORT).show();

                }
