### ISSUE TITLE
Improper usage of switch case in Login Activity

### ISSUE THREAD

**Issue by Grandolf49** [openMF/android-client#1424]
**Summary:** 

There is a switch case in Login Activity with only case and default.
``` 
switch (item.getItemId()) {  
            case R.id.mItem_connection_settings:  
                ll_connectionSettings.setVisibility(  
                        ll_connectionSettings.getVisibility() == VISIBLE ? GONE : VISIBLE);  
                return true;  

            default:  
                return super.onOptionsItemSelected(item);  
        }
```
**Expected behaviour:** 

If there is only one case in switch case, it should be replaced with if else statement.

**Comment by dreadpool2** [comment]
Actually a switch case should be used here, even if there is one condition, as this is present under onOptionItemSelected function. Here it analyzes that there might be more options to be added in the future.
