### ISSUE TITLE
No toast message while switching between offline and online mode.

### ISSUE THREAD

**Issue by iamsh4shank** [openMF/android-client#1441]
**Summary:** 

No toast message while switching between offline and online mode by the provided spinner in navigation drawer.

**Steps to reproduce:** 

open navigation drawer>switch between offline and online mode.

**Expected behaviour:** 

There should be a toast message while switching between offline and online mode.

**Observed behaviour:** 

There is no such notification provided while switching.

**Device and Android version:** 

Android Version 9.0
Realme 5

**Screenshots:** 

![issue44-2](https://user-images.githubusercontent.com/52889867/77253361-9d10ed00-6c7f-11ea-90e7-35e2bb8a15d1.png)

**Comment by robustTechie** [comment]
I would like to work on this.
