### ISSUE TITLE
Keyboard does not hide when we open the app and click the hamburger menu. 

### ISSUE THREAD

**Issue by Sachit1137** [openMF/android-client#1443]
**Summary:** 

Keyboard does not hide when we open the app and click the hamburger menu. Ideally it should hide automatically on clicking the menu button.

**Steps to reproduce:** 
1. Open the app
2. Click the menu button
3. Keyboard is still there

**Expected behaviour:** 

The Keyboard should hide automatically.

**Observed behaviour:** 

As the keyboard does not hide itself the user has to manually do it, which is not ideal.

**Device and Android version:** 

Device - Samsung Galaxy S10e 
Android Version - 10 (Samsung One UI v2.0)

**Screenshots:** 
![WhatsApp Image 2020-03-22 at 7 01 36 PM](https://user-images.githubusercontent.com/55988870/77263905-b01bc100-6c6f-11ea-875f-dff90188d738.jpeg)

**Comment by robustTechie** [comment]
#1234 is the same issue.

**Comment by Sachit1137** [comment]
Already Resolved.
