### ISSUE TITLE
Keyboard not hiding in Login page

### ISSUE THREAD

**Issue by shambu2k** [openMF/android-client#1453]
**Summary:** 

Keyboard not hiding if incorrect credentials are entered and Snackbar comes behind keyboard

**Steps to reproduce:** 

Just open the app and enter wrong credentials.. the keyboard stays there and the error snackbar is not visible as it is behind the keyboard. This happens in the main page also, everywhere the hideKeyboard method is called.

**Expected behaviour:** 

Irrespective of whether credentials are right or wrong, keyboard should hide.

**Observed behaviour:** 

Even though there is a method implemented to hide keyboard.. it does not seem to work.. The Keyboard should hide as soon as login button is pressed.

**Device and Android version:** 

My device is Nokia 3.1 plus running android api 28 (android pie)

**Comment by shambu2k** [comment]
I want to work on this..

**Comment by robustTechie** [comment]
#1352  is the fix for this. Please close this.

**Comment by shambu2k** [comment]
Has it not been merged?? 

> #1352 is the fix for this. Please close this.

```
Oh okay..
