### ISSUE TITLE
Client Image delete api doesn't work

### ISSUE THREAD

**Issue by bnasim** [openMF/android-client#146]
Even if it says deleted but it's not permanently deleted.

**Comment by therajanmaurya** [comment]
It is working for me, may be you are seeing the default image. Can you post a screenshot?

**Comment by mayank-kgp** [comment]
@bnasim  Please give an update on this issue.

**Comment by therajanmaurya** [comment]
@mayank-kgp It's working now, I think this issue should be closed. 
@mayank-kgp try to delete user profile image and let me know because it's working in devices.

**Comment by mayank-kgp** [comment]
@therajanmaurya  It is deleted. But when we go back to client list, then image is appearing in clientList. 
Because the list is not reloading. But when I reload the list, then image is not appearing.

**Comment by therajanmaurya** [comment]
Thanks @mayank-kgp, So this issue is already resolved. I will open new issue for "when we go back to client list, then image is appearing in clientList Because the list is not reloading"

Thanks

**Comment by mayank-kgp** [comment]
Thanks @therajanmaurya  
Pls open it.
