### ISSUE TITLE
Recurring Accounts withdrawl or payment crashes application

### ISSUE THREAD

**Issue by chhavip** [openMF/android-client#147]
Choosing Make Repayment or Make Deposit in an active recurring account leads to a crash in the application.
Log of the error:

![recurring account crash](https://cloud.githubusercontent.com/assets/7212638/10958784/dd1713aa-8397-11e5-996d-6bfabb484d34.png)

**Comment by therajanmaurya** [comment]
It is fixed in #279, So I am closing this issue.
