### ISSUE TITLE
Remove unnecessary button when generating new individual collection sheet

### ISSUE THREAD

**Issue by casyazmon** [openMF/android-client#1473]
**Summary:** 

Inactive and unnecessary button when generating new individual collection sheet. the clear button is unnecessary since we only have few fields which are predefined.

**Steps to reproduce:** 

1. Nav drawer
2. Individual collection sheet
3. You will see a "Generate" and a "Clear" button. The clear button is not necessary.
 

**Expected behaviour:** 
The clear button should become active when the form is filled or it should be completely removed.

**Observed behaviour:** 
The "clear" button remains inactive even after filling the form.

**Device and Android version:** 
Google Pixel 2 Emulator, Android 9 Pie

**Screenshots:** 

![Screenshot_1585731000](https://user-images.githubusercontent.com/11456907/78119117-d673f600-73ff-11ea-95a0-c190663db28a.png)

**Comment by casyazmon** [comment]
I am working on this.

**Comment by robustTechie** [comment]
Clear button is not unnecessary button  now it is not interactive, check the fix in #1253 . Please close this issue.

**Comment by casyazmon** [comment]
ok @robustTechie the button remains inactive throughout. i  think it should be active when the fields are filled.

**Comment by casyazmon** [comment]
ok @robustTechie. I didn't notice
