### ISSUE TITLE
Implement Material Design

### ISSUE THREAD

**Issue by chhavip** [openMF/android-client#149]
With reference to https://mifosforge.jira.com/projects/MIFOSAC/issues/MIFOSAC-84?filter=allopenissues
I have created this issue so we can discuss material design implementation on the application screen by screen and everyone can give their opinion.
We can take pointers from the [provided mock-ups ](https://mifosforge.jira.com/wiki/download/attachments/34111558/Mifos%20Android%20Mockups.pdf?version=8&modificationDate=1380225023161&api=v2)

**Comment by ishan1604** [comment]
Fixed!
