### ISSUE TITLE
Sync Survey not disable automatically

### ISSUE THREAD

**Issue by iamsh4shank** [openMF/android-client#1490]
**Summary:** 

On successful completion of the sync survey switch doesn't disable automatically.

**Steps to reproduce:** 

settings> sync survey

**Expected behaviour:** 

After a successful completion switch should close automatically.

**Observed behaviour:** 

On successful completion of the sync survey switch doesn't disable automatically.

**Device and Android version:** 

Android Version 9.0
Realme 5

**Screenshots:** 

![settings](https://user-images.githubusercontent.com/52889867/78941406-40ae2a00-7ad5-11ea-9baa-41de067a35d6.gif)

**Comment by robustTechie** [comment]
I would like to work on this issue.

**Comment by sachin-0102** [comment]
Hey @robustTechie , are you working on this issue. If not, can I take it up?

**Comment by PatelVatsalB21** [comment]
hey! if anyone don't mind I would like to suggest that why don't you add Imagebutton with sync symbol as it is for momentary use only.

**Comment by PatelVatsalB21** [comment]
hey @robustTechie can i work on this issue, please read my previous comment.

**Comment by robustTechie** [comment]
@PatelVatsalB21 yes you can work on this :)

**Comment by robustTechie** [comment]
Hey @PatelVatsalB21 can you do something like if the sync is complete it will automatically disable the switch preference?

**Comment by PatelVatsalB21** [comment]
Actually I removed switch preference that needs extra boolean check if sync is complete, and place button if clicked shows sync dialog, but if you want i can undo to switch preference, and as per you said i can make a static boolean in setting fragment which turns off when  **showSurveysSyncSuccessfully()** method in sync dialog fragment is called. So please tell me what to do. Also dont forget to see my pr #1600.

**Comment by robustTechie** [comment]
yeah ig for now we can go with the switch

**Comment by PatelVatsalB21** [comment]
Hey @robustTechie i tried many ways making static boolean or switch but it gave no resu. Its working in mobile but didn't passed gradle check anytime. It failed gradle check with gc overhead memory limit and if not so findbugs error shown as a bad practice. 
![findBugs](https://user-images.githubusercontent.com/70195106/101603550-bfbd7e80-3a25-11eb-9e94-36facabe65ba.PNG)
