### ISSUE TITLE
App crashes if user clicks twice on date textView anywhere in the app.

### ISSUE THREAD

**Issue by iamsh4shank** [openMF/android-client#1506]
**Summary:** 

If the user clicks on date textView twice then the app crashes. This bug could be found anywhere in the app wherever the date textView is present.

**Steps to reproduce:** 

In any date, TextView just click twice

**Expected behaviour:** 

It shouldn't crash as it is affecting the UX.

**Observed behaviour:** 

If the user clicks on date textView twice then the app crashes. This bug could be found anywhere in the app wherever the date textView is present.

**Device and Android version:** 

Android Version 9.0
Realme 5

**Screenshots:** 

This can be found anywhere in the app wherever the date textView is present.

**Comment by robustTechie** [comment]
I would like to work on this issue.

**Comment by sachin-0102** [comment]
Can I work on this issue?

**Comment by robustTechie** [comment]
> Can I work on this issue?

Yeah sure go ahead:)

**Comment by sachin-0102** [comment]
> > Can I work on this issue?
> 
> Yeah sure go ahead:)

Is there a demo account through which I can login into the app. If not please provide me with the credentials because there is no such thing as create account

**Comment by sachin-0102** [comment]
@robustTechie , would you review the PR that I made and tell me why is the build failing continuously because I ran it on 4 different APIs and it worked fine on all the devices.

**Comment by robustTechie** [comment]
> @robustTechie , would you please review the PR that I made and tell me why is the build failing continuously because I ran it on 4 different APIs and it worked fine on all the devices.

I had commented a few things just check it and fix those errors.
