### ISSUE TITLE
Wrong message in document of identifier 

### ISSUE THREAD

**Issue by iamsh4shank** [openMF/android-client#1508]
**Summary:** 

The wrong message is visible in the document screen of the identifier. If the user adds some documents then also it shows that "There is No Document to show".

**Steps to reproduce:** 

Open any client> click on document>press add document>then add a new document

**Expected behaviour:** 

When the list is empty then it will show "No document to show"  otherwise it doesn't show this.

**Observed behaviour:** 

The wrong message is visible in the document screen of the identifier. If the user adds some documents then also it shows that "There is No Document to show".

**Device and Android version:** 

Android Version 9.0
Realme 5

**Screenshots:** 

![ezgif com-resize](https://user-images.githubusercontent.com/52889867/80239364-b988b680-867d-11ea-95df-28274fc9c364.png)

**Comment by robustTechie** [comment]
I would like to work on this issue.

**Comment by sachin-0102** [comment]
This doesn't happen in my device @robustTechie . Please check if the issue was resolved

**Comment by robustTechie** [comment]
@sachin-0102 it is still there as the screen is not directly updated if you add a new document. Once check it :)

**Comment by The-Anton** [comment]
I would like to work upon this

**Comment by sachin-0102** [comment]
@The-Anton I'm already working on this issue

**Comment by sachin-0102** [comment]
@robustTechie Please close this issue. This issue has been resolved.

**Comment by Aditya-gupta99** [comment]
Issue has been resolved.
