### ISSUE TITLE
Cannot add notes for individual clients

### ISSUE THREAD

**Issue by Sachit1137** [openMF/android-client#1515]
**Summary:** 

There is no button to add new notes for individual clients. A Floating Action Button (FAB) should be shown to do so.

**Steps to reproduce:** 

1. Goto Clients
2. Click on any client
3. Click 3 dot menu and chose Notes
4. No button to add new Notes

**Expected behaviour:** 

There should be a Floating Action Button to add new Notes

**Observed behaviour:** 

FAB should be displayed.

**Device and Android version:** 

Device - Samsung Galaxy S10e
Android Version - 10 (Android Q)
Custom ROM - Samsung One UI version 2.1

**Screenshots:** 
![image](https://user-images.githubusercontent.com/55988870/80772704-a1091800-8b25-11ea-97e7-33adbeebdb3a.png)

**Comment by robustTechie** [comment]
Hey, @Sachit1137 issue #1291 is the same issue as this, please close this issue.

**Comment by Sachit1137** [comment]
ok
