### ISSUE TITLE
3 Fragments how to handle progress bar visibility 

### ISSUE THREAD

**Issue by developersamuelakram** [openMF/android-client#1520]
I am using ListView (which means I am using only one xml layout for my three fragments) and the visibility of the progressbar is not working. Can someone please help. I am posting the code of one of the 3 fragments ( code in other two frag looks the same)

Please tell me what I should add and should I add to each fragment, what am I missing. Can someone help.

Earlier I had tried adding code and set visibility it did not work thats why I have deleted it, so someone can tell me where exactly and what exact needs to be inserted. Thank you so much.

public class Uspolitics extends Fragment implements LoaderManager.LoaderCallbacks> {

private static final String LOG_TAG = Uspolitics.class.getSimpleName();

private static final String NEWS_API = "https://newsapi.org/v2/top-headlines?country=us&apiKey=6a6f7c77766442acb20c86157a152131";
private NewsAdapter mAdapter;
private static final int EARTHQUAKE_LOADER_ID = 1;
private TextView mEmptyStateTextView;

public Uspolitics() {
    // Required empty public constructor
}

@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container,
                         Bundle savedInstanceState) {
    // Inflate the layout for this fragment
    View rootView = inflater.inflate(R.layout.activity_all, container, false);

    mEmptyStateTextView = rootView.findViewById(R.id.empty_view);
    ListView listView = (ListView) rootView.findViewById(R.id.list);
    listView.setEmptyView(mEmptyStateTextView);

    mAdapter = new NewsAdapter(getActivity(), new ArrayList<News>());
    listView.setAdapter(mAdapter);

    listView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
        @Override
        public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
            News currentNews = mAdapter.getItem(position);

            Uri uriweb = Uri.parse(currentNews.getURL());
            Intent webIntent = new Intent(Intent.ACTION_VIEW, uriweb);
            startActivity(webIntent);

        }
    });
ConnectivityManager connMgr = (ConnectivityManager) getActivity().getSystemService(Context.CONNECTIVITY_SERVICE);

        // Get details on the currently active default data network
        NetworkInfo networkInfo = connMgr.getActiveNetworkInfo();

        if (networkInfo != null && networkInfo.isConnected()) {
            LoaderManager loaderManager = getActivity().getSupportLoaderManager();
            loaderManager.initLoader(EARTHQUAKE_LOADER_ID, null, this);

        } else {

            // Update empty state with no connection error message
            if (networkInfo == null) {

                mEmptyStateTextView.setText("NO INTERNET CONNECTION");
            }
        }

    return rootView;

}

@Override
public Loader<List<News>> onCreateLoader(int i,  Bundle bundle) {

    return new PoliticsLoader(getContext(), NEWS_API);

}

@Override
public void onLoadFinished( Loader<List<News>> loader, List<News> news) {

    mAdapter.clear();
    if (news!=null && !news.isEmpty()) {
        mAdapter.addAll(news);
    }

}

@Override
public void onLoaderReset( Loader<List<News>> loader) {
    mAdapter.clear();

   }
}

**Comment by sachin-0102** [comment]
Hi @developersamuelakram , what are you trying to create here... please ellaborate..
