### ISSUE TITLE
Enhancement: UI enhancement in login, dashboard and other activities

### ISSUE THREAD

**Issue by robustTechie** [openMF/android-client#1532]
**Summary:** 

UI enhancement is required in the dashboard, login, client details, and individual collection sheets
**Steps to reproduce:** 

**Device and Android version:** 
Android Version: 9.0
Model: Redmi Note 4

**Comment by deepak-prajapatii** [comment]
@robustTechie Can I work on this issue?

**Comment by danishjamal104** [comment]
> @robustTechie Can I work on this issue?

There is already a PR send by @robustTechie

**Comment by deepak-prajapatii** [comment]
@danishjamal104 okay. Can you help me in contributing? I am new to open source and want to contribute to "The Mifos Initiative". I researched a lot about "The Mifos Initiative" for a week. I look at many issues on this repo but most of them are solved already or there is already a PR  regarding that issue. Please help me.
