### ISSUE TITLE
Enhancement :The keypad should disappear when opening another menu

### ISSUE THREAD

**Issue by sachin-0102** [openMF/android-client#1549]
**Summary:** 

The keypad should disappear when the user opens another menu on the screen

**Steps to reproduce:** 

1. Open the app and tap on the text field that appears
2. Click on the menu option at the top-left corner
3. The keyboard doesn't disappear.

**Expected behaviour:** 

The keyboard should disppear as soon as the menu is oppened

**Observed behaviour:** 

The keyboard doesn't disappear

**Device and Android version:** 

Pixel 2 
Android 9

![GIF-200828_103705](https://user-images.githubusercontent.com/61426967/91523566-aed77a00-e91a-11ea-82d2-fee859bf84d4.gif)

**Comment by sachin-0102** [comment]
I would like to work on this issue.

**Comment by robustTechie** [comment]
@sachin-0102 This issue is already reported #1234. Please close duplicate issues.

**Comment by sachin-0102** [comment]
Oh okay. I'll close this issue @robustTechie. Thanks for the update
