### ISSUE TITLE
Improve Information displayed for Centers

### ISSUE THREAD

**Issue by chhavip** [openMF/android-client#155]
Compared to Community App, less amount of information is accessible in mobile application and also no indications are present if any information is missing.
Aim to include the following:
 1) Status of Center
 2) Indication if no groups are present in a center
 3) Account Id for Center
 4) Next meeting of a particular group

These are the issues I thought were needed, are they significant enough to be worked upon?

**Comment by mayank-kgp** [comment]
@chhavip  Please give an update on this. 
Is it resolved or are u still working on this?

**Comment by therajanmaurya** [comment]
This issue continues Here #390
