### ISSUE TITLE
The gender dropdown menu includes spammed unexisting genders

### ISSUE THREAD

**Issue by sachin-0102** [openMF/android-client#1555]
**Summary:** 

In the create new client activity the gender dropdown menu includes a lot of spammed genders

**Steps to reproduce:** 

Open create a new client activity> Open gender dropdown menu

**Expected behaviour:** 

Their should be only 3 kinds of genders.

**Observed behaviour:** 

There are about 10 non existing genders

**Device and Android version:** 
Realme 7
Android 10

**Screenshots:** 

![upload.gif](https://user-images.githubusercontent.com/61426967/93840766-2b0d7500-fcaf-11ea-9f2f-da66e0cc0447.gif)

**Comment by sachin-0102** [comment]
@robustTechie please check this issue. I would like to work on it.

**Comment by robustTechie** [comment]
This is not a valid issue as it is fetching the genders from the clients template. So whatever it is showing is only for demo. So no need of doing this.

**Comment by sachin-0102** [comment]
Alright...
