### ISSUE TITLE
Gradle Sync Failed, Plugin with Id "findbugs" not found.

### ISSUE THREAD

**Issue by aryanharitsh123** [openMF/android-client#1556]
Trying to build the project But getting Gradle sync failed Plugin with ID "findbugs" not found.
![Error](https://user-images.githubusercontent.com/37960580/97735586-84639200-1b00-11eb-88e3-7cf0ee63ba1c.png)

**Comment by robustTechie** [comment]
Hello, @aryanharitsh123 is the project successfully built?

**Comment by aryanharitsh123** [comment]
> Hello, @aryanharitsh123 is the project successfully built?
> 

Nope.

**Comment by robustTechie** [comment]
Hey @aryanharitsh123 can you once check this file `android-client/config/quality/quality.gradle` is this contain something like `apply plugin: 'findbugs'` and `task findbugs...`

**Comment by aryanharitsh123** [comment]
@robustTechie Yes These lines are present in the above-mentioned file. I tried recloning but  still the same error.
![buildfailed](https://user-images.githubusercontent.com/37960580/99178432-02e34500-2739-11eb-8d10-dfdd6da0f781.png)

**Comment by robustTechie** [comment]
Can you once check the last commit

**Comment by aryanharitsh123** [comment]
Yes, now it is working fine on Gradle version "4.10.1".

**Comment by UjjwalDeep** [comment]
> Yes, now it is working fine on Gradle version "4.10.1".

How you solved the issue please explain. I am having the same issue.

**Comment by francisguchie** [comment]
Changed the gradle version to 4.10.1
