### ISSUE TITLE
Unable to update client image

### ISSUE THREAD

**Issue by danishjamal104** [openMF/android-client#1561]
**Summary:** 

Unable to upload client image in clientInfo page.

**Steps to reproduce:** 
* **Step1-** Go to `dashboard` and search for any client.
* **Step2-** Click on client to see his/her info.
* **Step3-** On info page click on profile image and select `upload new photo`.
* **Step4-** Select any image and observe the message in snackbar `Unable to update image`.

**Expected behaviour:** 
Update the client profile image and display the new image instead of old.

**Observed behaviour:** 
Not able to update client profile image.

**Device and Android version:** 
* **Device:** Pixel 2 XL Emulator
* **Android Version:** API 27 Android O(Oreo) - 8.1.0

**Screenshots:** 

<img width="333" alt="Screenshot 2020-11-15 at 10 44 03 PM" src="https://user-images.githubusercontent.com/31315800/99517564-827d4800-29b5-11eb-9ca7-7aa9883b9b4c.png">

**Comment by robustTechie** [comment]
@danishjamal104 this issue is because of the API endpoints we are currently using.
