### ISSUE TITLE
Dashboard doesn't show proper toast when the user is not connected to the network.

### ISSUE THREAD

**Issue by danishjamal104** [openMF/android-client#1580]
**Summary:** 
Dashboard doesn't show proper toast when the user is not connected to the network.

**Steps to reproduce:** 
Search anything in the dashboard while you are disconnected from the internet.

**Expected behaviour:** 
`No internet connection` toast should be displayed for no internet connectivity case.

**Observed behaviour:** 
Invalid toast `Failed to fetch resource` toast is shown.

**Device and Android version:** 
* Device: Pixel 2 XL Emulator
* Android Version: API 27 Android O(Oreo) - 8.1.0

**Screenshots:** 

<img width="333" alt="Screenshot 2020-11-15 at 10 44 03 PM" src="https://user-images.githubusercontent.com/31315800/100547392-7edaa280-328c-11eb-86cb-ee2551e5442e.jpg">

**Comment by deepak-prajapatii** [comment]
@danishjamal104 Can I work on this issue?

**Comment by danishjamal104** [comment]
> @danishjamal104 Can I work on this issue?

This issue is already resolved in PR #1582

**Comment by deepak-prajapatii** [comment]
> > @danishjamal104 Can I work on this issue?
> 
> This issue is already resolved in PR #1582

@danishjamal104 okay
