### ISSUE TITLE
New Feature: Disconnecting the internet should auto-trigger offline mode and vice versa.

### ISSUE THREAD

**Issue by danishjamal104** [openMF/android-client#1584]
**Summary:** 

Disconnecting the internet should auto-trigger offline mode and vice versa. So if the user is using the app online mode then if he disconnects from the network then the app automatically switches to offline mode

**Expected behaviour:** 

Disconnecting from the internet should auto toggle offline mode.

**Observed behaviour:** 

Disconnect device from the internet doesn't automatically toggle offline mode, instead, the user has to press the toggle button manually in the nav drawer.

**Device and Android version:** 

* ANY

**Comment by danishjamal104** [comment]
I am working on this issue

**Comment by danishjamal104** [comment]
I think that we should give an option to the user where he can opt for the automatic transition between offline and online.
Because for some user it may be annoying that app automatically switches whenever he disconnects from the internet.
What do all say??

**Comment by PatelVatsalB21** [comment]
I would like to work on it, but someone needs to approve first.

**Comment by PatelVatsalB21** [comment]
Also i think this issue will be redundant. I have already open it on this topic what do you say @danishjamal104 ?

**Comment by PatelVatsalB21** [comment]
I thought I was waiting for approval to work on. This isn't fair @danishjamal104 😐

**Comment by danishjamal104** [comment]
> I thought I was waiting for approval to work on. This isn't fair @danishjamal104 😐

Your issue is regarding the sync service which is based on network receiver, so please be more descriptive and clear in your issue about what you are trying to implement next time. Also, I haven't resolved your issue I simply added a new feature of auto-trigger offline and online mode. If still anything bothers you please feel free to ping me. Thank You

**Comment by PatelVatsalB21** [comment]
i have no issues with your work but i was ready to work and as i am new i have less opportunities to work on. No worries. 👍 

> > I thought I was waiting for approval to work on. This isn't fair @danishjamal104 😐
> 
> Your issue is regarding the sync service which is based on network receiver, so please be more descriptive and clear in your issue about what you are trying to implement next time. Also, I haven't resolved your issue I simply added a new feature of auto-trigger offline and online mode. If still anything bothers you please feel free to ping me. Thank You
