### ISSUE TITLE
New Feature: Adding Initial letter based avatar bitmap to circular image view

### ISSUE THREAD

**Issue by PatelVatsalB21** [openMF/android-client#1591]
**Summary:** 
Currently all circular image view in navigation view, client adapter, and client details have no icon in that image view.
![Screenshot_20201203-140910](https://user-images.githubusercontent.com/70195106/100985468-061c6480-3572-11eb-899d-edeaafb5a3e7.jpeg)
![Screenshot_20201203-140925](https://user-images.githubusercontent.com/70195106/100985478-09afeb80-3572-11eb-8bbb-9c9c9e9d2ceb.jpeg)
![Screenshot_20201203-140949](https://user-images.githubusercontent.com/70195106/100985481-0c124580-3572-11eb-9a8b-17d95752eb5e.jpeg)

I want to suggest that instead of this dummy images if we add bitmap with Intial letter of user or client,
like if user is **Amit** then navigation view circular image will be like 
![snip](https://user-images.githubusercontent.com/70195106/100985827-71663680-3572-11eb-827e-7cc849470759.PNG)

These changes should be applied to navigation view header, client adapter items and client info activity. This will make app look more attractive and beautiful and sense of those circular imageview.

**Device and Android version:** 

Any

**Comment by PatelVatsalB21** [comment]
Should i start working on this feature?

**Comment by danishjamal104** [comment]
Nice observation @PatelVatsalB21 , keep going :)
