### ISSUE TITLE
Invalid Toast message in Checker Inbox

### ISSUE THREAD

**Issue by ritish099** [openMF/android-client#1595]
**Summary:** 

On deleting and rejecting a request wrong toast is shown

**Steps to reproduce:** 

Open the app and open Checker Inbox & Tasks and then open checker inbox. Then try to delete and reject some request to see the toast message

**Expected behaviour:** 

Toast Message should be "Entry Rejected" and "Entry Deleted" respectively

**Observed behaviour:** 

Toast Message is showing "ENTRYREJECTED" and "ENTRYDELETED" respectively

**Device and Android version:** 

Samsung J6, Android 10

**Screenshots:** 

<img width="333" alt="alternative text" src="https://user-images.githubusercontent.com/54978105/101125778-0e32dd80-3620-11eb-8671-6909a0a0818d.jpg">

<img width="333" alt="alternative text" src="https://user-images.githubusercontent.com/54978105/101125787-125efb00-3620-11eb-96b4-0dbc3af6b981.jpg">

**Comment by ritish099** [comment]
Can i work on it ?

**Comment by danishjamal104** [comment]
Hey @ritish099 , please reduce the size of screen shot since its really big. You can use below syntax if you want. Thanks :)
```html
<img width="333" alt="alternative text" src="enter url here">
```

**Comment by danishjamal104** [comment]
> Can i work on it ?

Good to go.

**Comment by ritish099** [comment]
@danishjamal104 kindly check it out.

**Comment by Aditya-gupta99** [comment]
The issue has already been resolved
