### ISSUE TITLE
New Feature: Adding FAB on dashboard for client, groups and centres.

### ISSUE THREAD

**Issue by PatelVatsalB21** [openMF/android-client#1608]
**Summary:** 
Instead of menu on Right top of screen Floating Action Button can be added on dashboard that makes screen more beautiful and less confusing. 

**Expected behaviour:** 
New client, group or centre can be added from this FAB from dashboard activity.

**Device and Android version:** 
ANY

**Comment by PatelVatsalB21** [comment]
I am working on this feature.

**Comment by robustTechie** [comment]
Hey, @PatelVatsalB21 this issue is already raised in issue number #1337 and the fix is already sent in PR #1521

**Comment by PatelVatsalB21** [comment]
Ok 👍
