### ISSUE TITLE
Overscroll effect in Navigation Bar

### ISSUE THREAD

**Issue by PatelVatsalB21** [openMF/android-client#1627]
**Summary:** 
If we slide finger vertically in navigation bar, overscroll effect is visible even though menu isn't scrolling. This should be avoided.

**Expected behaviour:** 
No effects should be visible to user when scrolling vertically

**Device and Android version:** 

Any

**Screenshots:** 

![GIF-201212_130108 1](https://user-images.githubusercontent.com/70195106/101978370-5aae9680-3c7a-11eb-952c-cc011176f067.gif)

**Comment by PatelVatsalB21** [comment]
I am working on this issue

**Comment by danishjamal104** [comment]
Hey @PatelVatsalB21 , I think that over scroll effect is necessary to indicate that scrolling is over and also it adds to UX(user experience). And this is for what we have ever scrolling effect. I don't think this change is required. What do you say @robustTechie ?

**Comment by PatelVatsalB21** [comment]
> Hey @PatelVatsalB21 , I think that over scroll effect is necessary to indicate that scrolling is over and also it adds to UX(user experience). And this is for what we have ever scrolling effect. I don't think this change is required. What do you say @robustTechie ?

@danishjamal104 i agree with if it was recyclerview or listview or if menu is big and actually scrolls, but as you can see in above GIF, menu is limited and fits screen and not scrolling, showing over scroll indicators not serves the point, atleast that what i think and have seen in various app with limited menu.

**Comment by robustTechie** [comment]
Yeah, it's fine @PatelVatsalB21, also as we are going to merge the bottom nav feature so it would be good to remove scroll for very fewer menu :)
