### ISSUE TITLE
UI enhancements required in fragment_add_savings_account

### ISSUE THREAD

**Issue by PatelVatsalB21** [openMF/android-client#1632]
**Summary:** 

fragment_add_savings_account has following UI flaws. No padding on whole layout, spinner background colors does not match background checkbox text not aligned properly, spacing between some elements are not consistent

**Expected behaviour:** 

Padding on main layout should be applied such that scrollbar remains at right corner, checkbox text should be aligned properly and spacing should be consistent between elements and background of spinners should be white or transparent.

**Device and Android version:** 

Lenovo Tab 7
Android 7

**Screenshots:** 
![Screenshot_20201215-201903 1](https://user-images.githubusercontent.com/70195106/102230977-7da7a780-3f13-11eb-8bd6-53ea55cef6af.jpeg)
![Screenshot_20201215-201909 1](https://user-images.githubusercontent.com/70195106/102230914-6d8fc800-3f13-11eb-9856-1844ab7e1320.jpeg)

**Comment by PatelVatsalB21** [comment]
I am working on this issue.

**Comment by danishjamal104** [comment]
@PatelVatsalB21 please use the smaller size for screenshot to make it easy for developers to see what are you trying to point to.

**Comment by danishjamal104** [comment]
> @PatelVatsalB21 please use the smaller size for screenshot to make it easy for developers to see what are you trying to point to.

`<img width='333' alt='ss' src='<enter url here>'>`
use the above tag to set image in md

**Comment by thisrahul** [comment]
can i work on this??

**Comment by PatelVatsalB21** [comment]
> can i work on this??

@thisrahul this has been solved in #1633.
