### ISSUE TITLE
Unnecessary logout option in every fragment

### ISSUE THREAD

**Issue by PatelVatsalB21** [openMF/android-client#1645]
**Summary:** 
Alongwith Search fragment on Dashboard, logout option is visible everywhere if it is clients, centers or groups and also in other activities. Logot is used less frequently so its visibility in every fragment does not suits with menu.

**Expected behaviour:** 
Instead of placing logout option in menu it is good to place it in Navigation Drawer

**Device and Android version:** 
Any

https://user-images.githubusercontent.com/70195106/102690701-3e3bcc80-422d-11eb-86a0-0aa1611d8388.mp4

**Comment by danishjamal104** [comment]
@PatelVatsalB21 , how did you ember video in md? It will help me alot.

**Comment by PatelVatsalB21** [comment]
@danishjamal104 its new feature in github addition of support for .mp4 and .MOV files
