### ISSUE TITLE
UI enhancements in client identifier

### ISSUE THREAD

**Issue by danishjamal104** [openMF/android-client#1647]
**Summary:** 

The client identifier is very badly laid out it makes very unclear what things are depicting what.

**Steps to reproduce:** 

1. Visit the client details page.
2. Click on 3 dots on the top right to expand menu.
3. Select `identifier`.
4. UI of identifier item is unorganised.

**Expected behaviour:** 

Organized material UI

**Observed behaviour:** 

Unorganised and unclear UI.

**Device and Android version:** 

* Samsung Tab A7
* Android 10

**Screenshots:** 

<img width='333' alt='ss' src='https://user-images.githubusercontent.com/31315800/102693635-0be89a00-4242-11eb-9219-89812aa102d6.jpeg'>

**Comment by PatelVatsalB21** [comment]
@danishjamal104 that might be due to you are using 10 inch tablet as for me its normal.

**Comment by danishjamal104** [comment]
> @danishjamal104 that might be due to you are using 10 inch tablet as for me its normal.

I have checked on multiple devices

**Comment by danishjamal104** [comment]
Also its not only about orientation, padding and margins are also not looking good
