### ISSUE TITLE
Icon display error in Loan transaction items

### ISSUE THREAD

**Issue by PatelVatsalB21** [openMF/android-client#1648]
**Summary:** 
Icon of items of Loan Transactions has error which does not show proper icon, in both expanded and collapsed mode.

**Steps to reproduce:** 
1 Open Client Details
2 Expand Loan accounts and click any item
3 Open menu and click Transactions

**Expected behaviour:** 
It should show + and - symbols in circle

**Observed behaviour:** 
x is visible in textview

**Device and Android version:** 
Lenovo Tab 7
Android 7

https://user-images.githubusercontent.com/70195106/102696672-f0878a00-4255-11eb-8b4b-a4a05948f0c0.mp4

**Comment by mananvirmani611** [comment]
@PatelVatsalB21 I think, on clicking anywhere on the entire row, not only on the +/- button, it is expanding/collapsing, can I work on improving this ??

**Comment by PatelVatsalB21** [comment]
@mananvirmani611 Its working correctly by clicking anywhere on row it should expand. And this issue has been fixed in #1649. You can try any issue whose pr is not made.
