### ISSUE TITLE
Saving Account Transaction details not displayed properly

### ISSUE THREAD

**Issue by danishjamal104** [openMF/android-client#1690]
**Summary:** 

Transaction details are not displayed properly. When the user clicks on any transaction only limited info is shown that also in a Toast which makes it very uncomfortable to see transactions detail.

**Steps to reproduce:** 

Go to `Saving Account Summary` page and click on any transaction to see its details.

**Expected behaviour:** 

Proper dialog box should be open to display the required details.

**Observed behaviour:** 

Only limited info is shown as a toast message.

**Device and Android version:** 

* SAMSUNG TAB A7
* ANDROID 10

**Screenshots:** 

<img width='333' alt='ss' src='https://user-images.githubusercontent.com/31315800/103259086-fbf95480-49bd-11eb-8fca-7be3036538d0.jpeg'>

**Comment by PatelVatsalB21** [comment]
@danishjamal104 can i work on it?

**Comment by danishjamal104** [comment]
> @danishjamal104 can i work on it?

I have already started working on it, sorry I missed commenting here

**Comment by Pratham2305** [comment]
@danishjamal104 are you still working on this issue?

**Comment by PatelVatsalB21** [comment]
@Pratham2305 he has already made or #1695 for this issue.

**Comment by danishjamal104** [comment]
> @danishjamal104 are you still working on this issue?

Yes, I have already solved this issue. Thanks for asking I made a typo in the tag that's why no PR was linked with this issue.
