### ISSUE TITLE
UI enhancements required in ChargeDialogFragment

### ISSUE THREAD

**Issue by PatelVatsalB21** [openMF/android-client#1698]
**Summary:** 
Edittexts have grey background that does not looks good and colour of save button does not match with theme colour. Also dialog does not have heading

**Steps to reproduce:** 
1 Open Client Details
2 Open Charges from menu
3 Tap on + symbol

**Expected behaviour:** 
Editexts should be in transparent or white background. Also heading should be added and button color should be changed

**Device and Android version:** 
Lenovo Tab 7
Android 7

**Screenshots:** 
<img width="333" alt="ss" src="https://user-images.githubusercontent.com/70195106/103419293-6f66b600-4bb8-11eb-8724-9712141e61bf.jpeg">

**Comment by PatelVatsalB21** [comment]
I am working on this issue

**Comment by Arjun2905** [comment]
is this issue still open .
If yes then I would like to work on it .

**Comment by PatelVatsalB21** [comment]
> is this issue still open .
> If yes then I would like to work on it .

@Arjun2905 this issue has been solved in #1699
