### ISSUE TITLE
UI enhancement possible in Login Activity

### ISSUE THREAD

**Issue by PatelVatsalB21** [openMF/android-client#1712]
**Summary:** 
As visible in image attached username and password fields in Login Activity are plain edittext but as we see nowadays drawables are added with edittext. Similarly we can add drwables to user name and password 

**Observed behaviour:** 
Plain edittext without drawables

**Device and Android version:** 
ANY

**Screenshots:** 
<img width="333" src="https://user-images.githubusercontent.com/70195106/104354100-b9dc2100-552e-11eb-81e4-55572ec2051f.jpeg">

**Comment by mananvirmani611** [comment]
Hi @PatelVatsalB21, May you please tell can I  work on this ??

**Comment by PatelVatsalB21** [comment]
@mananvirmani611 solutions for this pr has been already made in #1713

**Comment by mananvirmani611** [comment]
@PatelVatsalB21 ok, thanks for replying
