### ISSUE TITLE
UI bug in ClientListFragmentItem 

### ISSUE THREAD

**Issue by NikunjGarg2000** [openMF/android-client#1716]
**Summary:** 

UI bug in ClientListFragmentItem
In row_center_list_item.xml, if center name is large then center id moves to next line which doesn't looks good.

**Steps to reproduce:** 

Just some changes in xml file can make it easily.

**Device and Android version:** 

ALL

**Screenshots:** 

<img width="300" height="450" src="https://user-images.githubusercontent.com/67901968/104811600-c4463580-5822-11eb-96c0-70c052cd0bdb.jpeg">

**Comment by danishjamal104** [comment]
@NikunjGarg2000 , the issue title and summary don't match please verify it.

**Comment by NikunjGarg2000** [comment]
Thanks @danishjamal104 , I modified it.
