### ISSUE TITLE
UI Enhancement in Center details fragment

### ISSUE THREAD

**Issue by Abhinavtdk** [openMF/android-client#1720]
**Summary:** 

The details shown in center details fragment are aligned towards the ends without any padding. Adding padding to this makes the whole page look more appealing.

**Steps to reproduce:** 

1)Go to the centers option in right menu
2)Click on any center.

**Observed behaviour:** 

Center details are aligned to the end, not so appealing to a user.

**Device and Android version:** 

ANY

**Screenshots:** 

<img src = "https://user-images.githubusercontent.com/52701183/104844556-ea3d0a00-58f6-11eb-86ee-407282b3c0da.jpg" width = "300" height = "900">

**Comment by danishjamal104** [comment]
Please explore the already created issues since a similar issue is already created at #1601 and is resolved at #1603 , so its always better to discuss before sending PR.

**Comment by Abhinavtdk** [comment]
Oh, Sorry for that, I'll close this pr

**Comment by danishjamal104** [comment]
> Oh, Sorry for that, I'll close this pr

NP, Thanks
