### ISSUE TITLE
Keyboard related issue

### ISSUE THREAD

**Issue by Abhinavtdk** [openMF/android-client#1726]
**Summary:** 

Soft keyboard doesn't close after the last edit text in create client, center and group fragments.

**Steps to reproduce:** 

1)Go to any of create client, create group or create center fragments.
2)Type anything in the last edit text available and press next.

**Expected behaviour:** 

On pressing next, keyboard should collapse and the last edit text shouldn't be in focus

**Observed behaviour:** 

On pressing next in the last edit text, the keyboard doesn't collapse.

**Device and Android version:** 

RedMi Note 8 Pro
Android 9

**Screenshots:** 

https://user-images.githubusercontent.com/52701183/105319643-2ae49e00-5beb-11eb-9fd4-9f2a864be7be.mp4

**Comment by kartikeysaran** [comment]
Can i work on this issue

**Comment by mananvirmani611** [comment]
Hi @Abhinavtdk , can I work on this issue ??

**Comment by Abhinavtdk** [comment]
> Hi @Abhinavtdk , can I work on this issue ??

I've already worked on this, #1727 fixes it

**Comment by mananvirmani611** [comment]
@Abhinavtdk So isn't it merged with the master branch ??

**Comment by Abhinavtdk** [comment]
> @Abhinavtdk So isn't it merged with the master branch ??

Not yet
