### ISSUE TITLE
Invalid toast message in Datatables

### ISSUE THREAD

**Issue by PatelVatsalB21** [openMF/android-client#1728]
**Summary:** 
On opening specific Datatable if there is error, toast is shown which has a typing error.

**Steps to reproduce:** 
1 Open Client or Group Details
2 Open Datatables 
3 Open Specific Datatable

**Expected behaviour:** 
Toast should be : "Failed to fetch DataTable Info"

**Observed behaviour:** 
Toast shown : "Failed to fetch DataTableInfo"

**Device and Android version:** 
Any

**Recording:** 

https://user-images.githubusercontent.com/70195106/105811167-314f8d00-5fd2-11eb-9caf-8b88f4b548a5.mp4

**Comment by danishjamal104** [comment]
@PatelVatsalB21 , I think their is type in below section of your issue description, please cross check once.
```
Expected behaviour:
Toast should be : "Failed to fetch DataTable Info"

Observed behaviour:
Toast shown : "Failed to fetch DataTable Info"
```

**Comment by PatelVatsalB21** [comment]
@danishjamal104 thanks for informing. I updated comment.

**Comment by danishjamal104** [comment]
> @danishjamal104 thanks for informing. I updated comment.

NP
