### ISSUE TITLE
Improper dimensions of text view and absent padding in Payment Details

### ISSUE THREAD

**Issue by PatelVatsalB21** [openMF/android-client#1742]
**Summary:** 
As we see in payment details layout Total charges textview is wraped text and it has no bottom padding. It has fixed sized of 120 dp which makes it look like this even though no charges are present.

**Steps to reproduce:** 
1 Open Individual Collection sheet
2 Fill New Collection Sheet
3 Open any one item from list 

**Expected behaviour:** 
Width of this textview should be `wrap content` and bottom padding should be applied.

**Device and Android version:** 
Any

**Screenshots:** 
<img src="https://user-images.githubusercontent.com/70195106/106757679-a831f900-6656-11eb-98c3-2b181d88e838.jpeg" width="333">

**Comment by mananvirmani611** [comment]
@PatelVatsalB21 , this issue is shown as an open issue, although you had already fixed it, may you please tell me why this is shown as open ?? (and this is the case with many similar issues, which had been fixed, but are still showing open)

**Comment by PatelVatsalB21** [comment]
@mananvirmani611 these issues are still there because pull request is made but not merged. Once it gets merged that specific issue resolves. It to all issues.

**Comment by mananvirmani611** [comment]
@PatelVatsalB21 So, can I also make changes in the code, and post them in the comments of a particular issue ??

**Comment by PatelVatsalB21** [comment]
@mananvirmani611 if you found issue that hasn't been raised before then you can creat new issue and make changes locally on your system in new branch and then make pr for that issue. You should go through how GitHub works and for better guidance from community please join on Gitter from here Mifos Android Client Gitter community

**Comment by mananvirmani611** [comment]
@PatelVatsalB21 thanks sir !!
