### ISSUE TITLE
Cancel button not working properly in Payment Details

### ISSUE THREAD

**Issue by PatelVatsalB21** [openMF/android-client#1746]
**Summary:** 
As shown in video below after user enters values in fields of payment details, if user presses cancel layout hides and according to code it resets all values to null. But if fails to clear values from edittexts.

**Steps to reproduce:** 
1 Open Payment Details
2 Enter values in Add payment details fields 

**Expected behaviour:** 
Values entered in edittexts should be cleared.

**Device and Android version:** 
Any

**Recording:** 
![GIF-210204_224343 1](https://user-images.githubusercontent.com/70195106/106930107-2ec00680-673b-11eb-9efd-25e530dba3d5.gif)

**Comment by AhwiniMirajkar** [comment]
I want to work on this

**Comment by PatelVatsalB21** [comment]
@AhwiniMirajkar this issue has been solved by #1747
