### ISSUE TITLE
Progress bar is not stopping after loading the clients in any group

### ISSUE THREAD

**Issue by mananvirmani611** [openMF/android-client#1761]
**Summary:** 
Progress bar does not stops even after the information of clients is loaded.

**Expected behaviour:** 
Progress bar should stop, once the name of clients is displayed.

**Observed behaviour:** 
from navigation drawer -> groups -> click on any group -> top menu -> group clients ->
detail of clients is shown, but the progress bar doesn't stops.
**Device and Android version:** 
any
What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:** 
![Screenshot_20210209-141330_MifosXDroid](https://user-images.githubusercontent.com/72332463/107338116-312ab380-6ae1-11eb-9547-3884d5936847.jpg)

**Comment by danishjamal104** [comment]
@mananvirmani611 upload a smaller screenshot so that it is visible within the scroll limit. If an image is a large use the below syntax.
`<img width='333' alt='ss' src='[image src]'>`

**Comment by mananvirmani611** [comment]
![download](https://user-images.githubusercontent.com/72332463/107401355-cac98380-6b28-11eb-8153-0ac096be7ea0.png)
@danishjamal104

**Comment by NikunjGarg2000** [comment]
Hey @mananvirmani611 , this issue is already opened #1378 and solved #1412 by @robustTechie.

**Comment by PatelVatsalB21** [comment]
@mananvirmani611 if you have found an issue or finding solutions of other's issue make sure to confirm that no one has made that issue before. This might save your and reviewers time. There are many errors whose solutions are made but not merged so they exist in app. Hope you got it.

**Comment by mananvirmani611** [comment]
@NikunjGarg2000 ok, thanks for telling.

**Comment by mananvirmani611** [comment]
@PatelVatsalB21 yeah I got it.
can you please tell one more thing,
Is there any way to search that issue if it is already been listed, or I have to look at all the issues to check ??

**Comment by PatelVatsalB21** [comment]
@mananvirmani611 if you open GitHub in chrome there is a searchbar in 'Issues' section. Type keyword related to your issue and if there is issue created before it will be visible.

**Comment by mananvirmani611** [comment]
@PatelVatsalB21 OKk, thanks !

**Comment by danishjamal104** [comment]
> ![download](https://user-images.githubusercontent.com/72332463/107401355-cac98380-6b28-11eb-8153-0ac096be7ea0.png)
> @danishjamal104

edit the first comment of yours itself, instead of sending a new one. 
Also for finding issues use the filter option viz available in the search box just above the issue listing. Refer [this](https://docs.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) link if you aren't familiar with it.

**Comment by robustTechie** [comment]
@mananvirmani611 you can close this pull request
