### ISSUE TITLE
UI Enhancement required in item_checker_task.xml

### ISSUE THREAD

**Issue by NikunjGarg2000** [openMF/android-client#1762]
**Summary:** 

UI Enhancement required in item_checker_task.xml

**Steps to reproduce:** 

1. Open Navigation Drawer and choose Checker Inbox.
2. Choose checker inbox.

Observed Behaviour 
tv_checker_task_entity (ProvisionalEntities) overlapping cb_checker_task (checker box)

**Device and Android version:** 

Any

<img width="300" height="550" src="https://user-images.githubusercontent.com/67901968/107885156-ab629a00-6f1e-11eb-8d1d-9d27f463302c.jpeg">

**Comment by PatelVatsalB21** [comment]
@NikunjGarg2000 you need to describe exactly what changes are required or which elements require enhancement

**Comment by Edward1919** [comment]
I want to work on this issue please.

**Comment by NikunjGarg2000** [comment]
> @NikunjGarg2000 you need to describe exactly what changes are required or which elements require enhancement in 'Expected Behaviour' section. Though it is visible for this error

Ok @PatelVatsalB21, updated the comment.

**Comment by NikunjGarg2000** [comment]
> I want to work on this issue please.

@Edward1919 this is solved by #1763 , you could raise issue about some other changes in ui or anything and could solve. Best of luck.

**Comment by danishjamal104** [comment]
@NikunjGarg2000 , please be more clear about the issue description since it is difficult to get what the actual issue is.
