### ISSUE TITLE
Typo in Saving Account Summary

### ISSUE THREAD

**Issue by PatelVatsalB21** [openMF/android-client#1778]
**Summary:** 
Typo is present in type of account field written as **Fixed Depsotis** which should be **Fixed Deposits**.

**Steps to reproduce:** 
1 Open Client details
2 Open any FD account

**Expected behaviour:** 
It should be `Fixed Deposits`.

**Device and Android version:** 
Any

**Screenshots:** 
<img src="https://user-images.githubusercontent.com/70195106/108027228-d6004000-704f-11eb-8c8d-b463a9a77662.jpeg" width="333"/>

**Comment by sakshi-1604** [comment]
On it

**Comment by sakshi-1604** [comment]
Working on it

**Comment by sakshi-1604** [comment]
@PatelVatsalB21 can you please tell me where Client details is (path)?
I am not able to find it in the clone while running the app in android studio.
It would help a lot ..if you share video.

**Comment by NikunjGarg2000** [comment]
@sakshi-1604 open clients from navigation drawer then select any client and you will be in client details fragment.

**Comment by sakshi-1604** [comment]
@NikunjGarg2000  thanks!
But I tried searching there ..but there is no such page as displayed in screenshot....I guess the code in app(not updated) and  code fork is (updated) due to which I am not able to find that page

**Comment by NikunjGarg2000** [comment]
This is how you get there. Probably you have this.
https://user-images.githubusercontent.com/67901968/108155265-98112380-7104-11eb-81d3-d357fdb3eb6f.mp4

**Comment by NikunjGarg2000** [comment]
@sakshi-1604 probably your code is updated too this is how you get there.
https://user-images.githubusercontent.com/67901968/108155459-eaeadb00-7104-11eb-9547-22be6f8f35a1.mp4

**Comment by PatelVatsalB21** [comment]
@sakshi-1604 though you can try learn and find new  errors, but this one seems backend, I too tried a lot but didn't found solution. But still you can try, All the best 😊.

**Comment by sakshi-1604** [comment]
@NikunjGarg2000  yes ..my code was updated

**Comment by sakshi-1604** [comment]
@PatelVatsalB21 I have found some small issues ,I will work on them now.

**Comment by Aditya-gupta99** [comment]
Issue has been already resolved.
