### ISSUE TITLE
Toast message in ClientDetailsFragment 

### ISSUE THREAD

**Issue by Abhinavtdk** [openMF/android-client#1779]
**Summary:** 

When changing the client picture, if you click any of take new photo or upload new photo and go back without clicking or uploading respectively, the toast message which appears disappears too fast

**Steps to reproduce:** 

Go to client list from side navigation -> Click on any client -> Click on client profile picture -> Choose either of teake new photo or upload new photo -> Go back without performing any action

**Expected behaviour:** 

Show the toast message for a while in order to be seen clearly

**Observed behaviour:** 

The toast message disappears too fast

**Device and Android version:** 

RedMi Note 8 Pro
Android 9

**Screenshots:** 

https://user-images.githubusercontent.com/52701183/108369377-8a04f500-7221-11eb-8f3f-866e1b122549.mp4

**Comment by Abhinavtdk** [comment]
I'm working on this

**Comment by Anshul-9923** [comment]
@Abhinavtdk Can you please assign me this issue? I would like to work on this issue.
