### ISSUE TITLE
UI enhancements required in Create NewIndividualCollectionSheetFragment

### ISSUE THREAD

**Issue by PatelVatsalB21** [openMF/android-client#1788]
**Summary:** 
  Title and subtitle are not aligned with other elements, also textsize of subtitle is too small. Arrows of spinner are not in center_vertical and same applies to calendar icon

**Expected behaviour:** 
  Title should be in center, textsize of subtitle should be increased. Arrows of spinner and calendar icon should be in center_vertical alignment

**Device and Android version:** 
Lenovo Tab 7
Android 7

**Screenshots:** 
<img width='333' alt='ss' src='https://user-images.githubusercontent.com/70195106/109193621-94456700-77be-11eb-9baa-d79b74d39c7f.jpeg'>

**Comment by danishjamal104** [comment]
@PatelVatsalB21 , have you checked that this issue is not addressed previously? Can you please cross-verify it? Thanks

**Comment by PatelVatsalB21** [comment]
@danishjamal104 I searched for this type of error but I didn't found any.

**Comment by avinash14022002** [comment]
this issue is already resolved in present code
