### ISSUE TITLE
Feature: Adding scrolling behaviour to FAB

### ISSUE THREAD

**Issue by PatelVatsalB21** [openMF/android-client#1796]
**Summary:** 
When user scrolls through list of Clients, Groups and Centers it is visble that FAB remains still, which is not responsive with UI.  There is difference between Image btn and FAB, as FAB is available with some features to `show()` and `hide()`. It should be implemented for better User Experience.

**Steps to reproduce:** 
1 Open Clients
2 Scroll the List

**Expected behaviour:** 
Fab should show and hide with scroll changes.

**Device and Android version:** 
Any

**Recording:** 

https://user-images.githubusercontent.com/70195106/109395970-49aa2300-7955-11eb-8e7e-014e156b5bf0.mp4

**Comment by AyushUnleashed** [comment]
So When the user is scrolling the FAB should not be visible.
But when the user is not scrolling should FAB be visible?

Did I interpret it correctly?
