### ISSUE TITLE
Keyboard doesn't hides in Login Screen

### ISSUE THREAD

**Issue by aaddven** [openMF/android-client#1799]
**Summary:** 

In login screen keyboard doesn't hides when you click on screen or login button.

**Expected behaviour:** 

Whenever you click somewhere other than Username EditText and Password EditText , keyboard should hide.
I used red mark like on mifos image , background or login button.

**Device and Android version:** 

Redimi Note 7 Pro
Android 9 : Pie

**Screenshots:** 

![WhatsApp Image 2021-03-06 at 4 18 08 AM](https://user-images.githubusercontent.com/66247983/110183421-d280fd00-7e34-11eb-91ab-a40abec26e53.jpeg)

**Comment by GITrandhir** [comment]
I'm working on it also it will be very helpful if any mentor can add their valuable comments.

**Comment by danishjamal104** [comment]
> I'm working on it also it will be very helpful if any mentor can add their valuable comments.

Sure @GITrandhir , whats the progress.

**Comment by PatelVatsalB21** [comment]
@danishjamal104 I don't find it issue as there are only 2 default focusable elements on screen. What do you say?

**Comment by AnubhavPabby** [comment]
@danishjamal104 Hey can i work on this issue? If it's still open.

**Comment by Aditya-gupta99** [comment]
The issue has already been resolved
