### ISSUE TITLE
Swipe Refresh Layout is refreshing when pressed back button(twice) while creating groups

### ISSUE THREAD

**Issue by sreyans01** [openMF/android-client#1800]
**Summary:** 

When user tries to create a group and presses back button, the refresh layout is set to refreshing which should not be done when no new group is created.

**Steps to reproduce:** 

1) Go to Groups
2) Click on '+' button 
3) Press back button twice

**Expected behaviour:** 

https://user-images.githubusercontent.com/47531297/110196101-3f61ba80-7e68-11eb-9da5-dd0d821a2357.mp4

**Observed behaviour:** 

https://user-images.githubusercontent.com/47531297/110196125-6a4c0e80-7e68-11eb-8f11-af8da4309c62.mp4

**Device and Android version:** 
Any

**Comment by sreyans01** [comment]
I'm working on it also it will be very helpful if any mentor can add their valuable comments.

**Comment by elirehema** [comment]
> I'm working on it also it will be very helpful if any mentor can add their valuable comments.

@sreyans01 in my understanding it refresh to update group list, for it is multi user application someone on the other side may have updated or created a new group.

**Comment by sreyans01** [comment]
> 
> 
> > I'm working on it also it will be very helpful if any mentor can add their valuable comments.
> 
> @sreyans01 in my understanding it refresh to update group list, for it is multi user application someone on the other side may have updated or created a new group.

I understand your point completely, but the refreshing icon is running indefinitely. I tried and waited more than 5 minutes for multiple times, after which I finally raised the issue. I would suggest you also give it a try, if it works for your case, please share the recording, and I will close the issue.

**Comment by danishjamal104** [comment]
@sreyans01 I have already created the issue regarding this please check #1570. Thanks :)

**Comment by sreyans01** [comment]
Yes, I didn't notice it, I will close my issue #1800 then.

**Comment by sreyans01** [comment]
Please check, I have corrected the title for my pull request :
https://github.com/openMF/android-client/pull/1802
