### ISSUE TITLE
login button shadow not appearing correctly 

### ISSUE THREAD

**Issue by vinayak0505** [openMF/android-client#1803]
**Summary:** 
When the button in login page is pressed then shadow is cut down

**Steps to reproduce:** 
just open the app ( logout if logged in ) press and hold login button

**Expected behaviour:** 
the shadow should not be cut when the button is pressed

**Observed behaviour:** 
cutting of shadow

**Device and Android version:** 
it will appear on every device

**Screenshots:** 
![error_LI](https://user-images.githubusercontent.com/56196007/110442122-8c4fc600-80e0-11eb-9803-dbe72b6d80a6.jpg)
![solution_LI](https://user-images.githubusercontent.com/56196007/110442109-878b1200-80e0-11eb-947b-e9fa91cf1c49.jpg)

**Comment by houdesampath** [comment]
Can I work on this issue?

**Comment by danishjamal104** [comment]
> Can I work on this issue?

There are other priority issue you can explore that first.
