### ISSUE TITLE
wrong toast while starting the app

### ISSUE THREAD

**Issue by vinayak0505** [openMF/android-client#1805]
**Summary:** 
Every time I open the app it ask me to set pin code and pressing skin shows login successful which must be removed.

**Steps to reproduce:** 
1. open app.
2. log in
3. close app and remove it from recants
4. open app again
5. press skip

**Expected behavior:** 
I think there must be no toast there just leave it idle

**Observed behavior:** 
I am seeing the toast instead 
**Device and Android version:** 
every device

mentor if you wont some other solution instead of this just let me know

**Comment by sreyans01** [comment]
Could you please upload a screen recording of this issue

**Comment by vinayak0505** [comment]
![Screenshot_20210313-200450.png](https://user-images.githubusercontent.com/56196007/111033472-62c3d100-8437-11eb-8d15-fe8e2a9d9952.png)
App is also crashing as I have made another issue about threads

**Comment by vinayak0505** [comment]
screen recording

https://user-images.githubusercontent.com/56196007/111033874-3f018a80-8439-11eb-8c51-e80c4c0f71cf.mp4

**Comment by Smarshal21** [comment]
@Nayan @siebrand @vinayak0505 @sreyans01 can i work on this issues please?

**Comment by a-d14** [comment]
@Nayan @siebrand @vinayak0505 @sreyans01 is this issue still open? Can I work on it?

**Comment by AdityaKumdale** [comment]
I want to try working on it  too

**Comment by Aditya-gupta99** [comment]
The issue has already been resolved
