### ISSUE TITLE
App sends incorrect login API 

### ISSUE THREAD

**Issue by pmugabi** [openMF/android-client#1811]
App sends incorrect login API

App is unable to login and triggers an exception on Fineract mentioning invalid JSON as per issue FINERACT-726

**Steps to reproduce:** 
Attempt to login to version 1.5.0 of Fineract with the mobile app

**Expected behaviour:** 

To login

**Observed behaviour:** 

Returns a blank notification message

**Device and Android version:** 

Xiaomi Mi 9T running Android 10

**Comment by pmugabi** [comment]
First time contributor, have already fixed it on code I pulled down, if it's fine, I'd like to make a pull request and add it to the main code base.

**Comment by avinash14022002** [comment]
Already resolved
