### ISSUE TITLE
Plugin with id 'findbugs' not found

### ISSUE THREAD

**Issue by francisguchie** [openMF/android-client#1813]
**Summary:** 

Building the latest master branch"
------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------
Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_231 (Oracle Corporation 25.231-b11)
OS:           Windows 10 10.0 amd64

**Steps to reproduce:** 

How can we reproduce the issue?
clone the repo, open android studio and try to build the apk 

**Expected behaviour:** 
it should build successfully

**Observed behaviour:** 
instead you get error "Plugin with id 'findbugs' not found" 

file path with findbugs settings  is  **android-client\config\quality\quality.gradle**

**Comment by surajkamblesk** [comment]
@francisguchie did you resolve the issue??
im still not able to figure it out

**Comment by francisguchie** [comment]
@surajkamblesk I did not figure it out 
In fact i dropped this and moved to another challenge the mifos-mobile app which i managed to work with

**Comment by surajkamblesk** [comment]
Were you able to run the app locally??
Because without resolving this issue I'm not able to build the app.

**Comment by surajkamblesk** [comment]
Actually  'findbugs' plugin is deprecated and no more supported by gradle. Have to use 'spotbugs'

**Comment by francisguchie** [comment]
> Were you able to run the app locally??
> Because without resolving this issue I'm not able to build the app.

No not at all

**Comment by francisguchie** [comment]
> Actually 'findbugs' plugin is deprecated and no more supported by gradle. Have to use 'spotbugs'

Yes @surajkamblesk  
And when I tried to use spotbugs i got more errors but as of now the whole code has been changed to kotlin so i think this is better now

**Comment by danishjamal104** [comment]
@francisguchie and @surajkamblesk, take care that you don't update the Gradle plugin while setting up the project. On initial setup of project on android studio their is pop saying `Gradle plugin ready to be update` simply ignore that and use the older version in order the project to be build successfully and work as expected. Hope this helps

**Comment by surajkamblesk** [comment]
@danishjamal104  ok.  I understood where I went wrong. I actually updated the gradle to latest version when the pop up asked. 
Thank you for clarifying.

**Comment by francisguchie** [comment]
@danishjamal104 
Yes this helps a lot, one has to be very vigilant and yet this kind of information is not as documented as for fineract. we need to look into this. I wish you comments could be part of the readme

**Comment by surajkamblesk** [comment]
> @danishjamal104
> Yes this helps a lot, one has to be very vigilant and yet this kind of information is not as documented as for fineract. we need to look into this. I wish you comments could be part of the readme

@francisguchie exactly
