### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by iamsh4shank** [openMF/android-client#1826]
**Summary:** 

Update the readme with the current changes.

Here we need to update the details such as - 
* Features added in the application but not there in the `README.MD`
* More descriptive and helpful documentation

**Comment by luckyman20** [comment]
@iamsh4shank Please elaborate on your issue. As of now, I am closing this. I would be happy to re-open this if you comment on this issue.

**Comment by iamsh4shank** [comment]
Hey, @luckyman20 we are planning for the Android client release, so updating the Readme with all current changes would help the new contributors.

**Comment by luckyman20** [comment]
@iamsh4shank would you like to take this issue?

**Comment by iamsh4shank** [comment]
yes @luckyman20

**Comment by iamsh4shank** [comment]
I am reopening the issues :)

**Comment by dmdbilal** [comment]
is this issue still open ?

**Comment by AdityaKumdale** [comment]
yeah I want to know too

**Comment by luckyman20** [comment]
@AdityaKumdale You can work on this.

**Comment by AdityaKumdale** [comment]
ok

**Comment by mayank0rajput** [comment]
Is this issue still open ?

**Comment by AdityaKumdale** [comment]
@mayank0rajput its open but I think they will close it soon .

**Comment by luckyman20** [comment]
Closing this because not very accurate recommendations are made. If anyone wishes to work on similar issue, they may open a new issue now.
