### ISSUE TITLE
login issue, I have installed latest  APK version for Mifos xDroid when i have enter user ID pass and  hit on login i am not able to login, and also not showing any error massage  screen shot attached for verification   

### ISSUE THREAD

**Issue by DHIRAJJADAV** [openMF/android-client#1833]
![Mifos Xdroid 2021-08-16 at 6 04 51 AM](https://user-images.githubusercontent.com/88222055/129569163-085506b6-311c-49e1-8ae4-bfabfc0bfa24.jpeg)
[**Summary:**](url) 

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)

**Steps to reproduce:** 

How can we reproduce the issue?

**Expected behaviour:** 

What did you expect the app to do?

**Observed behaviour:** 

What did you see instead?  Describe your issue in detail here.

**Device and Android version:** 

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:** 

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by bharathcgowda** [comment]
login issue is happening on the fineract 1.5 release version

**Comment by DHIRAJJADAV** [comment]
So what is the resolution for this

**Comment by danishjamal104** [comment]
Hey @DHIRAJJADAV,
Can you confirm which version of fineract this ` https://52.220.107.255/fineract-provider/api/v1` is running?

**Comment by danishjamal104** [comment]
> So what is the resolution for this

You are trying to use the instance url of fineract `1.5.0`, but the app is based on older version. 
In older version of api the username and password was send as a query parameter, but as of version `1.5.0` we need to send username and password field as a body parameter. Hence this is causing an error.
For fixing this issue try using the instance url which is running 1.0.x version of fineract api.

**Comment by danishjamal104** [comment]
Also @DHIRAJJADAV , the username your using as shown in SS is wrong based on the instance url `https://52.220.107.255/fineract-provider/api/v1`. It should be `mifos` not `Mifos`.

**Comment by danishjamal104** [comment]
> login issue is happening on the fineract 1.5 release version

for interacting with the `1.5.0` version of api use [`sdk-client branch`](https://github.com/openMF/android-client/tree/sdk-client) since it uses fineract-android-sdk which is based on fineract 1.5.0, just make sure that the api is not completely migrated so many feature won't work, but all the basic feature would definelty work.

**Comment by bharathcgowda** [comment]
thanks for all the information and the lead @danishjamal104  could you help us with the APK  of sdk-client branch?
We shall test it and share it with the users of the community- it would be easier for them to download and install.

**Comment by iamsh4shank** [comment]
@DHIRAJJADAV if you want to test the client app then you can try using the demo.mifos.io endpoint, but the above-mentioned endpoint won't work as @danishjamal104 and @bharathcgowda suggested it is in 1.5.0, the SDK is still in the development phase and it will be integrated soon to support 1.5.0.

**Comment by josephgodwinkimani** [comment]
> @DHIRAJJADAV if you want to test the client app, you can try using the demo.mifos.io endpoint, but the above-mentioned endpoint won't work as @danishjamal104 and @bharathcgowda suggested it is in 1.5.0, the SDK is still in the development phase and it will be integrated soon to support 1.5.0.

demo.mifos.io endpoint doesn't work using `mifos` : `password`. I had to test the master branch and kotlin-conversion branch

**Comment by hghost50** [comment]
Had build the app according to the steps required, but when the app is launch, it keeps crashing. is their any solution?

**Comment by hghost50** [comment]
Am using the latest mifosx platform 21.07.02.

**Comment by hghost50** [comment]
Which of fineract version work best for all mifos mobile platforms: android client, mobile client, mifos pay

**Comment by Aditya-gupta99** [comment]
The issue has already been resolved
