### ISSUE TITLE
Clients list doesn't load more clients

### ISSUE THREAD

**Issue by theVernon124** [openMF/android-client#1834]
**Summary:** 

Clients list doesn't load more clients even after scrolling to the very end of the list

**Steps to reproduce:** 

1. Log in to app with total clients > 100 (or greater than the default limit used by `loadClients()`)
2. Go to the Clients screen
3. Scroll to the very bottom of the list

**Expected behaviour:** 

Next page of clients will be loaded below

**Observed behaviour:** 

Still the same list of clients was shown. Checking the logcat, the app did make the GET request containing the correct `offset` query param value, and the response was successful.

**Device and Android version:** 

Pixel XL, Android 9 (from AVD)
Samsung Galaxy s10+, Android 11 (real device, stock ROM)

**Comment by danishjamal104** [comment]
@theVernon124  Are you sure about this error, since it worked fine in my device.

**Comment by Aditya-gupta99** [comment]
This issue has been already resolved.
