### ISSUE TITLE
Convert data managers source code language to Kotlin

### ISSUE THREAD

**Issue by danishjamal104** [openMF/android-client#1854]
**Summary:** 

This issue focuses on converting the DataManager classes to Kotlin. Since their is ongoing migration of APIs to SDK, it would be easier to convert the language to Kotlin too.
Their will be multiple PRs referring this issue.

**Comment by Anshul-9923** [comment]
@danishjamal104 Can you please assign me this issue? I would like to work on this issue.

**Comment by danishjamal104** [comment]
> @danishjamal104 Can you please assign me this issue? I would like to work on this issue.

@Grandolf49 or @iamsh4shank can you please assign this.

**Comment by PratyushSingh07** [comment]
@danishjamal104 can i work on this issue?

**Comment by atharv028** [comment]
@danishjamal104 Please check my PR for this issue
