### ISSUE TITLE
Upgrade project gradle version and dependency bumps

### ISSUE THREAD

**Issue by Grandolf49** [openMF/android-client#1862]
## Summary

The project uses Gradle version `3.3.2` which is quite old. Moreover, there are several external libraries that are required to be upgraded. In this process, it is necessary that the app remains stable and none of the existing functionality is breaking.

## Action Item

Upgrade all the dependencies and Gradle to use their respective latest versions

**Comment by Anshul-9923** [comment]
@Grandolf49 Can you please assign me this issue? I would like to work on this issue.
