### ISSUE TITLE
Kotlin conversion

### ISSUE THREAD

**Issue by Grandolf49** [openMF/android-client#1863]
## Summary

Migrating the codebase to use Kotlin was started earlier. However, the conversion is only 30% completed. Remaining 70% of the Java files need to be converted to Kotlin

## Action Item

Convert all the files to Kotlin while making sure the app is stable

**Comment by avinash14022002** [comment]
Hi @Grandolf49 ,
Wanted to work on the issue can we create a detail checkbox listing for the task?

**Comment by houdesampath** [comment]
Can I work on this, if this is not assigned to anyone

**Comment by debz-g** [comment]
@Grandolf49 I would like to work on this issue if no one is working.

**Comment by Aditya-gupta99** [comment]
This issue has been already resolved.
