### ISSUE TITLE
activity_login .xml showing error while launching application

### ISSUE THREAD

**Issue by avinash14022002** [openMF/android-client#1865]
**Summary:** 
Runtime error while launching application in activity_login.xml

**Steps to reproduce:** 
[How can we reproduce the issue?](https://github.com/xamarin/AndroidX/issues/207)

**Expected behaviour:** 
The application should be build successfully.

**Observed behaviour:** 

What did you see instead?  Describe your issue in detail here.
The application is not getting build and throwing the error
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mifos.mifosxdroid/com.mifos.mifosxdroid.login.LoginActivity}: android.view.InflateException: Binary XML file line #31 in com.mifos.mifosxdroid:layout/activity_login: Binary XML file line #31 in com.mifos.mifosxdroid:layout/activity_login: Error inflating class com.google.android.material.textfield.TextInputLayout`

**Comment by UnleashedMors** [comment]
I have got the same error, i am using material 3 with material 1.5.0 and Theme.Material3.DayNight.NoActionBar. On my emulator the app works fine but on my pixel6p it will crash immidately on launch.

**Comment by avinash14022002** [comment]
> I have got the same error, i am using material 3 with material 1.5.0 and Theme.Material3.DayNight.NoActionBar. On my emulator the app works fine but on my pixel6p it will crash immidately on launch.

Hi @UnleashedMors,
You may reflect same [changes ](https://github.com/openMF/android-client/pull/1866/commits/2123ae127e70bfd0bc81b347fd8734a03a3d9ccd) on your local codebase and test it once.

**Comment by UnleashedMors** [comment]
> 

You mean I should undo all changes up to the status where it was still working?

**Comment by UnleashedMors** [comment]
> > I have got the same error, i am using material 3 with material 1.5.0 and Theme.Material3.DayNight.NoActionBar. On my emulator the app works fine but on my pixel6p it will crash immidately on launch.
> 
> Hi @UnleashedMors, You may reflect same [changes ](https://github.com/openMF/android-client/pull/1866/commits/2123ae127e70bfd0bc81b347fd8734a03a3d9ccd) on your local codebase and test it once.

You mean I should undo all changes up to the status where it was still working?

**Comment by UnleashedMors** [comment]
Now it works. 
I remade my styles.xml so all themes inherite from 

` 
    <style name="BaseTheme" parent="Theme.Material3.Light.NoActionBar">`

and i controlled every view to use only material 3 styles and wont use any view with material 2 and now i am able to install without any crash. 

` <com.google.android.material.textfield.TextInputLayout
                android:id="@+id/menu_input_layout"
                style="@style/Widget.Material3.TextInputLayout.OutlinedBox.ExposedDropdownMenu"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:endIconMode="dropdown_menu"
                android:hint="@string/spinner_organisation"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="@id/input_container_login">

                <AutoCompleteTextView
                    android:id="@+id/dropdown_menu"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:inputType="none" />

            </com.google.android.material.textfield.TextInputLayout>`

this is my exposeddropdown

**Comment by avinash14022002** [comment]
PR merged #1866
