### ISSUE TITLE
Build fails due to a dependency on DBFlow

### ISSUE THREAD

**Issue by avinash14022002** [openMF/android-client#1878]
**Summary:** 
Since one of the libraries in the project build is throwing the following error

> Execution failed for task ':mifosng-android:kaptGenerateStubsDebugKotlin'.
> Could not resolve all files for configuration ':mifosng-android:kapt'.
> Could not find dbflow-core.jar (com.github.Raizlabs.DBFlow:dbflow-core:3.1.1).

**Steps to reproduce:** 
Open the project in the latest version of Android Studio and build the application.
How can we reproduce the issue?

**Expected behaviour:** 
After cloning, the app should build successfully without any issues

**Screenshots:** 

![image](https://user-images.githubusercontent.com/66490629/177973926-127a4462-90b3-44e7-ad17-9d73ac91e832.png)

**Comment by qe360-vrucenzon** [comment]
Was able to fix it by looking up DBFlow in Jitpack: https://jitpack.io/#agrosner/DBFlow/3.1.1 (seems the maintainer changed?)

Update `build.gradle` (DBFlow dependencies) with:

`implementation 'com.github.agrosner.DBFlow:dbflow:3.1.1'`
`kapt "com.github.agrosner.DBFlow:dbflow-processor:3.1.1"`

Commented out all other Raizlabs dependencies and build succeeded.
