### ISSUE TITLE
Trying to login with demo user doesnt work

### ISSUE THREAD

**Issue by josephgodwinkimani** [openMF/android-client#1880]
**Summary:** 

Trying to login with demo user doesnt work:

[![screenshot-github-com-2022-07-30-21-08-59.png](https://i.postimg.cc/TYRMngBc/screenshot-github-com-2022-07-30-21-08-59.png)](https://postimg.cc/XXDzbGjZ)

**Steps to reproduce:** 

In app set instance URL: `demo.mifos.io` 
Port: keep this empty 
Tenant Identifier: keep this empty 

**Expected behaviour:** 

Successful Login or a toast message of an error/warning

**Observed behaviour:** 

Empty toast message

**Device and Android version:** 

Android 6.0

**Comment by parjanya-rajput** [comment]
Login issue still persists
