### ISSUE TITLE
The design of the dialog box is inappropriate

### ISSUE THREAD

**Issue by Aditya-gupta99** [openMF/android-client#1900]
**Summary:** 

The design of the dialog box is inappropriate.

**Steps to reproduce:** 

![demo](https://user-images.githubusercontent.com/94394661/221355923-e3aefa83-368c-494a-8f50-9c1479375b0d.jpg)

**Device and Android version:** 

Device : OnePlus Nord
Android 12

**Comment by Aditya-gupta99** [comment]
I shall be working on this

**Comment by AdityaKumdale** [comment]
Hey I am begineer in Android dev and opensource. I can see that you are improving the design and creating and solving your own issues. Just wanted to ask you that is this considered as contribution or someone else like some mentor must assign the issue to us.   As it's saying "1 workflow awaiting approval".
