### ISSUE TITLE
Implement splashScreen Api to show splash Screens

### ISSUE THREAD

**Issue by zaidazaize** [openMF/android-client#1918]
**Summary:** 
Implement new SplashScreen API to show splash screens on app launch to show splash screens on app launch.
Show single splash screens on android 12 and higher on app launch.

**Comment by parjanya-rajput** [comment]
Hey, is this issue still open, if yes can I work on it?

**Comment by zaidazaize** [comment]
Pull request is already linked @parjanya-rajput .

**Comment by parjanya-rajput** [comment]
> Author

ok thank you
