### ISSUE TITLE
Upload an Image from gallery to update client's profile picture.

### ISSUE THREAD

**Issue by yvssssssssss** [openMF/android-client#197]
It would be good to have an upload function on the image instead of using camera in the client's page

![2016-03-09](https://cloud.githubusercontent.com/assets/17710616/13649741/1ecaa94e-e665-11e5-9117-cd866f782740.png)

**Comment by pandilladivya** [comment]
Yeah!
That is actually a great Idea!

I will work on it :)
ThankYou.

**Comment by pandilladivya** [comment]
Yeah!
That is actually a great Idea!

I will work on it :)
ThankYou.

**Comment by therajanmaurya** [comment]
I have opened a [PR](200) for this feature.

**Comment by pandilladivya** [comment]
The link to the PR is  https://github.com/openMF/android-client/pull/203

Please review my code.

Thank you!

**Comment by yvssssssssss** [comment]
@therajanmaurya  please follow the coding style given by mifos and don't do unnecessary changes by just indentation...and also ur code has bugs in it so please verify as u applied for another ticket regard with the same bug

@pandilladivya Good job with the ticket! :)

**Comment by therajanmaurya** [comment]
@yvssssssssss Please Tell me bugs and i will correct the indentation.
