### ISSUE TITLE
`TrustManager` that accepts all certificates

### ISSUE THREAD

**Issue by Onyx2406** [openMF/android-client#1978]
**Summary:** 

The app trusts all digital certificates, which isn't safe. It should only trust certificates from known, reliable sources.

**Steps to reproduce:** 

 1.   Find the part of the app code in MifosOkHttpClient.
 2.   It uses a TrustManager that accepts all certificates.
 3.   This means the app is willing to make secure connections with any server, even if it can't prove it's trustworthy.

To deploy CodeQL into your forked repository, use this codeQL.yml script : [codeQL.yml](https://pastebin.com/54xxr7s1)

**Expected behaviour:** 

The app should only trust certificates from servers it knows are safe. It should have a list of trusted certificates, and it should reject connections from servers not on that list.

**Observed behaviour:** 

Right now, the app doesn't check certificates properly. It will make secure connections with any server, even if it can't prove it's safe. This could let a attacker pretend to be a safe server, tricking the app into sharing private information.

**Device and Android version:** 

This isn't about a specific Android phone or Android version.
It's about code in master branch.

**Screenshots:** 

![image](https://github.com/openMF/android-client/assets/32770175/9427315e-d84c-48b2-a2cc-0501ce8e0f64)

**References:**

Android Developers: [Security with HTTPS and SSL](https://developer.android.com/training/articles/security-ssl).

**Comment by Malaydewangan09** [comment]
Hey! @Onyx2406 I want to work on this.

**Comment by Onyx2406** [comment]
> Hey! @Onyx2406 I want to work on this.

Thanks for showing interest. You can work on it and create a PR for the same, if you have any approach to solve this, we can discuss that as well. While I will ask the the appropriate people to assign you this issue.

**Comment by Malaydewangan09** [comment]
There can be multiple approaches for this 

- We can just remove the custom Trust manager in the code and use default validation.
- We can include the certificates in a .crt format 
- We can use certificate (much secure).

Please do correct me if these are not the correct ways.
