### ISSUE TITLE
Profile pictures for client is not shown in the Dashboard.

### ISSUE THREAD

**Issue by Swethaldsm** [openMF/android-client#199]
When we open the list of clients...their profile pics are not shown

![2016-03-10](https://cloud.githubusercontent.com/assets/17761684/13666701/86c55fcc-e678-11e5-9f48-4239978b6687.png)

**Comment by yvsssantosh** [comment]
I'm working on this issue!

**Comment by therajanmaurya** [comment]
@Swethaldsm Please review #205 and close this issue.
