### ISSUE TITLE
Stuck in Oboarding

### ISSUE THREAD

**Issue by pranavkonidena** [openMF/android-client#2052]
**Summary:** 

While onboarding into the app, one of the animations is stuck and doesn't allow me to do anything else

**Steps to reproduce:** 

Start the app, go through the onboarding flow

**Expected behaviour:** 

The animations should have stopped by touch or some indicator

**Observed behaviour:** 

I am stuck inside the animation screen. Even restarting the app doesn't work

**Device and Android version:** 

Pixel XL API 34 (Emulator)

**Screenshots:** 
<img width="1512" alt="Screenshot 2023-12-16 at 10 18 03 AM" src="https://github.com/openMF/android-client/assets/122373207/6b53fc2e-3542-40f0-9659-60c9966ee0b4">

**Comment by cliffgor** [comment]
Hello @pranavkonidena I think your issue is a screen size problem from what I see in your screenshot, I have  been able to go through the onboarding successfully. There is usually a button to go next which I am not seeing in your screenshot
