### ISSUE TITLE
App UI is very basic and dull needs redesigning

### ISSUE THREAD

**Issue by ThakurSaAbhay** [openMF/android-client#2054]
**Summary:** 

The UI of the application is very basic and dull it need some redesign to make it attractive and aesthetic for the betterment of UX.

**Steps to reproduce:** 

How can we reproduce the issue?
Just install the application.

**Expected behaviour:** 

What did you expect the app to do?
I expect it to be more attractive so that the user wants to use it.

**Comment by ThakurSaAbhay** [comment]
I want to work on this issue and make the app UI better.

**Comment by Aditya-gupta99** [comment]
Hi @ThakurSaAbhay , Once you clone the project and run it, you'll be able to see the updated UI.

**Comment by nuke200kr** [comment]
I want to work on this issue . Please assign it to me.

**Comment by nuke100pr** [comment]
I want to work on this issue . Please assign it to me.

**Comment by Saksham6395** [comment]
Hi @ThakurSaAbhay ,I want to work on this issue . Please assign it to me.
