### ISSUE TITLE
refactor: migrate login screen to jetpack compose 

### ISSUE THREAD

**Issue by Aditya-gupta99** [openMF/android-client#2059]
**Summary:** 

Transitioning from XML to Jetpack Compose offers advantages such as adopting a declarative UI approach, ensuring type-safe UI development, and minimizing boilerplate code.

**Comment by Aditya-gupta99** [comment]
I will be working on this issue.

**Comment by YatinGarg07** [comment]
@Aditya-gupta99 how to get the user & password for this debug build

**Comment by ashutosh-kumar-kushwaha** [comment]
> @Aditya-gupta99 how to get the user & password for this debug build

Username - mifos
Password - password

(It might not work for the first time but keep trying. It will work.)
