### ISSUE TITLE
Remove ImageLoadingAsyncTask for Image Loading in main Thread to Picasso with OkHttp3

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/android-client#206]
Remove ImageLoadingAsyncTask for Image Loading in `ClientDetailsFragment` that is working in main thread, That makes Application glitchy.

![12834788_999474940173480_1452022370_n](https://cloud.githubusercontent.com/assets/5724482/13693894/f9521c30-e775-11e5-8928-9ed119864f07.jpg)

Load the Image in new thread using [Picasso](https://github.com/JakeWharton/picasso2-okhttp3-downloader) with [OkHttp](http://square.github.io/okhttp/) for Basic OAuth.

**Comment by therajanmaurya** [comment]
This issue is fixed here #207

**Comment by top-gun007** [comment]
Is this issue fixed?...if not I can

**Comment by therajanmaurya** [comment]
@top-gun007 Welcome to the community. 

Yes you can work in this issue. 
But little changes is, Here we are not using Picasso, We are using Glide. 
So You can open new issue to fix this.

**Comment by therajanmaurya** [comment]
@top-gun007 Here you go #370.
