### ISSUE TITLE
refactor: migrate client list screen to jetpack compose

### ISSUE THREAD

**Issue by Aditya-gupta99** [openMF/android-client#2069]
**Summary:** 

Transitioning from XML to Jetpack Compose offers advantages such as adopting a declarative UI approach, ensuring type-safe UI development, and minimizing boilerplate code.

**Select Type:**

- [ ] UI Improvements
- [ ] UI Add On
- [ ] Improve Existing Code
- [x] New Feature
- [ ] Other

**Comment by Aditya-gupta99** [comment]
I will work on this issue

**Comment by PraneGIT** [comment]
I want to contribute in Mifos projects but i am having some problems. I need some help how can i connect in the community.

**Comment by Aditya-gupta99** [comment]
@PraneGIT In the readme file, you'll find the link to the Mifos Slack channel, where you can connect with community
