### ISSUE TITLE
Refactor - Groups Fragment to Compose UI

### ISSUE THREAD

**Issue by niyajali** [openMF/android-client#2074]
**Summary:** 

Converting the Groups Fragment to compose UI to achieve a type-safe and declarative UI approach, while also minimizing boilerplate code. This will enhance the efficiency and maintainability of the codebase.

**Possible Approach:**

Mention the steps to implement this feature(If you can think of one)

- Migrate Group List Fragment to Compose UI

**Select Type:**

- [x] UI Improvements
- [ ] UI Add On
- [ ] Improve Existing Code
- [x] New Feature
- [ ] Other

**Comment by niyajali** [comment]
I would like to work on this issue.

**Comment by therajanmaurya** [comment]
Go ahead
