### ISSUE TITLE
Overlapping of Fragments

### ISSUE THREAD

**Issue by Vatsal-Bajpai** [openMF/android-client#208]
•The fragments that are being replaced and while backstack poping when pressed back button to move back to previous fragment, it gets overlapped.
•Also the survey fragment is being replaced in the DashboardFragmentActivity, but when the ClientChooseFragment calls the replace for SurveyListFragment it gets replaced behind it on the second call(when client selected again from the list) and the fragment is hidden behind the ClientChooseFragment.
Probable solution : 
•User TabLayout and ViewPager to navigate fragments instead of replacing them.

@ishan1604 if this issue is unsolved then i can work on it. Please review my issue.
Here are some screenshots : 

![ss1](https://cloud.githubusercontent.com/assets/6625740/13701347/4df4cc88-e7ad-11e5-8012-b9044ce4da17.png)

![ss2](https://cloud.githubusercontent.com/assets/6625740/13701355/5663784c-e7ad-11e5-9b52-a2d0de62c91c.png)

**Comment by mayank-kgp** [comment]
Hi Vatsal,
               Overlapping problem is already resolved.
You can look into jira if you want to confirm about any issue.

**Comment by Vatsal-Bajpai** [comment]
Thank you @mayank-kgp. I'll close it :)
