### ISSUE TITLE
View conflicts in Create Group and Create Center.

### ISSUE THREAD

**Issue by Swethaldsm** [openMF/android-client#214]
The below images are screenshots from Mifos Webpage

![create_group_with_actdate](https://cloud.githubusercontent.com/assets/17761684/13721199/8587972e-e844-11e5-88f9-a9b126f79c50.PNG)

![create_group_without_actdate](https://cloud.githubusercontent.com/assets/17761684/13721197/7f63ed0c-e844-11e5-9a4a-afdc8fc38990.PNG)

![create_center_with_actdate](https://cloud.githubusercontent.com/assets/17761684/13721198/834397ec-e844-11e5-9d1c-b02b9dbb513f.PNG)

![create_center_without_actdate](https://cloud.githubusercontent.com/assets/17761684/13721202/88ef6a22-e844-11e5-829a-9ed15e42375e.PNG)

But in the android app,we don't have activation date.
Instead the submission date is being closed in both the cases when Active is checked.

The below images are screenshots from Android App.

![2016-03-11](https://cloud.githubusercontent.com/assets/17761684/13721259/4b1d250c-e846-11e5-8324-960a9f582052.png)

![2016-03-11 1](https://cloud.githubusercontent.com/assets/17761684/13721260/4d89c5d4-e846-11e5-8431-77083fed0167.png)

**Comment by yvsssantosh** [comment]
Hi,

I've gone through the issue reported here.
I'm working on it :)

**Comment by yvsssantosh** [comment]
Hi,

I've created a PR #215 

Kindly review my code

Thank You

**Comment by Swethaldsm** [comment]
@yvsssantosh 
I have gone through this code...

Everything works fine :)
