### ISSUE TITLE
Using timber library

### ISSUE THREAD

**Issue by vjs3** [openMF/android-client#217]
Log class provided by android is used in mifos client to keep track of logs. As log requires TAG , it is tedious to add redundant tag in every class we write so I suggest we should use Timber for easier logging and we don't have to write any boilerplate TAG strings.

Timber has other features as well and as we are using crashalytics it works well with it too.
@ishan1604 please let me know about your thoughts on it. I am already familiar with timber so I can work on changing existing logs.

**Comment by ishan1604** [comment]
Not needed at the moment! I'll be getting rid of the Logging calls from the code very soon.

**Comment by vjs3** [comment]
sure :) Let me know if i can help in that!

**Comment by ishan1604** [comment]
A Pull request is welcome. If you can get rid of the Log.methodName calls in the code.

**Comment by vjs3** [comment]
@ishan1604 I can do that but then how will be do logging any more? Does this not decrease readability in terms of testing code? Forgive me if I am asking a basic question.
