### ISSUE TITLE
NumberFormatException inSavingsAccountTransactionFragment

### ISSUE THREAD

**Issue by RowlandOti** [openMF/android-client#241]
![device-2016-03-28-153615](https://cloud.githubusercontent.com/assets/8356008/14078082/470eef92-f4fb-11e5-9065-4c1315d1a662.png)
![numberformat](https://cloud.githubusercontent.com/assets/8356008/14078083/473b326e-f4fb-11e5-8f44-46047a6ec781.png)

When you click "Make WithDrawal" or "Make Deposit" the app will crash with the above error. Is the Savings Account No. (savingsAccountNumber) supposed to be an integer or String? In Line 127 of SavingsAccountTransactionFragment.java this is causing an error.

``` java
App.apiManager.getSavingsAccountTemplate(savingsAccountType.getEndpoint(), 
Integer.parseInt(savingsAccountNumber), transactionType, new Callback<SavingsAccountTransactionTemplate>()
```

**Comment by RowlandOti** [comment]
@ishan1604 , could help give an answer to question, so I can proceed to fix this?

**Comment by nellyk** [comment]
@RowlandOti  sorry i took time to respond , yes you can work on this issue , thank you for finding it out, i have added it on Jira and assigned it to you https://mifosforge.jira.com/browse/MIFOSAC-140

**Comment by nellyk** [comment]
@RowlandOti please note that this only occurs when the account has no savings amount, so their is no money to withdraw, you can investigate why this happens to this savings accounts only?

**Comment by RowlandOti** [comment]
@nellyk ,thank you.

**Comment by mayank-kgp** [comment]
@RowlandOti  @nellyk The app is not crashing in my device.
Please give an update on this issue. Is it resolved or @RowlandOti  is still working on this?

**Comment by therajanmaurya** [comment]
@mayank-kgp It's already resolved by me during code refactoring. I have just looked into the code and found. Sorry, my bad. Closing now.

**Comment by mayank-kgp** [comment]
Thanks @therajanmaurya
