### ISSUE TITLE
No progress indication when fetching groups list

### ISSUE THREAD

**Issue by xiprox** [openMF/android-client#254]
As the title suggests, there is no indication that anything is happening in Groups List.

I found out about this while working on [MIFOSAC-139](https://mifosforge.jira.com/browse/MIFOSAC-139). I was just going to use the same method I'm using for everything else (centered ProgressBar - see below) but I saw that SwipeRefresLayout is already there. Now, we could just fix SwipeRefreshLayout and use that as an indicator. However, that goes against consistency. I'd much rather just ditch SwipeRefresh's indicator for the first load and use the ProgressBar method. What are the opinions on this?

For comparison:
![](https://i.imgur.com/VDSzyAB.png) ![](https://i.imgur.com/duHqw14.png)
*Left: ProgressBar (everywhere else), Right: SwipeRefreshLayout*

**Comment by nellyk** [comment]
Hi @xiprox ,

This should not appear have you pulled the latest code, because this what you should see , check this pull request out https://github.com/openMF/android-client/pull/245

**Comment by xiprox** [comment]
Oh, I didn't realize it was being used in Clients List too. Actually, they weren't really being *used*. The layout code might have been there but the ProgressDialogs were what were being shown.

in either case, I wouldn't mind using SwipeRefresh in Groups List if it'll also be used in Clients List. I'll be fixing SwipeRefresh indicators in a future PR then.

As for [MIFOSAC-139](https://mifosforge.jira.com/browse/MIFOSAC-139), I'll be omitting Clients List and Groups List.
