### ISSUE TITLE
Add API Response Model

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/android-client#285]
On some places, the API response is the Retrofit Response, Deserialize POJO is not coming by default, Need to add POJO of CallBack Retrofit Request.

Here is the Files.
1. **Done** GroupLoanAccountFragment : Same Type Multiple API request. No POJO of API response.
2. **Done** LoanAccountFragment : Same Type Multiple API request. No POJO of API response.
3. ChargeDialogFragment : No POJO of API response.
4. LoanAccountDisbursement : No POJO of API response.

**Comment by mayank-kgp** [comment]
@therajanmaurya I will work on this issue in detail once my PR is reviewed and merged successfully.
I have tried to correct the implementation of GroupLoanAccountFragment.

**Comment by mayank-kgp** [comment]
@therajanmaurya  
GroupLoanAccountFragment - corrected in pr #381 
LoanAccountFragment - POJO of "Loans" is required but it has no annotation - @SerializedName
ChargeDialogFragment - one POJO is made but it has dbflow implemetation as @primarykey, @column annotation . Annotation should be replace by @SerializedName . Another POJO required. And Subscription should be replaced by CompositeSubscription.
LoanAccountDisbursement - POJO required and Subscription should be replaced by CompositeSubscription.

Please assign it to me.

**Comment by therajanmaurya** [comment]
@mayank-kgp This is not a single PR, you have to break this Issue in multiple. 
Please open issue for LoanAccountFragment. I will assign to you.

**Comment by mayank-kgp** [comment]
@therajanmaurya  Sure.

**Comment by mayank-kgp** [comment]
@therajanmaurya May I open the issue for ChargeDialogFragment?

**Comment by therajanmaurya** [comment]
ChargeDialogFragment issue already opened #364.
If you wanna work I will assign to you.

**Comment by mayank-kgp** [comment]
@therajanmaurya  Please assign it to me.

**Comment by therajanmaurya** [comment]
fixed #443
