### ISSUE TITLE
LoadMore not Working at one case.

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/android-client#300]
LoadMore not woking when we scroll down and load more till the last element and back to top and when we again scrolling to down then LoadMore not working

**Comment by mayank-kgp** [comment]
@therajanmaurya Can you please elaborate this issue as I am not able to visualize the issue?

**Comment by TypicalGitHubUser** [comment]
@therajanmaurya 
I` ve resolved this issue. Can you review my PR?
