### ISSUE TITLE
Feature addition in Group Creation

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/android-client#308]
**Show Image and Text after successful or Failed during creation of Group**
Description : When the user creates the New Group then according to the response from response APIs from Database or retrofit response then setVisibilty of Group form "InVisible" and show an ImageView and TextView at the center of Group Creation Status.

**A button to Continue or Finish the GroupCreatio**
A button below the Image and TextView for continue to Create more Group or Finish.
If user does not want to create more group replace Fragment of Search Fragment.

**Comment by sosnickm** [comment]
Can you explain more what you mean here? I can try to work on this if no one has.

**Comment by therajanmaurya** [comment]
Yes, you are welcome.
right now, when the user is creating the group, you have to enter the group name and other details and submit.
There is two way to create the group.
1. Submitting Group to the server using retrofit.
2. Save the group to the database and sync later to the server, if the user does not have good           
    internet connection. you have to switch in offline from navigation drawer.

In this issue, we have to add a check and consider the server response or database response.
Let's take first case,
1. Submit Group to the server directly using retrofit.
    As we will submit the group to the server then we will get some response from the server.
![screenshot](https://cloud.githubusercontent.com/assets/5724482/19801712/02b38134-9d1e-11e6-8e54-398531f572de.jpg)
    * Group Submitted successfully 
    * Group Submission failed.

**Addition** As we got the response, if need to invisible the group creation form and show A Google card with a message(successful or failed) and two buttons. 
Message : **Group created successfully or failed according to response and do you want to create another group,**
First Button : **Create new Group**
second button : **No Thanks**
As user clicked on **Create new Group** button, we have to clear the Edit Text or etc and show the fresh Group creation form.

and same as for saving group in Database.

**Comment by top-gun007** [comment]
is someone working on it @therajanmaurya

**Comment by therajanmaurya** [comment]
fixed in #520
