### ISSUE TITLE
Delete an identifier

### ISSUE THREAD

**Issue by chashmeetsingh** [openMF/android-client#316]
After Deleting an identifier it still shows the same identifier, instead it should be removed.
Since its there clicking on remove again gives a 404

Steps to Reproduce:
- Login
- Clients
- Select a client (with an identifier)
- Select Identifiers from the dropdown menu
- Click Remove

**Comment by therajanmaurya** [comment]
Please Add also how others can generate the same bug. 
Example Open App and click somewhere like.

**Comment by therajanmaurya** [comment]
Thats good. You can work on this.

**Comment by ishan1604** [comment]
@chashmeetsingh Thanks for reporting the bug! 

We'd love to welcome you to the Mifos Developer Community! You can start working on this issue and if you need any help feel free to write back!

**Comment by chashmeetsingh** [comment]
@therajanmaurya how to test this? As I can't create a client

**Comment by chashmeetsingh** [comment]
```
Subscription subscription = call.subscribeOn(Schedulers.io())
                        .observeOn(AndroidSchedulers.mainThread())
                        .subscribe(new Subscriber<GenericResponse>() {
                            @Override
                            public void onCompleted() {
                                ClientIdentifiersFragment.newInstance(clientId).loadIdentifiers();
                            }

                            @Override
                            public void onError(Throwable e) {
                                Log.d(getClass().getSimpleName(), e.getMessage());
                            }

                            @Override
                            public void onNext(GenericResponse genericResponse) {
                                Log.d(LOG_TAG, genericResponse.toString());
                            }
                        });
```

I changed onComplete to this but since for the new instance go `ClientIdentifiersFragment` no attached view it throws an exception. So should I reference the instance of `ClientIdentifiersPresenter` in `ClientIdentifiersFragment` to do so? @therajanmaurya

**Comment by therajanmaurya** [comment]
you do not need to call this method in onComplete(). make a method in MvpView class and implement in Fragment and call in onNext() and reload the identifiers list by using mClientIdentifiersPresenter.loadIdentifiers(clientId) in implemented method in fragment class.

**Comment by chashmeetsingh** [comment]
@therajanmaurya but we don't have an instance of the fragment in the adapter right?

**Comment by therajanmaurya** [comment]
No this is not good.

**Comment by therajanmaurya** [comment]
Here I have written some architecture guidelines 
First look here : https://github.com/openMF/android-client/wiki/Architecture-Guidelines

Here what you have to do for completing this PR 

Make Interface in Adapter 

 ```java
java public interface deleteIdentifierListener {
        void onClickRemoveIdentifier(int identifierId);
 }
```

and make Object of the interface in adapter like this.

```private deleteIdentifierListener mDeleteIdentifierListener;```

and call onClickRemoveIdentifier onClick remove button event like this.

```java 
reusableIdentifierViewHolder.bt_delete_identifier.setOnClickListener(new View
                .OnClickListener() {
            @Override
            public void onClick(View view) {
            mDeleteIdentifierListener.onClickRemoveIdentifier(identifier.getId());
        });
```

and Implement this interface in ```ClientIdentifiersFragment```
```java
@Override
    public void onClickRemoveIdentifier(int identifierId) {
        mClientIdentifiersPresenter.deleteIdentifier(clientId, identifierId);
    }
```

and make a method in  ```ClientIdentifiersPresenter```

```java

public void deleteIdentifier(int clientId, int identifierId) {
        checkViewAttached();
        getMvpView().showProgressbar(true);
        if (mSubscription != null) mSubscription.unsubscribe();
        mSubscription = mDataManager.deleteIdentifier(clientId, identifierId)
                .observeOn(AndroidSchedulers.mainThread())
                .subscribeOn(Schedulers.io())
                .subscribe(new Subscriber<GenericResponse>() {
                    @Override
                    public void onCompleted() {

                    }

                    @Override
                    public void onError(Throwable e) {
                        getMvpView().showFetchingError("Failed to delete Identifier");
                    }

                    @Override
                    public void onNext(GenericResponse genericResponse) {
                        getMvpView().showIdentifierDeletedSuccessfully();
                        getMvpView().showProgressbar(false);
                    }
                });
    }
```

I think this is sufficient.

Ask if you got any problem

**Comment by therajanmaurya** [comment]
done in #324, @ishan1604 Please close.
