### ISSUE TITLE
Fix Group DataTable

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/android-client#338]
**Summary:** 

Right now GroupDetailsPresenter Loading the Group DataTable successfully
But DataTable is not accessible from Group Menu actionBar.
Need to add the Group DataTable accessibility in Menu ActionBar

**Steps to reproduce:** 

Click on Navigation Drawer home button and select `Groups`  from the list.
now you are able to look group list and click on any group from the list and then click on ActionBar button. ohhh there no option to look Group DataTable.

**Expected behavior:** 

In GroupDetailFragment ActionBar. there should be a button of  `More Group Info`.
that will call DtaTable Fragment and show Groups DataTable.

**Observed behavior:** 

No ActionBar button available for looking Group DataTable in GroupDetailFragment ActionBar. 

**Device and Android version:** 

Moto g3 turbo.
version (Android 6.0 Marshmallow) 
it is the stock

**Screenshots:** 

![group](https://cloud.githubusercontent.com/assets/5724482/18418490/183c1a44-7865-11e6-83ad-412ce957f62e.png)

**Comment by top-gun007** [comment]
hi @therajanmaurya can I do it?

**Comment by therajanmaurya** [comment]
fixed in #536
