### ISSUE TITLE
Save User Model in Shared Preference 

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/android-client#339]
**Summary:** 

When the user is logging(Login.Activity) into the app then server response is user model. this need to be saved into the shared preference using the PrefManager and make a method to  deserilize  the user model json string into the PrefManager and show the user credentials in Navigation Drawer header(Dashdoard.Activity).

and remove the REST API call from the Dashboard that is fetching the client details.

**Steps to reproduce:** 

Open the app and click on Navigation drawer home button and look into the navigation drawer header information.

**Expected behavior:** 

User logged in information in Navigation drawer header instead of client information.

**Observed behavior:** 

Client Information instead of the User logged in Information in Navigation drawer header.

**Device and Android version:** 

Moto g turbo 3 Android 6.0 Marshmallow.  it is the stock ROM.

**Comment by SKrPl** [comment]
How to handle the profile picture of User (that logged in) as there is no attribute for profile picture in User class ?

**Comment by therajanmaurya** [comment]
Yes, I know that profile picture is not present. I had looked. So, for now, leave the profile picture staff and save User Model in Pref.

**Comment by ishan1604** [comment]
Why do you think do we need to store it in SharedPreferences ?

**Comment by therajanmaurya** [comment]
Because it is faster.

**Comment by therajanmaurya** [comment]
Done #343
