### ISSUE TITLE
Can't Save New Client Because of Validation on Middle Name Field

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#344]
**Summary:** 

Can't successfully create a client with the middle name blank because it states "Middle name should contain only ALPHABETS

Copied over from https://mifosforge.jira.com/projects/MIFOSAC/issues/MIFOSAC-157

**Steps to reproduce:** 

Create client, don't fill out middle name, press submit. 

**Expected behavior:** 
Successfully save client

**Observed behavior:** 

Just an error message but one is also not able to enter a middle name and re-submit. You have to start by creating a client again from scratch
**Device and Android version:** 
HTC One M8, Android 6 stock
**Screenshots:**

**Comment by edcable** [comment]
![screenshot_20160923-165557](https://cloud.githubusercontent.com/assets/823454/18804564/7db87bd8-81b1-11e6-9edd-8a639d4debfe.png)

**Comment by therajanmaurya** [comment]
Fix in #352. Now no need to create fresh client if any validation fails and middle name can be empty fix.
