### ISSUE TITLE
Can't Save New Group Because of ALPHABETS validation

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#345]
**Summary:** 

Can't save a group because of the validation which says Group Name should contain only ALPHABETS. 

**Steps to reproduce:** 

Enter a group name with spaces, press submit. 
**Expected behavior:** 

Successfully save. 

**Observed behavior:** 

Error message

**Device and Android version:** 
HTC One M8 with Android 6.0
**Screenshots:**

**Comment by edcable** [comment]
![screenshot_20160923-165905](https://cloud.githubusercontent.com/assets/823454/18804672/01d5a82c-81b3-11e6-86f7-e3487191aa38.png)

**Comment by therajanmaurya** [comment]
Fix in #351
