### ISSUE TITLE
Can't Save New Client - Try Again Error Message

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#347]
**Summary:** 

When attempting to create a new client, even with all fields completed, can't successfully save. 
**Steps to reproduce:** 

Create a new client and click submit.

**Expected behavior:** 
Successfully save new client
**Observed behavior:** 
Error message which says Try Again. Upon re-submitting nothing occurs.
**Device and Android version:** 
HTC One M8 with Android 6.0 
**Screenshots:** 
![screenshot_20160923-165736](https://cloud.githubusercontent.com/assets/823454/18804695/7b27516c-81b3-11e6-843f-c358df8ba8bf.png)

**Comment by therajanmaurya** [comment]
This was the server error. I had talked to Shreyaank and It is resolved now.

**Comment by javmcre** [comment]
Hi, What was wrong with the server??. I'm having the same problem.

**Comment by therajanmaurya** [comment]
@javmcre 
somebody enable the "account number preferences"  for client. So that problem was coming during creation of client.
