### ISSUE TITLE
Can't add new savings account

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#349]
**Summary:** 
With all the available fields added, can't successfully save the savings account. It might be related to MIFOSAC-133 (https://mifosforge.jira.com/projects/MIFOSAC/issues/MIFOSAC-133) where not all the savings fields are available. 
**Steps to reproduce:** 
Fill in available fields and click submit

**Expected behavior:** 
Expect to save

**Observed behavior:** 
Error message of failed to add savings account
**Device and Android version:** 
Demo3 Server on HTC One M8 with Android 6.0
**Screenshots:** 
![screenshot_20160923-174406](https://cloud.githubusercontent.com/assets/823454/18804842/9c9a836c-81b5-11e6-88fb-9b6e0665f13c.png)

**Comment by mayank-kgp** [comment]
@edcable 
It is working on my device(Android version 5.1.1) . 
Is it due to specific android version?

**Comment by therajanmaurya** [comment]
fixed in  #515
