### ISSUE TITLE
Can't retrieve/view documents stored at client record

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#357]
**Summary:** 

I tried to both click and download PDFs or image documents that have been uploaded as documents to a client. 
**Steps to reproduce:** 

Navigate to R Smith, click more menu, click Documents, click various documents

**Expected behavior:** 

View document or be prompted to download document

**Observed behavior:** 

For the PDF, My PDF viewer opens but it says can't be displayed. For the image, the app just restarts with the "MifosX Droid has stopped" error 

**Device and Android version:** 

Demo Server on HTC One M8 with Android 6.0
**Screenshots:**

**Comment by therajanmaurya** [comment]
I am working on this Issue

**Comment by therajanmaurya** [comment]
Document Update and Remove Feature Added. 
This Issue Completed

**Comment by therajanmaurya** [comment]
Added in #373
