### ISSUE TITLE
Drop-down values when creating loan account at group level aren't available

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#358]
**Summary:** 

Drop downs associated with a loan product at the individual level aren't available when trying to create same loan product at the group level. 
**Steps to reproduce:** 

Go to group, Santa Maria Group 2, from more menu, select Add Loan Account, select income generating loan as product type. Try to fill out

**Expected behavior:** 

Be able to fill out all fields and successfully submit loan application

**Observed behavior:** 

Drop-downs for Amortization, interest calculation period, repayment strategy, fund, loan officer, and interest type method has no values. See screenshots.

**Device and Android version:** 
Demo Sever on HTC One M8 with Android 6.0
**Screenshots:**

**Comment by edcable** [comment]
![screenshot_20160927-150106](https://cloud.githubusercontent.com/assets/823454/18894708/538c1282-84c9-11e6-9150-7eeecb211f79.png)

**Comment by mayank-kgp** [comment]
@edcable  I am working on this.

**Comment by mayank-kgp** [comment]
@edcable  @therajanmaurya  This is happening because empty response is coming from the server side. I think there is no bug in android code. It is because values are not available. Please see the screenshot. 
<img width="1280" alt="screen shot 2016-09-30 at 13 16 11" src="https://cloud.githubusercontent.com/assets/11210887/18984163/80ce8008-870e-11e6-86e8-23c31a7ddd7e.png">

**Comment by edcable** [comment]
@mayank-kgp @therajanmaurya @ishan1604 hmmm...the values are present there for an individual loan on the last three and the first three, amortization, interest calculation period, and repayment strategy are system-generated drop-downs and should have values.

**Comment by mayank-kgp** [comment]
@therajanmaurya  PR has been merged 
Please close it.

**Comment by therajanmaurya** [comment]
fixed in #381
