### ISSUE TITLE
App doesn't displayed logged in user info, incorrectly displays client info (MIFOSAC-158)

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#359]
**Summary:** 

When you log in, name/photo/profile should be that of authenticated user but it's that of a client (R Smith)

**Steps to reproduce:** 

Log in and go to dashboard

**Expected behavior:** 

See name, avatar of the logged in user. 

**Observed behavior:** 

 Name/avatar of a client (R Smith) is displayed
**Device and Android version:** 

Demo Server on HTC One M8 with Android 6.0

**Screenshots:**

**Comment by edcable** [comment]
![screenshot_20160927-151952](https://cloud.githubusercontent.com/assets/823454/18894696/3b5b56d2-84c9-11e6-8e83-98ecadf0b792.png)

**Comment by therajanmaurya** [comment]
Fix in #343
