### ISSUE TITLE
Pinpoint location causes app to crash

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#361]
**Summary:** 

When trying to do the pinpoint location, the app just crashes with the "Unfortunately, MifosX Droid has stopped" error
**Steps to reproduce:** 
Navigate to a client and click more menu and then pinpoint location
**Expected behavior:** 
Bring up a map to drop a pin
**Observed behavior:** 
Just the error
**Device and Android version:** 
Demo Server on HTC One M8 with Android 6.0
**Screenshots:**

**Comment by top-gun007** [comment]
@edcable i think the issuse is resolved as when I tried the app on moto E2 it is not crashing and is bringing up a map

**Comment by sosnickm** [comment]
@edcable do you have Google play services on whatever device you are using? (the error that I have coming up for me when I try to run this is that I don't have Google play services)

**Comment by reverie-ss** [comment]
If the location permission is not enabled, then the app crashes.

**Comment by therajanmaurya** [comment]
fix in #472
