### ISSUE TITLE
Path tracker causes app to crash

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#362]
**Summary:** 
When trying to run the path tracker, the app just crashes with the "Unfortunately, MifosX Droid has stopped" error
**Steps to reproduce:** 
From Dashboard, just click Path Tracker

**Expected behavior:** 
Bring up a map that will track location of worker and turn on GPS tracking
**Observed behavior:** 
Just the error
**Device and Android version:** 
Demo Server on HTC One M8 with Android 6.0
**Screenshots:**

**Comment by sosnickm** [comment]
<img width="405" alt="screen shot 2016-10-23 at 2 18 25 am" src="https://cloud.githubusercontent.com/assets/12140915/19624491/0154fc2e-98c7-11e6-977f-92c6f79ec09f.png">

**Comment by sosnickm** [comment]
This is what I get when I click Path Tracker (Android 4.1.1), can you try clicking on it again and seeing if this is just a problem with your version?

**Comment by edcable** [comment]
@therajanmaurya, is this fix included in latest build? My app still crashes when I press start tracking.

**Comment by therajanmaurya** [comment]
fix in #478
