### ISSUE TITLE
Add Ability to Add New Identifiers from Android App

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#365]
**Summary:** 

Right now you can just view identifiers and upload new docs or remove docs from them, there should be the ability to add a new identifier with a plus sign on the right to add new identifier and upload a document
**Steps to reproduce:** 
Navigate to client and then go to identifiers
**Expected behavior:** 
Have the option to add a new identifier

**Observed behavior:** 
Can just view identifiers but not add new ones
**Device and Android version:** 
Demo Server on HTC One M8 with Android 6.0
**Screenshots:** 
![screenshot_20160927-162832](https://cloud.githubusercontent.com/assets/823454/18895581/b0290968-84cf-11e6-8fc8-964b949bc20c.png)

**Comment by therajanmaurya** [comment]
I am working in this Issue

**Comment by therajanmaurya** [comment]
@edcable @ishan1604 I did not understand  work of the "Upload" button.
neither found any API to upload.

**Comment by therajanmaurya** [comment]
Create New Identifier Done.

**Comment by therajanmaurya** [comment]
Sorry, I got the Identifier Document Upload and It's done.
Working on Update identifier.

**Comment by therajanmaurya** [comment]
Added in #373
