### ISSUE TITLE
Remove ImageLoadingAsyncTask for Image Loading with Glide. In ClientDetailsFragment.

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/android-client#370]
**Summary:** 

Remove ImageLoadingAsyncTask for Image Loading to Glide.
In ClientDetailsFragment.

**Steps to reproduce:** 
Navigate to Client Details.

**Expected behavior:** 
Client Image should load in different Thread other than Main thread.

What did you expect the app to do?
Client Image should load in different Thread other than Main thread.

**Observed behavior:** 
Client Image Loading using AsyncTask in main Thread.

What did you see instead?  Describe your issue in detail here.
Client Image is loading in main that is making the app glitchy and decreasing the performance.

**Device and Android version:** 

Moto G Turbo 3 (Android 6.0 Marshmallow) , Stock Rom.

**Comment by therajanmaurya** [comment]
@top-gun007 You can work in this Issue.

**Comment by top-gun007** [comment]
Thanks @therajanmaurya I'll start right away

**Comment by top-gun007** [comment]
hey @therajanmaurya should I convert the downloaded image into bitmap

**Comment by therajanmaurya** [comment]
do you mean to save in local, So answer is No.
Here we have to show client profile in ImageView using Glide.

**Comment by top-gun007** [comment]
ok..thanks for being so helpful @therajanmaurya

**Comment by top-gun007** [comment]
@therajanmaurya i have fixed the issue will send a pull request soon
just to confirm you wanted to implement in the following snap only na?
![screenshot_1475860584](https://cloud.githubusercontent.com/assets/15179401/19199169/5a834b7c-8ce0-11e6-8de4-b22064fba919.png)

**Comment by top-gun007** [comment]
the image quality was a bit down as glide uses RGB565

**Comment by top-gun007** [comment]
and one more thing do i need to create a work around for onDetach() method in ClientDetailsFragment.
which is currently relying on async task
Regards
Ashu

**Comment by therajanmaurya** [comment]
@top-gun007 good to know that you have fixed the issue.
It's very difficult to suggest you here without looking, What you have changed and what not.
So Please open the PR then I will review that will best.

Great work 👍

**Comment by top-gun007** [comment]
@therajanmaurya i have submitted a pull request please review it

**Comment by top-gun007** [comment]
@therajanmaurya I didn't run gradelew before submitting pull request and it failed.

**Comment by therajanmaurya** [comment]
So run and when all check will pass, send PR again.

On 08-Oct-2016 7:40 AM, "Ashutosh Dadhich" <notifications@github.com> wrote:

@therajanmaurya <https://github.com/therajanmaurya> I didn't run gradelew
before submitting pull request and it failed.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openMF/android-client/issues/370#issuecomment-252396218>,
or mute the thread

**Comment by therajanmaurya** [comment]
fixed #379
