### ISSUE TITLE
Keyword "tap" should be used instead of "click"

### ISSUE THREAD

**Issue by top-gun007** [openMF/android-client#376]
**Summary:** 

On many instances across the device where user interaction is required some text is displayed which says for eg. click to refresh/click to open file instead it should be "tap to refresh" etc. 

**Steps to reproduce:** 

Just change the values in strings.xml.

**Expected behavior:** 

The app should direct the user to tap instead of click as it gets confusing

**Observed behavior:** 

The app should direct the user to click instead of tap 

**Device and Android version:** 

 Android 7.0 Naught 
**Screenshots:** 

![screenshot_1475975932](https://cloud.githubusercontent.com/assets/15179401/19218510/5cd9d9ec-8e19-11e6-8ec7-fd6f9314efa6.png)

**Comment by ishan1604** [comment]
@therajanmaurya why was this issue closed without a reason in the comment below ?

**Comment by ishan1604** [comment]
Since tap is not required here, this is not a valid issue. 
Thanks for clarification @therajanmaurya
