### ISSUE TITLE
No Response for Invalid username/password in login activity

### ISSUE THREAD

**Issue by chiragw15** [openMF/android-client#389]
When a user enters wrong username or password, there is no response.

**Expected behavior:** 

There should be a message if user enters invalid username/password. 

These are some implementations, I tried.

1.) SnackBar
![screenshot_20161105-220253](https://cloud.githubusercontent.com/assets/16978820/20032088/e540ba68-a3a8-11e6-9b3c-4a5fbca24dc0.png)

2.)Toast
![screenshot_20161105-214433](https://cloud.githubusercontent.com/assets/16978820/20032089/f0df2134-a3a8-11e6-9446-8e0751cb3d4d.png)

3.) DialogBox
![screenshot_20161105-220901](https://cloud.githubusercontent.com/assets/16978820/20032093/ffb30194-a3a8-11e6-8136-03018ccc8e72.png)

@therajanmaurya Please let me know which implementation looks good.

**Comment by therajanmaurya** [comment]
The first approach looks good 👍

**Comment by chiragw15** [comment]
Okay sure. I'll be sending a PR for this soon.

**Comment by therajanmaurya** [comment]
fixed in #522

**Comment by tarun0** [comment]
@iadeelzafar Create a new issue for that. Make sure to add a gif to reproduce the issue.
