### ISSUE TITLE
CenterList UI Enhance

### ISSUE THREAD

**Issue by mayank-kgp** [openMF/android-client#390]
**Summary:** 

UI enhancement of Center List Activity

**Steps to reproduce:** 

Go to Centers

**Expected behavior:** 

Summary of each center should be properly displayed.

**Observed behavior:** 

Display of information is not well separated and not presentable.

**Device and Android version:** 

Demo Server on YUREKA with Android 5.1.1

**Screenshots:** 

Proposed Design - 

![centerlist](https://cloud.githubusercontent.com/assets/11210887/20141619/31b0b4be-a6b7-11e6-9c34-e85de64bdde2.png)

**Comment by therajanmaurya** [comment]
fix in #392
