### ISSUE TITLE
Hide (Soft) Keyboard on clicking search 

### ISSUE THREAD

**Issue by tarun0** [openMF/android-client#394]
**Summary:** 

The softkeyboard should hide once the user clicks on 'Search' button (or taps on NavigationBar) in ClientSearchFragment but it doesn't.

**Steps to reproduce:** 

On the first screen after login, the ClientSearchFragment is shown. Type anything there and press search (without tapping on the 'Done' button on the soft keyboard). The keyboard will still be there. Now if the user taps on 'Search' then the Toast "_No string entered_." will also be hidden behind the keyboard.

**Expected behavior:** 

The keyboard should hide in any of the following cases:
1. The user taps on 'Search' button.
2. The user taps on the 'Hamburger' icon or when the Navigation Drawer is opened as the keyboard hides like half of the Navigation Bar.

**Observed behavior:** 

The keyboard doesn't hide after the user presses 'Search' button or taps on the 'Hamburger' icon.

**Device and Android version:** 

Not device specific. However, I used the emulator with Marshmallow (API 23).

**Screenshots:** 

![issue 1](https://cloud.githubusercontent.com/assets/12914286/20245186/f9111f64-a9c1-11e6-8677-eecb9e2b8d80.png)

![issue 2](https://cloud.githubusercontent.com/assets/12914286/20245192/12837b72-a9c2-11e6-8bed-d9797f9bfea7.png)

**Comment by therajanmaurya** [comment]
Looks good, Go ahead.
Feel free to ask anything.

**Comment by therajanmaurya** [comment]
Fixed in #440
