### ISSUE TITLE
Search menu Item in Centers List finishes the activity

### ISSUE THREAD

**Issue by tarun0** [openMF/android-client#396]
**Summary:** 

In the Centers list fragment, the Menu Item `Search` finishes the activity.

**Steps to reproduce:** 

Open Navigation Bar, tap on `Centres`. On the Toolbar, tap the menu item `Search`. The activity finishes.

**Expected behavior:** 

Should have shown the list of centres which match (or contain) the string entered.

**Observed behavior:** 

The activity finishes.

**Device and Android version:** 

Marshmallow (API 23) emulator.

**Screenshots:**

**Comment by mayank-kgp** [comment]
@tarun0  Are you working on this issue?
If not, can I work on this?

**Comment by tarun0** [comment]
@mayank-kgp  No, I've not started working on it yet but would like to, once @therajanmaurya clears that the proposed behaviour by me is indeed the expected behaviour.

**Comment by mayank-kgp** [comment]
@tarun0 @therajanmaurya I was curious to know about this issue. This is pending since a long time in android client. Is anyone working on this issue?

**Comment by shobhitagarwal1612** [comment]
@mayank-kgp I would like to work on this

**Comment by therajanmaurya** [comment]
fixed.
