### ISSUE TITLE
Add Button to Create Client from Listing of Group Clients

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#401]
**Summary:** 

Just as you can do in the web app, it'd be good to be able to add a client directly to a group from the app mobile app. Currently when you view a list of clients within a group.

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)

**Steps to create** 

* Navigate to Groups. Select a group
* Click the More Menu, select Group clients
* Both when there are clients or aren't any clients, it would be nice to have a button at the top right to add/create a new client.

To see how this works on the app, navigate to the demo server and then go to any group and then from the client listing for the group, click +Add and create a client (who will then belong in the group). 

**Expected behavior:** 
Go through the create client workflow and the client is then created and within that group.  To test out on the Web

**Screenshots:** 

![screenshot_20161121-203350](https://cloud.githubusercontent.com/assets/823454/20511921/f448caac-b030-11e6-9827-30b8da5b1ce2.png)
![screenshot_20161121-203959](https://cloud.githubusercontent.com/assets/823454/20511917/ef24b3a6-b030-11e6-8a27-0ea7f71518e1.png)

**Comment by mayank-kgp** [comment]
@therajanmaurya Please assign it to me if it can be worked.

**Comment by therajanmaurya** [comment]
you can work.

**Comment by mayank-kgp** [comment]
@therajanmaurya what would be better between "Having a button as Sync is there after long press on any client" and "creating an option menu and putting Create Client in that option menu".

**Comment by therajanmaurya** [comment]
fix in #523
