### ISSUE TITLE
Add labels for Submitted On and Disbursement On for Create Loan View (Individual & Group)

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#402]
**Summary:** 

These input fields are currently just the date picker without any label. 
**Steps to reproduce:** 

Navigate to any client or any group and add a loan account. You'll see the date fields without a label. 

**Expected behavior:** 
Have a clearly placed label to identify what date is being selected. 

**Observed behavior:** 

Just the date field

**Screenshots:** 
![screenshot_20161122-072027](https://cloud.githubusercontent.com/assets/823454/20531092/7ff74980-b08a-11e6-8c0c-a5c66edf8f2b.png)

**Comment by therajanmaurya** [comment]
fix in #473
