### ISSUE TITLE
Include proper input field for nominal interest rate for create loan view

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#403]
**Summary:** 

Nominal Interest Rate should be specified in one input field as a rate that's either per month or per year (based on product configuration. 

For the create loan view for the individual clients and groups, it presents the user two different input fields for the nominal interest rate. Both are incorrect. 
**Steps to reproduce:** 

Navigate to any client or group and click to add loan.

**Expected behavior:** 

Just as in the web app, there should be one single required input field with the label, "nominal interest rate" and then after the field it should be either per month or per year. Whether or not it's a monthly or yearly rate should be generated by the system given it's a parameter that is specified at product creation and not configurable at account creation.

**Observed behavior:** 

The user is presented with two input fields both with incorrect labels.
* Nominal annual intrest (has both a typo and shouldn't specify annual)
* Nominal interest rate per year (shouldn't always be per year - should be dynamic based on product configuration setting 

**Screenshots:** 
![screenshot_20161122-072051](https://cloud.githubusercontent.com/assets/823454/20531481/c141f902-b08b-11e6-8131-1e7df26aa82a.png)

**Comment by edcable** [comment]
@therajanmaurya, I know you already know but this is critical for release.

**Comment by therajanmaurya** [comment]
fix in #445
