### ISSUE TITLE
Ideal Create Loan Account Fields & Layout [was MIFOSAC-153]

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#405]
**Summary:** 

Ideally the loan creation field should contain only those fields that a field officer should be able to edit for a new loan account. All the options available in the web app won't be made available but those that are necessary to be performed in the field should be supported.

I propose the following input fields and order of display (based on web app UI):

- [ ] Product
- [ ] Loan Purpose
- [ ] Loan Officer
- [ ] Fund
- [ ] Submitted On:
- [ ] Disbursement On:
- [ ] External ID: 

- [ ] Savings Linkage (Dropdown to select linked savings)

- [ ] Principal (should display default amount)
- [ ] Number of Repayments (should display default amount)
- [ ] Nominal interest rate (should display default amount) and should be per month or per year based on what's configured at loan product level
- [ ] Repaid every (input field and then drop down to select days, weeks, months. If it's months, should be able to select subsequent dropdown for  what day of the month (i.e. first Monday, second Wednesday)

**Comment by tarun0** [comment]
Can I start working on this? @edcable @therajanmaurya

**Comment by edcable** [comment]
Yes. Please go ahead @tarun0. All the fields included in this list should be able to be overridden while creating an account and not just at the product level. The fields that aren't exposed in the account creation process aren't listed here.

**Comment by tarun0** [comment]
@edcable I've fixed this and the other issues with it -  #403 and #402 in https://github.com/openMF/android-client/pull/449 
I've added `Link Saving` options, `Repaid Every` and reordered the fields. Below are screenshots of the same. Haven't removed the already added fields, though. Please let me know if they must be removed. I thought it'd be fine to provide a webapp like experience. 

![screenshot_5](https://cloud.githubusercontent.com/assets/12914286/21289235/cb4fa5d4-c4bd-11e6-97dc-6f09c45c92c0.png)

![screenshot_6](https://cloud.githubusercontent.com/assets/12914286/21289254/fb2302d8-c4bd-11e6-830d-d2beaa3e682c.png)

**Comment by edcable** [comment]
Great work @tarun0!
