### ISSUE TITLE
Add following fields to the Create Savings Account form 

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#408]
Based on the most typical use case of creating a savings account from the mobile app, we should include the following fields.
- [ ] Savings Product*
- [ ] Field Officer
- [ ] Submitted On*
- [ ] External ID
- [ ] Nominal Annual Interest*

For the following four required fields, I would propose they don't get included in the savings creation form and they just inherit the default values that are specified at the product level. These should ultimately be parameters that should only be configured at the product level and not be overridden at account level.

- [ ] Interest calculated using*
- [ ] Interest compounding period*
- [ ] Interest posting period*
- [ ] Days in year* 

These conditional fields should be included: 

- [ ] Enforce Minimum Balance (checkbox) and then if selected input field for...
 - [ ] Minimum Balance
- [ ] Is overdraft allowed (checkbox) and then if selected input fields for
 - [ ] Maximum overdraft amount limit 
 - [ ] Nominal annual interest for overdraft
 - [ ] Min Overdraft Required for Interest Calculation

**Comment by edcable** [comment]
See https://mifosforge.jira.com/browse/MIFOSAC-133 and possible PR

**Comment by top-gun007** [comment]
can i work on it @edcable thank you

**Comment by therajanmaurya** [comment]
Yeah, Go ahead.

**Comment by top-gun007** [comment]
just to make sure we are on the same page you want me to implement changes here right?
![screenshot_1480077041](https://cloud.githubusercontent.com/assets/15179401/20626513/373f0e40-b340-11e6-948a-c2022a7e1e0b.png)

**Comment by therajanmaurya** [comment]
Yeah :)

**Comment by top-gun007** [comment]
ok @therajanmaurya here is the approach which I am going to follow:

- for the first part I am going to create the necessary field in the xml and the  use SavingsPayload.java to post the parameters as I there are already some unimplemented methods in it.

- for the second part I am going to remove the fields and post directly the parameters using SavingsPayload.java

- and for the third part I am going to hide the parameter using android:setVisibility attribute and the paramter shows up when the corresponding box is checked.

**I have one doubt though**

- How am I going to post the parameters of the third part is their an Api already built for them (only implement the getter and setter part in SavingsPayload.java) or something else.

**Thank you and please suggest any changes if want to do it in some other way**

**Comment by therajanmaurya** [comment]
@top-gun007 In 2nd point which fields you are going to remove and rest of things looks fine.

**Comment by top-gun007** [comment]
The following fields rajan:
 - Interest calculated using*
-  Interest compounding period*
-  Interest posting period*
-  Days in year*

**or should I just show their default values but the user would not be able to edit them**

Please correct me if I am wrong.
Thanks

**Comment by top-gun007** [comment]
should I remove the fields in the second part?
Thank you

**Comment by edcable** [comment]
Yes those fields don't need to be exposed during savings creation. How is work going on this? It would be nice to ship as part of the release.

**Comment by top-gun007** [comment]
@edcable the work is mostly done only one field(Field Officer) was left unimplemented as I was not sure how to implement it. I asked on channel many times but nobody replied.  

If you could help me with it I can complete it.

The problem I was facing was:
Weather Field Officer is an edit text field or a spinner. If its a spinner where should I get the values from.

_Thank you_

**Comment by tarun0** [comment]
@top-gun007 I guess your query would have been resolved by now. If not, I'll try to help you. The _Field Officer field_ in the question should be the one below.

![screenshot_3](https://cloud.githubusercontent.com/assets/12914286/22020749/f04a19de-dcdf-11e6-961f-225ac35c23cf.png)

Yes, it's a spinner and the values are retrieved from the array `fieldOfficerOptions` from the `https://demo.openmf.org/fineract-provider/api/v1/savingsaccounts/template` Endpoint.

You can always refer the web-app and the chrome dev tools whenever you are stuck and can also approach the mailing list as well.

![screenshot_4](https://cloud.githubusercontent.com/assets/12914286/22020944/cca074c8-dce0-11e6-800a-be91ac30cd1e.png)

**Comment by mayank-kgp** [comment]
@top-gun007 Please tell about the work status asap as this is going to be a part of the release tomorrow.

**Comment by top-gun007** [comment]
Hi sorry I stopped working on it long ago but if it's urgent can do it by morning

**Comment by mayank-kgp** [comment]
@top-gun007 I am working on it. I will take your help if required. :)

**Comment by therajanmaurya** [comment]
fix in #477
