### ISSUE TITLE
Unable to view Center Details

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#409]
**Summary:** 

The Centers navigation workflow still is of the old format in which it's just a navigational aid and it's not possible to actually navigate to and view and edit a center's details. 

**Steps to reproduce:** 

One should be able to navigate to a center and then view its details:

- [ ] link form more menu to list of groups
- [ ] activation date
- [ ] Meeting details (if assigned)
- [ ] Assigned loan officer/staff

Summary Info (these would all be nice for GCI)
- [ ] Active Clients
- [ ] Active Group Loans
- [ ] Active Client Loans
- [ ] Active Group Borrowers
- [ ] Active Client Borrowers
- [ ] Active Overdue Group Loans
- [ ] Active Overdue Client Loans 

**Observed behavior:** 

Right now you just navigate from center to groups to clients.

**Comment by therajanmaurya** [comment]
fix in #506
