### ISSUE TITLE
Add ability to create center savings account [MIFOSAC-129]

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#411]
**Summary:** 

From the center view, from the more menu, there should be a link to add/create savings account that belongs to a center. The savings account application should contain the same fields as that of a client or group savings application.

**Comment by tarun0** [comment]
Some description:

   `Center view` stated above refers to the screen shown
      In [webapp](https://demo.openmf.org), by clicking on

> _Centers -> select any center xyz_

In android app, by opening
>_Navigation Drawer -> Centers -> select any center xyz_

In the webapp's center view, there's an option named `Center Saving Application`. The same feature has to be implemented in the android app's center view. 

For reference see the implementation in Client's Loan Application by opening
 >_Navigation Drawer -> Clients -> select any client xyz_
 From more options menu, select _Add Savings Account_.

**Comment by therajanmaurya** [comment]
Added in #425
