### ISSUE TITLE
Replace all the hardcoded strings with @string resource

### ISSUE THREAD

**Issue by mayank-kgp** [openMF/android-client#412]
**Summary:** 

All the hardcoded string in code should be replaced with separate string resource in string.xml file.
For example - In  mifosng-android/src/main/res/menu/client_save_pin.xml "Save pin" is written. Instead of that, this string should be in different string.xml files according to different languages.

**Steps to reproduce:** 

Start Run Inspect By Name and see all the hard coded strings by searching "hardcoded string".

**Expected behavior:** 

All the strings should be in string.xml file for internationalisation.

**Observed behavior:** 

Strings are harcoded in many places.

**Comment by yvsssantosh** [comment]
@mayank-kgp 

I'd like to work on this issue
Please assign it to me

**Comment by sagarchoudhary96** [comment]
@therajanmaurya can i work on it ?

**Comment by AkshGautam** [comment]
@therajanmaurya @tarun0 @droidchef  The strings are still hardcoded at some places. I would like to fix this.

**Comment by RajaVamsi11** [comment]
@tarun0 @moksh-mahajan, As @AkshGautam said there are still some hardcoded strings in the files. Can I work on this issue?

**Comment by deepak-prajapatii** [comment]
@therajanmaurya Can I work on this issue?
