### ISSUE TITLE
Update Client List User Guide

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/android-client#416]
**Summary:** 
Update this [Client List User Guide](https://mifosforge.jira.com/wiki/display/docs/Working+with+center+lists) with the Latest screenshot and describe the how Client List feature is working with a brief description.
The current documentation is the outdated, Now the whole client list feature changes with new working design.

Please look Present User guide and Run the app and check the client list feature you will found out.

**Steps to reproduce:** 

Open the app and  [Client List User Guide](https://mifosforge.jira.com/wiki/display/docs/Working+with+center+lists), look that user guide is outdated. 

**Expected behavior:** 

 [Client List User Guide](https://mifosforge.jira.com/wiki/display/docs/Working+with+center+lists)
should be updated but it's not.

**Observed behavior:** 

 [Client List User Guide](https://mifosforge.jira.com/wiki/display/docs/Working+with+center+lists) is not updated, need to update.

**Device and Android version:** 

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:** 

Add screenshot with high resolution.

**Comment by yvsssantosh** [comment]
@therajanmaurya 
I'd like to work on this so kindly assign it to me

**Comment by therajanmaurya** [comment]
@yvsssantosh Sorry I forget to add the GCI tag, These are a very simple issue for School Children.
Thanks.

**Comment by yvsssantosh** [comment]
@therajanmaurya 
Never mind  then I will look for another issue 👍 
Thanks for the reply :)

**Comment by SafeFatNoob** [comment]
hi! I am doing this task for GCI. I have updated all steps besides the [final step](https://mifosforge.jira.com/wiki/display/docs/Working+with+center+lists) which I am not able to get to.

**Comment by therajanmaurya** [comment]
Why are you editing document of center list because in this task you have
to edit the documentation of client list.

**Comment by SafeFatNoob** [comment]
my bad, I assumed that was a typo as all hyperlinks on this issue and on GCI link to the centers page. is [https://mifosforge.jira.com/wiki/display/docs/View+Accounts+of+a+Client](https://mifosforge.jira.com/wiki/display/docs/View+Accounts+of+a+Client) the correct one?

**Comment by therajanmaurya** [comment]
Yes It is right link
https://mifosforge.jira.com/wiki/display/docs/View+Accounts+of+a+Client

**Comment by therajanmaurya** [comment]
Updated User guide At here https://mifosforge.jira.com/wiki/display/docs/View+Accounts+of+a+Client
