### ISSUE TITLE
Update Center List User Guide

### ISSUE THREAD

**Issue by mayank-kgp** [openMF/android-client#419]
Summary:
Update this [Center List User Guide](https://mifosforge.jira.com/wiki/display/docs/Working+with+center+lists)  with the Latest screenshot and describe the how Center List feature is working with a brief description.
The current documentation is the outdated, Now the whole center list feature changes with new working design.

Please look Present User guide and Run the app and check the center list feature you will found out.

Steps to reproduce:

Open the app and  [Center List User Guide](https://mifosforge.jira.com/wiki/display/docs/Working+with+center+lists), look that user guide is outdated.

Expected behavior:

Center List User Guide
should be updated but it's not.

Observed behavior:

Center List User Guide is not updated, need to update.

**Comment by therajanmaurya** [comment]
Completed here https://mifosforge.jira.com/wiki/display/docs/Working+with+center+lists
