### ISSUE TITLE
App is crashing

### ISSUE THREAD

**Issue by vishwesh3** [openMF/android-client#423]
**Summary:** 

Runtime permission.

**Steps to reproduce:** 

Add runtime permission

**Expected behavior:** 

When app is trying to get location (and storage) first it should for permission, if granted then proceed else ask permission . 

**Observed behavior:** 

If permission is not granted it doesn't  ask for permission and crashes.

**Device and Android version:** 

Tested on ASUS Zenfone selfie Android 6.0.1

I want to work on this.

**Comment by reverie-ss** [comment]
The issue has been raised #362

**Comment by vishwesh3** [comment]
@reverie-ss Sorry, I didn't know that it is already open.
