### ISSUE TITLE
Show Correct ActionBar Title While Creating Center or Client

### ISSUE THREAD

**Issue by vishwesh3** [openMF/android-client#427]
**Summary:** 

Some items in menu (`client_search.xml`) are redundant.

**Steps to reproduce:** 

Open menu in `DashboardActivity`.

**Expected behavior:** 

For example if **Create Centre** page is opened, then it should not show **Create Centre** option in menu. Same for **Create Client**.

**Observed behavior:** 

It is showing **Create Centre** option in **Create Centre** page. Same for **Create Client**.

**Device and Android version:** 

ASUS ZENFONE 2

**Screenshots:** 

![screenshot_20161207-134419](https://cloud.githubusercontent.com/assets/18511177/20959872/5b78a400-bc83-11e6-9e30-d4b350736b62.jpg)

**Comment by vishwesh3** [comment]
@therajanmaurya  Please review it.

**Comment by therajanmaurya** [comment]
@vishwesh3 Looks good,
I want two change in this PR 
1. Change the Actionbar title like "Create Client", "Create Center".
2. Rename the ```client_search.xml``` to ```menu_main.xml```

**Comment by vishwesh3** [comment]
Ok I will send PR soon.

**Comment by vishwesh3** [comment]
@therajanmaurya 
Now we are updating title for each page, so should I remove "Create client" (marked in red) from the xml?

![whatsapp image 2016-12-08 at 2 30 43 am](https://cloud.githubusercontent.com/assets/18511177/20986379/74c025f8-bcee-11e6-9d22-d8a3d6593bcb.jpeg)

**Comment by vishwesh3** [comment]
@therajanmaurya waiting for your review.

**Comment by therajanmaurya** [comment]
@ishan1604 @edcable What do you think about the "Create Client" in the red circle. we want that or not.

**Comment by therajanmaurya** [comment]
Fixed in #439
