### ISSUE TITLE
Can't create client - 'client classification' not loaded

### ISSUE THREAD

**Issue by tarun0** [openMF/android-client#433]
**Summary:** 

Can't create a new client from the Dashboard.

**Steps to reproduce:** 

From Dashboard, open 'More Menu' -> Create Client.

**Expected behavior:** 

All the values in the template should have loaded correctly. 

**Observed behavior:** 

The 'Gender' and 'Client' values take significant time in loading and the `Client Classification` value is not loaded. As a result of which the error `The parameter clientClassificationId must be greater than 0.` is thrown.

**Device and Android version:** 

Android Emulator - API 23
Xiaomi Redmi Note 1S - Kitkat (4.4) - API 19

**Screenshots:** 

![classification](https://cloud.githubusercontent.com/assets/12914286/21050939/b56adcfa-be43-11e6-9e9e-5482e9b9eecb.png)

**Comment by mayank-kgp** [comment]
@tarun0 https://demo.openmf.org/fineract-provider/api/v1/clients/template?tenantIdentifier=default
This api is giving empty Json Array of clientClassificationOptions. I think this is the reason of issue.
@therajanmaurya Please give a comment on this.

**Comment by therajanmaurya** [comment]
In new version of fineract. there is the functionality of adding data table that why It is failing. we have to add feature,  adding datatable values during creating the client.

BTW this issue I have been fixed in #450
