### ISSUE TITLE
App crashes on setting visiting date to center

### ISSUE THREAD

**Issue by tarun0** [openMF/android-client#435]
**Summary:** 

App crashes on setting a visiting date to any center.

**Steps to reproduce:** 

From NavigationDrawer, tap on 'Centers'. Long tap any center. Date picker will show up. Select any date. It crashes with NullPointerException.

**Expected behavior:** 

The date should have been selected successfully and the subsequent screen of all the meetings should have been shown, [as explained here](https://mifosforge.jira.com/wiki/display/docs/Working+with+center+lists).

**Observed behavior:** 

App crashes.

**Device and Android version:** 

Android Emulator - Marshmallow - API 23

**Screenshots:**

**Comment by therajanmaurya** [comment]
Fixed in #440
