### ISSUE TITLE
Process Dialog should appear when client views his/her Loan/Saving/Recurring account information 

### ISSUE THREAD

**Issue by top-gun007** [openMF/android-client#441]
**Summary:** 

When we view client's account information in Client fragment a process dialog should pop up so at least we know that the app is trying to retrieve information instead of giving the perception that the following feature is not working        

**Expected behavior:** 

Process Dialog should appear when we select loan/savings/recurring account.

**Observed behavior:** 

The corresponding account info is only shown when it is downloaded in the background no way of telling whether the app is working in the background for retrieving the information or not.   

**Device and Android version:** 

Era X1 (Android Marshmallow) 

**Screenshots:** 
![image](https://cloud.githubusercontent.com/assets/15179401/21128299/bcdebb9e-c11f-11e6-9e58-841716e75c60.png)

.

**Comment by FleetAdmiral** [comment]
Hey! I'm new to the project and would like to start working on it with this issue, could it take it up?

**Comment by top-gun007** [comment]
I was thinking of working on it myself. Once it gets approved.
@therajanmaurya is this issue approved?

**Comment by therajanmaurya** [comment]
No need for Progress Dialog while fetching the Client Accounts because we are not sharing any information that most important for us. It simple @Get request.
