### ISSUE TITLE
Incorrect app`s behavior in some locales.

### ISSUE THREAD

**Issue by TypicalGitHubUser** [openMF/android-client#455]
**Summary:** 

Incorrect app`s behavior in group and client screens, if, for example, katalian or russian locale is set on device.

**Steps to reproduce:** 

1. Launch an Android Emulator
2. Choose katalian (ca) locale.
3. Launch the app.
4. Choose any client or group.

**Expected behavior:** 

Information about client or group.

**Observed behavior:** 

In client screen : error message "Client not found" and infinite loading of client`s photo. All data except of activation date and office name are showed.
In group screen : error message "Failed to fetch group and accounts" and empty data.

**Comment by therajanmaurya** [comment]
fixed in #456
