### ISSUE TITLE
Crash on Selecting Centers from Navigation Drawer

### ISSUE THREAD

**Issue by tarun0** [openMF/android-client#457]
**Summary:** 

App crashes on selecting Centers from Navigation Drawer. 

**Steps to reproduce:** 

From Navigation Drawer select Centers. 

**Expected behavior:** 

Center List should have appeared.

**Observed behavior:** 

App Crashes.

**Device and Android version:** 

AVD - Marshmallow API 23

**Screenshots:**

**Comment by vishwesh3** [comment]
@tarun0 I would like to work on this.

**Comment by tarun0** [comment]
Hi, @vishwesh3 This has been fixed already.

**Comment by edcable** [comment]
@therajanmaurya if you could build an API that has this fix, I will test and we can close

**Comment by therajanmaurya** [comment]
I have reviewed the PR.
