### ISSUE TITLE
Add message for no groups available associated with a center

### ISSUE THREAD

**Issue by mayank-kgp** [openMF/android-client#468]
**Summary:** 

Showing message that no group is available after clicking on a center

**Steps to reproduce:** 

Click on a specific center from center list.

**Expected behavior:** 

If there is no group associated with a center, a message should be shown that "No group associted with this center"

**Observed behavior:** 

Empty page is shown. It is very confusing as it seems that loading is not finished.

**Device and Android version:** 

Demo Server on YUREKA with Android 5.1.1

**Comment by TypicalGitHubUser** [comment]
Hi,
I fixed this issue. Please, review.

**Comment by mayank-kgp** [comment]
@TypicalGitHubUser I was working on this issue. You have done the same work. Please get it assigned by @therajanmaurya if you are working on issue that is opened by someone else. This will prevent duplicate work. :)

**Comment by TypicalGitHubUser** [comment]
@mayank-kgp Sorry. I will close this PR.

**Comment by mayank-kgp** [comment]
@TypicalGitHubUser No need to close PR now. Get it reviewed. 
:)

**Comment by mayank-kgp** [comment]
@TypicalGitHubUser Are you working on this?

**Comment by TypicalGitHubUser** [comment]
Sorry for delay. I`ve already sent PR #471

**Comment by therajanmaurya** [comment]
fixed in #471
