### ISSUE TITLE
Feature Addition in Center Creation

### ISSUE THREAD

**Issue by daveo30** [openMF/android-client#470]
Summary:  Similar to issue #308, on creating a new Center the page remains as it is without refreshing. A dialog should appear notifying the status and giving an option to create a new Center or go back to search fragment.

Expected Behaviour: A dialog gets displayed on successful creation of a Center which asks to create a new Center or not. On click of create new Center, the  previously entered data gets removed so new details can be entered. On clicking no, the search fragment is displayed again.

Observed Behaviour: The Center creation page remains as it is, even on successful creation of a Center

**Comment by shobhitagarwal1612** [comment]
I'd like to tackle this bug

**Comment by therajanmaurya** [comment]
Look this https://github.com/openMF/android-client/pull/500#issuecomment-282657099
Closed
