### ISSUE TITLE
Incorrect content in client screen, if data are not available.

### ISSUE THREAD

**Issue by k4wel** [openMF/android-client#475]
**Summary:** 

3 same rows ''Saving Accounts' in client screen.

**Steps to reproduce:** 

1. Go to the list of clients.
2. Turn off the Internet
3. Select any client

**Expected behavior:** 

Normally, we should see lists of loan, saving and recurring accounts.  And even when data are not available, we should see the same with zeros.

**Observed behavior:** 

We see 3 lines "Saving accounts"

**Screenshots:** 

![screenshot_20170122-135931](https://cloud.githubusercontent.com/assets/22119535/22182326/90ed1f66-e0ab-11e6-8c4b-ad0cdb49927e.png)

**Comment by mayank-kgp** [comment]
@TypicalGitHubUser  Are you working on it or should I try?

**Comment by TypicalGitHubUser** [comment]
@mayank-kgp I think you can try. I`m not sure I can take care of it in the short run.

**Comment by mayank-kgp** [comment]
@TypicalGitHubUser I think we can't see the details because details would be fetched from API when we click on any client from the list.  If we turn off the internet before clicking on any item, the details are not available. 
Please give a comment.

**Comment by TypicalGitHubUser** [comment]
@mayank-kgp 3 lines with exatcly the same name instead of 3 diffferent looks odd and may create negative impression of app. Either correct names or hide them at all would be more appropriate.

**Comment by mayank-kgp** [comment]
I think we should take a suggestion of @therajanmaurya

**Comment by edcable** [comment]
Just confirming that I'm facing the same issue. I will let @therajanmaurya make the final call but agree with @TypicalGitHubUser that it shouldn't display 3 rows of savings accounts but rather the same account headings you would see if online, simply with no data.

**Comment by therajanmaurya** [comment]
@TypicalGitHubUser you are right. If network request failed for some reason. App show should 
"Failed to fetch client details and account." and hide the whole UI and show instead of an ImageView and TextView with a message and on swipe refresh user can make the request again for data.

If anyone wants to pick who can. Please be careful ClientDetailsFragment code.

**Comment by mayank-kgp** [comment]
@therajanmaurya I would like to work on this issue.
Any suggestion or something that you want to tell about before working?

**Comment by therajanmaurya** [comment]
@mayank-kgp Go ahead.

**Comment by hardik124** [comment]
@therajanmaurya  i would like to work on this.

**Comment by Kigamba** [comment]
I would like to work on this @edcable @therajanmaurya

**Comment by Kigamba** [comment]
I have worked on it. I think we should also add the ability to refresh after internet connection is stable or back again.

**SCREENSHOT**

![screenshot_2017-04-04-11-49-48](https://cloud.githubusercontent.com/assets/23360506/24649180/e05ff5e4-192e-11e7-85db-db7c1c3ebec1.png)

**Comment by dabbler011** [comment]
@therajanmaurya @edcable in the present PR data is rest to 0. However there should be no data in the display and only the error message. Shall I work on the same and open PR?

**Comment by AkshGautam** [comment]
@therajanmaurya @tarun0 This issue is pending till now. May i work on this?

**Comment by ivary43** [comment]
@tarun0  sorry for the inconvenience but I didn't notice that content is wrong too  I only noticed the loading bar thing.

**Comment by ShankarNara** [comment]
I have a solution for this issue , may I work on this?
