### ISSUE TITLE
Can't change both the submission and disbursement date while creating loan

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#479]
**Summary:** 

As reported by Sifiso on the mailing list, when you create a loan, you can't select different dates for submission and disbursement date. Changing one changes the other. 

**Steps to reproduce:** 

Navigate to any client and create a new loan. Attempt to change the submission or disbursement date. 

**Expected behavior:** 

Be able to change the dates to any date irrespective of what date has been selected for the other. 

**Observed behavior:** 

Changing one date changes the other and they both remain the same date. 

**Device and Android version:** 

Le Eco 2 S3 Android 6.0

**Screenshots:** 

![screenshot_20170124-153817](https://cloud.githubusercontent.com/assets/823454/22272324/387c06f4-e24e-11e6-869b-4295ebc3431c.jpg)

**Comment by CloudyPadmal** [comment]
Can I look into this matter??

**Comment by edcable** [comment]
Certainly @CloudyPadmal

**Comment by edcable** [comment]
Just assign it to yourself so the community knows somebody is working on it. Send along any questions in our Gitter chatroom.

**Comment by CloudyPadmal** [comment]
I've forked and downloaded the project! How can I assign this to myself?

**Comment by CloudyPadmal** [comment]
I found how this happens. In `GroupLoanAccountFragment.java` in the overridden method for picking date, it will set the same date for both _Submitted on Date_ and _Disbursement on Date_ once a date is chosen. If we implement the views separately to select dates, this will be resolved :)

**Comment by CloudyPadmal** [comment]
I'll make a fix to it and send you a pull request? @edcable

**Comment by CloudyPadmal** [comment]
@therajanmaurya I've reverted those system files and pushed only the java files! Is it correct now?

**Comment by therajanmaurya** [comment]
@CloudyPadmal Looks good. I will review PR soon 👍

**Comment by CloudyPadmal** [comment]
@therajanmaurya thank you!!

**Comment by therajanmaurya** [comment]
fix in #487
