### ISSUE TITLE
Long press on center view brings up calendar

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#480]
**Summary:** 

Do a long press on any center form the list of centers and it brings up the date picker 
**Steps to reproduce:** 

See above

**Expected behavior:** 

Not sure really but typically you could select a group or client for syncing. 

**Observed behavior:** 

Date picker gets displayed 
**Device and Android version:** 

Le Eco S3 with Android 6.0

**Screenshots:** 

![screenshot_20170124-153651](https://cloud.githubusercontent.com/assets/823454/22273227/4430abde-e254-11e6-874c-6afbb282ae41.jpg)

**Comment by tarun0** [comment]
The expected behaviour, most probably, should be to check visits and update payments on that day. Here's some related info: https://mifosforge.jira.com/wiki/display/docs/Working+with+center+lists

**Comment by therajanmaurya** [comment]
@edcable right now center feature does not have support for syncing the center and their group's client. It only shows a dialog picker to pick date and check their is any meeting is schedule or not.

**Comment by therajanmaurya** [comment]
I think this is not an issue. This was the small discussion about the Long press on center view.
Closing this issue for know.
