### ISSUE TITLE
DatePicker storing wrong date

### ISSUE THREAD

**Issue by tarun0** [openMF/android-client#489]
**Summary:** 

The generic DatePicker is sending wrong date.

**Steps to reproduce:** 

Open any field that requires date input. As an example:
Open any client -> More Menu -> Add Loan Account. You'll find two fields to select date. Tap on those fields and choose the dates. Sometimes, they'll be correct. Most of the times, they are wrong, even invalid (23-50-2017 !).

**Expected behavior:** 

Correct date is stored as input.

**Observed behavior:** 

Incorrect date is stored as input.

**Device and Android version:** 

Visual Studio Emulator - Kitkat API 19
Visual Studio Emulator - Marshmallow API 23
Moto G4 (or G3) Marshmallow 23

**Screenshots:** 

![t](https://cloud.githubusercontent.com/assets/12914286/22403753/d71506fc-e646-11e6-950b-7d33679c9852.gif)

**Comment by tarun0** [comment]
The changes done in `MFDatePicker.java` in the PR #479 are resulting in this behaviour.

**Comment by therajanmaurya** [comment]
Yeah I have tested, Feel free to send PR.

**Comment by shobhitagarwal1612** [comment]
I'd like to work on this issue

**Comment by CloudyPadmal** [comment]
@therajanmaurya this issue is fixed and it is merged! This can be closed now :)

**Comment by tarun0** [comment]
Fixed and merged in https://github.com/openMF/android-client/pull/493
Closing.
