### ISSUE TITLE
Can't change both the submission and disbursement date while creating loan for Client

### ISSUE THREAD

**Issue by tarun0** [openMF/android-client#491]
**Summary:** 

On setting one of the two dates - submission or disbursement, both the dates gets set to the same picked date.

**Steps to reproduce:** 

Go to client. From More menu, select Add New Loan. Select the dates.

**Expected behavior:** 

Dates should be selected independently.

**Observed behavior:** 

Dates are the same.

**Comment by shobhitagarwal1612** [comment]
I'd like to work on this issue.
