### ISSUE TITLE
Edittext in add documents dialog under the account summary screen has no text limit.

### ISSUE THREAD

**Issue by harshitagupta30** [openMF/android-client#496]
**Summary:** 

Edittext in add documents dialog under the account summary screen has no text limit which is resulting into bad view.

**Steps to reproduce:** 

1. Under the clients, click on any of the client .
2. In action bar click on the menu, then click on documents and then finally add new document.

**Expected behavior:** 

The edittext should be restricted to a few lines instead of it taking entire window.

**Observed behavior:** 

The edit text can take any no of lines.

**Device and Android version:** 

Moto G-2 
Android version :  5.1 Lollipop

**Screenshots:** 

![screenshot_2017-02-03-19-06-03](https://cloud.githubusercontent.com/assets/12701036/22593320/ee6da70e-ea43-11e6-9795-657a1be4a636.png)

@therajanmaurya Please review!

**Comment by mayank-kgp** [comment]
I want to work on this issue.

**Comment by harshitagupta30** [comment]
@mayank-kgp I've already resolved the issue! waiting for some maintainer's reply to send the PR! :+1:

**Comment by therajanmaurya** [comment]
@harshitagupta30 send the PR. I will review.

**Comment by therajanmaurya** [comment]
fixed in #537
