### ISSUE TITLE
Client image doesn't display in client view, only in clients list

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#499]
**Summary:** 

Clients with an image (uploaded not taken via webcam) don't display image in client view only in clients list.
**Steps to reproduce:** 
Click and view a client.

**Expected behavior:** 

Client image to be displayed

**Observed behavior:** 

Only see Mifos X logo.
**Device and Android version:** 

Le Eco Android 6.0

On demo 4 server Mifos/MifosAdmin

**Screenshots:** 

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by edcable** [comment]
![screenshot_20170203-171119](https://cloud.githubusercontent.com/assets/823454/22614270/dbbc9534-ea34-11e6-8ba1-063da2b6b59b.jpg)
![screenshot_20170203-171126](https://cloud.githubusercontent.com/assets/823454/22614290/fff7448a-ea34-11e6-9296-16136a38290d.jpg)

**Comment by therajanmaurya** [comment]
fix in #504
