### ISSUE TITLE
Show Connection Status

### ISSUE THREAD

**Issue by edcable** [openMF/android-client#522]
**Summary:** 

As reported by Mayank in https://mifosforge.jira.com/browse/MIFOSX-2568, Add snackbar for showing connction status at the time of login replacing that "There was some error processing your request".
Because it would be better if there is a seperate message for users about connection status.
![screenshot_2016-03-05-16-04-43](https://cloud.githubusercontent.com/assets/823454/22977467/80e73e62-f343-11e6-829f-3b36241ab0f6.png)

**Comment by mayank-kgp** [comment]
@edcable I would like to work on this issue.

**Comment by edcable** [comment]
Go right ahead.

**Comment by therajanmaurya** [comment]
@mayank-kgp It's great. If you will look this [PR](https://github.com/openMF/android-client/pull/393) and make your own PR + this PR.

**Comment by therajanmaurya** [comment]
fixed in #535
