### ISSUE TITLE
Feature Request: Option to make password visible on home screen.

### ISSUE THREAD

**Issue by devkhan** [openMF/android-client#524]
**Summary:** 

The password is hidden, and there is no option to make it visible

**Steps to reproduce:** 

NA

**Expected behavior:** 

Option to show/hide password.

![image](https://cloud.githubusercontent.com/assets/8049092/23021482/37678b22-f472-11e6-822d-1a1806d116cc.png)

**Observed behavior:** 

![image](https://cloud.githubusercontent.com/assets/8049092/23021542/7a90e3b2-f472-11e6-8d3e-29935d837349.png)

**Device and Android version:** 

Device independent.

**Screenshots:** 

See above.

**Comment by tarun0** [comment]
I appreciate your contribution towards listing an issue. However, there's already an issue for this: https://github.com/openMF/android-client/issues/382

Also, it won't require any additional code but just updating the 'Design Support Library' version to 24.2 or higher will do the job, which @therajanmaurya will be doing soon.

**Comment by devkhan** [comment]
Thanks.
