### ISSUE TITLE
UX: `Connection Settings` on login screen doesn't feel clickable.

### ISSUE THREAD

**Issue by devkhan** [openMF/android-client#525]
**Summary:** 

The `Connection Settings` on the login screen allows to change connection option, but it feels like a plain `TextView` when it should be a `Button` or `ImageButton`.

**Steps to reproduce:** 

NA

**Expected behavior:** 

NA

**Observed behavior:** 

NA

**Device and Android version:** 

Device independent.

**Screenshots:** 

NA

**Comment by singhalok641** [comment]
I am fixing this issue

**Comment by singhalok641** [comment]
I am fixing this issue

**Comment by Pritom14** [comment]
Please review #546 . 
Here I have changed the TextView into a Button

**Comment by Pritom14** [comment]
I am new to this and whenever I edit one of the files another gets created with ~ at the end. I have submitted another pr #547 , but it has the same problem it has two extra files. Can you help me fix it?

**Comment by Pritom14** [comment]
Please review #548

**Comment by therajanmaurya** [comment]
fix in #552
