### ISSUE TITLE
Path Tracker crashes the app if GPS is turned off

### ISSUE THREAD

**Issue by TypicalGitHubUser** [openMF/android-client#527]
**Steps to reproduce:** 

1. Turn off GPS.
2. Go to Path Tracker screen.
3. Launch the path tracking by pressing a button in action bar.

**Expected behavior:** 

App keeps working and shows a warning or a dialog, asking for user's permission to modify the location settings, like in Google Maps 

**Observed behavior:** 

After 2-3 seconds app crashes, but a notification about tracking is shown.

**Comment by CloudyPadmal** [comment]
Happens to me!

**Comment by CloudyPadmal** [comment]
@TypicalGitHubUser are you on to this?

**Comment by TypicalGitHubUser** [comment]
@CloudyPadmal No, you can take it.

**Comment by CloudyPadmal** [comment]
Thank you @TypicalGitHubUser :D @therajanmaurya I've handled this error! Can you review? :)

**Comment by therajanmaurya** [comment]
@TypicalGitHubUser  @CloudyPadmal First this is not happening because of the GPS. It is happening because someone has associated the ```user_location``` data table to office and in which they are not adding the lat-long while submitting.

**Comment by therajanmaurya** [comment]
@CloudyPadmal Send your PR. I will review.

**Comment by CloudyPadmal** [comment]
@therajanmaurya exactly what you're saying! The relevant item doesn't have the latlon in the list. So indexoutofbound happens. I've caught it and pushed. I have a previous PR also and this one merged with it. Is it okay that way? Both commits together?

**Comment by therajanmaurya** [comment]
No, you have to make sperate PR for this issue.

**Comment by CloudyPadmal** [comment]
@therajanmaurya I've made a separate PR! :)
