### ISSUE TITLE
Feature Fetch Notes

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/android-client#543]
**Summary:** 

There is no feature to show Notes of client group savings and loan.
Add A Note Fragment that will be the generic type and will handle all type of note like client group savings and loan.

API: https://demo.openmf.org/api-docs/apiLive.htm#notes

**Steps to reproduce:** 

There is no feature of notes in Client Savings Group and Loan Account menu item.

**Expected behavior:** 

Add Toolbar menu item in ClientListFragment and GroupListFragment and SavingAccountSummaryFragment and LoanAccountSummaryFragment that will make fragment transaction to NoteFragment.

**Observed behavior:** 

There is no feature to show notes.

**Comment by SehgalDivij** [comment]
I am new here and want to contribute to MIFOS. Can someone suggest where to start to get familiar with the codebase??

**Comment by Rishabhk07** [comment]
Hey, can i work on this issue ?

**Comment by praveenfun2** [comment]
I would like to implement this feature @therajanmaurya .

**Comment by rahulbabbar1** [comment]
I am working on this issue. @therajanmaurya alloted this issue to me on gitter. Sorry for the inconvenience caused to all of you.
