### ISSUE TITLE
HardwareRenderer.java line 1173

### ISSUE THREAD

**Issue by ishan1604** [openMF/android-client#55]
#### in android.view.HardwareRenderer$GlRenderer.chooseEglConfig

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://crashlytics.com/openmf/android/apps/com.mifos.mifosxdroid/issues/53d7ef68e3de5099ba92f891](https://crashlytics.com/openmf/android/apps/com.mifos.mifosxdroid/issues/53d7ef68e3de5099ba92f891)

**Comment by mayank-kgp** [comment]
Hi Ishan, 
    I am not able to find this class in project. 
Can you please help me out?
Kind Regards,
