### ISSUE TITLE
How to login - version 1.0

### ISSUE THREAD

**Issue by kickbox** [openMF/android-client#550]
**Summary:** 

I have setup mifos at AWS using the image in AWS. I am not able to figure out how to login, as just specifying the ip address, username and password fails to get me pass the login.

**Steps to reproduce:** 
These are the login details I am using 
username: mifos
password: password
Instance URL: my_AWS_ip
Port: <empty>
Tenant Identifier: <empty>
https://my_AWS_ip/fineract-provider/api/v1/

**Expected behavior:** 

App should login me into the next screen

**Observed behavior:** 

I see the loading icon, and then it disappears. Stuck at the same login screen.

**Device and Android version:** 

LG Vibe, Moto G 2 - Android 5.1

**Screenshots:** 

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by therajanmaurya** [comment]
@kickbox You have to add **Port** and **Tenant Identifier: **. It's necessary. maybe you **Tenant Identifier: ** default.

You have to check which port you are using on server or local host.

**Comment by kickbox** [comment]
Thanks. Since my web address is https, I tried with port 443 and it worked. I left the tenant empty.

**Comment by therajanmaurya** [comment]
It's great. Can you please make a wiki for us on Wiki here https://github.com/openMF/android-client/wiki. 
Add a new page and add your whole approach with screenshot.

It will help others.
