### ISSUE TITLE
Improper error message

### ISSUE THREAD

**Issue by praveenfun2** [openMF/android-client#553]
Summary: 
Empty error message is produced...

Steps to reproduce:
Try to login entering any wrong "tenant identifier".

Expected behavior: 
Should have shown error message like "Incorrect tenant id"

Observed behavior:
Empty toast message appears.

![screenshot_20170303-195145](https://cloud.githubusercontent.com/assets/19526203/23554610/e2fe8622-004b-11e7-9741-cff2679d22f2.png)

Would like to fix this..

**Comment by therajanmaurya** [comment]
go ahead 👍

**Comment by AkshGautam** [comment]
@therajanmaurya @tarun0  I am working on this. it is still a prevalent issue.

**Comment by Aditya-gupta99** [comment]
The issue has already been resolved
