### ISSUE TITLE
Use the new data binding library instead of ButterKnife?

### ISSUE THREAD

**Issue by priyankvex** [openMF/android-client#556]
Android DataBinding library can decrease the boilerplate code that we tend to decrease using ButterKnife. 

As DataBinding library is already present in the projects, we won't have to add additional dependencies for ButterKnife.

I have worked with both data binding and butter knife. Should I work on this?

**Comment by therajanmaurya** [comment]
There are lot's of reasons, you can find some reasons here https://medium.com/@Miqubel/4-reasons-im-not-using-android-data-binding-e62127c2650c#.cfanyhoc6. 

I think It will break our MVP architecture. So right now I can not give you permission to implement this.

closing
