### ISSUE TITLE
SwipeRefreshLayout keeps on refreshing

### ISSUE THREAD

**Issue by tarun0** [openMF/android-client#561]
**Summary:** 

The SwipeRefreshLayout on Group List and Client List keeps on refreshing on coming back from `Create Client/Group` screen.

**Steps to reproduce:** 

Open `Clients` from the navigation drawer. Click on the *+* floating action button. Press back button

**Expected behavior:** 

Only the list should have been shown.

**Observed behavior:** 

The list is shown but the refreshing view is still there.

**Device and Android version:** 

Android Emulator - API 23

**Screenshots:** 

![refresh](https://cloud.githubusercontent.com/assets/12914286/23602463/ab6d7f38-0276-11e7-86dc-f27881da217e.gif)

**Comment by therajanmaurya** [comment]
Are you using instant run.

**Comment by tarun0** [comment]
No

**Comment by tarun0** [comment]
The layout's `seRefreshing` attribute is not set to false when the fragment is popped back. I've fixed it on the locally and will send a PR today. 

Are you not facing this?

**Comment by therajanmaurya** [comment]
Ok that's great.

**Comment by Aditya-gupta99** [comment]
The issue has already been resolved
