### ISSUE TITLE
Sort locations in Track my path.

### ISSUE THREAD

**Issue by m-murad** [openMF/android-client#565]
**Summary:** 

In Track my path activity the oldest locations are shown first while latest locations are shown last.

**Expected behavior:** 

The latest locations should be shown first while the oldest locations should be shown last.

**Device and Android version:** 

Android 7, Moto G4 Plus

@therajanmaurya 
Should I send a PR?

**Comment by karsai1993** [comment]
Hi, @free4murad ! I suppose you have solved it. That is why you would like to send a PR. Is it right?

**Comment by free4murad** [comment]
Haven't solved it yet.
But if this is an intended change I will be happy to solve it and send a PR.

**Comment by therajanmaurya** [comment]
Go ahead 👍

**Comment by nb2998** [comment]
@therajanmaurya @tarun0 Shall I send a PR for this?

**Comment by nb2998** [comment]
Please review #899

**Comment by laxyapahuja** [comment]
This issue seems to be solved in #899. Once #899 gets merged, this can be closed. @luckyman20
