### ISSUE TITLE
App crashes on menu item click of Path tracking activity.

### ISSUE THREAD

**Issue by sukhbir-singh** [openMF/android-client#569]
**Summary:** 

App crashes on menu item click of Path tracking activity. 

**Steps to reproduce:** 

Select Path tracking from Navigation drawer. Then click on menu item visible as box. 

**Expected behavior:** 

On click of menu item, app should remain stable and should open the desired activity.

**Observed behavior:** 

App crash happens.

**Device and Android version:** 

Motorola G-2 and Android 6.0 Marshmallow

**Comment by icancode23** [comment]
@sukhbir-singh can i work on this..?

**Comment by sukhbir-singh** [comment]
@icancode23 I have resolved this issue, will send PR very soon

**Comment by amogh-jrules** [comment]
@sukhbir-singh @icancode23  Actually, this issue was brought up before(#828). A pull request is available, but has not been confirmed. I have already asked to work on this.

**Comment by Aditya-gupta99** [comment]
This issue has been already resolved.
