### ISSUE TITLE
Unnessasary semi-colons present in certain Java files

### ISSUE THREAD

**Issue by AbhilashG97** [openMF/android-client#571]
**Summary:** 

Unnecessary semi-colons are present in certain Java files in the code base.

**Steps to reproduce:** 

Step 1) Go to analyze option in the main menu of Android Studio.
Step 2) Inspect code.
Step 3) Go to Code Style in inspection. 

**Expected behavior:** 

There shouldn't be any unnecessary semi-colons present in the code base. 

**Observed behavior:** 

There are unnecessary semi-colons present in the code base.

**Comment by AbhilashG97** [comment]
I would like to work on this issue.

**Comment by AbhilashG97** [comment]
Please review my pull request on this issue and kindly let me know if I have to make any further changes. 
Pull request - https://github.com/openMF/android-client/pull/572

**Comment by therajanmaurya** [comment]
fixed in #572
