### ISSUE TITLE
EditText hint text cannot be read fully

### ISSUE THREAD

**Issue by karsai1993** [openMF/android-client#578]
Summary:
In SearchFragment, the hint text of the EditText cannot be fully read when we come back from one of the create client/group/center fragments.

Steps to reproduce:
1, From SearchFragment, enter one of the create client/group/center fragments.
2, Press back button on your device.

Expected behavior:
The user should see the full see the whole hint text always to have an idea on what he/she can search.
Good solution is that the EditText gets the focus automatically always (by the help of requestFocus() method) when the user enters SearchFragment. In this way, the hint text would float up, so it becomes readable.

Observed behavior:
In SearchFragment, the hint text of the EditText cannot be fully read when we come back from one of the create client/group/center fragments because it does not get the focus automatically. As the activity is set to be in portrait mode in the manifest, the user has no change to read it fully by rotating the screen after coming back from one of the create fragments.

Device and Android version:
Samsung Ace 3
4.2.2 - API 17

Screenshots:
![device-2017-03-14-000304](https://cloud.githubusercontent.com/assets/15123875/23879011/de31e786-084a-11e7-9c20-f8e9a23ef271.png)

**Comment by karsai1993** [comment]
I have already implemented the solution. I am waiting for a review if I am allowed to commit and create the pull request.

**Comment by therajanmaurya** [comment]
Make sense. Go ahead and send PR.

**Comment by therajanmaurya** [comment]
fixed in #580
