### ISSUE TITLE
Unable to update Profile Photo of Client - Png image cannot be Clicked from a Camera

### ISSUE THREAD

**Issue by ramya257** [openMF/android-client#584]
**Summary:** 

The profile photo of the client cannot be updated after clicking the photo.

**Steps to reproduce:** 
On clicking the photo from camera the client profilephoto must get updated.

**Expected behavior:** 
On selecting "take photo" option and after clicking the pic the image of the client should get updated.
Steps-
1.On selecting the clicked photo the image should get uploaded in the background with proper notification about the progress of image uploading.
2. As initially only "click with camera" option is available and support for png files is provided in the code and as the user cannot click png files with camera "choose from gallery" option must be there.

**Observed behavior:** 
Image update fails with an error "Failed to update Image" 
Details-
On running the app,the log cat throws the following issue-
{"timestamp":1489528378024,"status":500,"error":"Internal Server Error","exception":"java.lang.IllegalArgumentException","message":"The bucket name parameter must be specified when uploading an object"}
this error occurs due to the support for png file and we are passing jpg file as parameter to the uploadImage function.

**Device and Android version:** 

Xiaomi Redmi Note 4 having Android  Marshmallow 6.0
![screenshot_2017-03-15-04-03-24-089_com mifos mifosxdroid](https://cloud.githubusercontent.com/assets/18115114/23925364/c859e522-0934-11e7-8c4a-b121a6097c42.png)

**Screenshots:**

**Comment by therajanmaurya** [comment]
It's working fine. I think the server was down when you were testing the app.
![image](https://cloud.githubusercontent.com/assets/5724482/24071549/d841c0ae-0bfa-11e7-9b10-fa5d5ac88992.png)

**Comment by sunny5125** [comment]
what about the choose option from gallery and notification generation for uploading picture.

**Comment by ramya257** [comment]
@sunny5125 i started working on this after  facing the above mentioned issue and due to some issues from server it was not working properly !

**Comment by sunny5125** [comment]
@ramya257  problem for uploading picture is working that's ok .
as u mentioned in **Expected behavior** (2) ,option from **choose from gallery** is not implemented so what about that ?

**Comment by ramya257** [comment]
@sunny5125
I m working on notification point and i have added choose from gallery option but there is also issue during image upload using the same API as for the earlier one and its creating problem as i don't know it's server side implementation !

**Comment by sunny5125** [comment]
@ramya257  BTW i have opened issue(feature) for choose from gallery option. as u have mentioned there is problem in choose from gallery option may i give a shot .
