### ISSUE TITLE
Dropdowns in Create Client don't feel like dropdowns

### ISSUE THREAD

**Issue by aj019** [openMF/android-client#591]
**Summary:** 

The dropdowns in create new client looks like textfield and don't feel clickable. A dropdown should be represented with a down arrow signifying a list.

**Steps to reproduce:** 

1) Open the app
2) From the navbar choose Clients
3) From the toolbar menu select and Create Client
4) Scroll down to Gender label
5) Below Gender you will find a dropdown list which doesn't feel like a dropdown

**Expected behavior:** 

Looking at the gender field. I expected it to be an edittext.

**Observed behavior:** 

But the field was actually a dropdown list

**Device and Android version:** 

Nexus 5 API 23

**Screenshots:** 

<img width="245" alt="screen shot 2017-03-17 at 6 51 53 am" src="https://cloud.githubusercontent.com/assets/7893859/24025258/6ae630e2-0adf-11e7-95dc-03e445a2b1bd.png">

**Comment by aj019** [comment]
I would like to work on this

**Comment by aj019** [comment]
I would suggest something like this

<img width="249" alt="screen shot 2017-03-17 at 7 06 36 am" src="https://cloud.githubusercontent.com/assets/7893859/24025447/635a7b52-0ae0-11e7-8eec-e9449ec5c6ad.png">

**Comment by aj019** [comment]
@therajanmaurya 
https://github.com/jaredrummler/material-spinner
How about this ?
Would you like me to implement this ?

**Comment by therajanmaurya** [comment]
@ishan1604 What you think.

**Comment by ishan1604** [comment]
@therajanmaurya I am good with the idea of having spinner. But @aj019 why do you think you want to add another library for this simple task ?

Why can't we do it with the default spinner android provides ?

**Comment by aj019** [comment]
@ishan1604 I am fine with the default spinners. The library was just a suggestion to make the UI better. The screenshot i suggested in the comment is the default spinner android provides that is how the spinner is going to look. Should i go ahead and work on it ?

**Comment by luckyman20** [comment]
@aj019 Are you still working on this?

**Comment by Aditya-gupta99** [comment]
Issue has been resolved.
