### ISSUE TITLE
Create Client option inside Create Client

### ISSUE THREAD

**Issue by aj019** [openMF/android-client#595]
**Summary:** 

Inside the Create Client Screen if we click on the toolbar menu. It shows Create client as one of the options. And when the user clicks on the Create Client option nothing happens.

**Steps to reproduce:** 

1) Open the app
2) From the navbar select clients
3) From the toolbar menu select Create Client
4) In Create client if you click on the toolbar menu you will get an option saying Create Client

**Expected behavior:** 

The Create client option inside Create client should either be invisible or should be have distinct colour depicting it to be disabled.

**Observed behavior:** 

When you click on the the Create Client option inside Create Client nothing happens.

**Device and Android version:** 

Nexus 5 API 23

**Screenshots:** 
<img width="247" alt="screen shot 2017-03-18 at 7 18 55 am" src="https://cloud.githubusercontent.com/assets/7893859/24068083/5a98d460-0bac-11e7-89cc-92e04ecdce85.png">

**Comment by therajanmaurya** [comment]
duplicate https://github.com/openMF/android-client/issues/526
