### ISSUE TITLE
Toast Message not correct

### ISSUE THREAD

**Issue by aj019** [openMF/android-client#596]
**Summary:** 

I entered a numeric value in the name field. On clicking submit a Toast appears with the message "Group Nameshould contain onlyALPHABETS" but instead it should be "Group Name should only  contain Alphabets"

**Steps to reproduce:** 

1) Open the app
2) From the nav bar select Groups
3) From the toolbar menu select Create Group
4) Inside the name field enter numeric value (eg : 123)
5) Fill other details and click on submit 

**Expected behavior:** 

Toast message should be "Group Name should only  contain Alphabets"

**Observed behavior:** 

On clicking submit a Toast appears with the message "Group Nameshould contain onlyALPHABETS"

**Device and Android version:** 

Nexus 5 API 23

**Screenshots:** 

<img width="192" alt="screen shot 2017-03-18 at 7 31 44 am" src="https://cloud.githubusercontent.com/assets/7893859/24068174/0134d8b8-0bae-11e7-85a4-84539b112d8c.png">

**Comment by aj019** [comment]
I would like to work on this issue.

**Comment by therajanmaurya** [comment]
Go ahead 👍

**Comment by laxyapahuja** [comment]
@luckyman20 i think this issue can be closed now.

**Comment by luckyman20** [comment]
Solved in #603
