### ISSUE TITLE
The progress bar in Datatables of both Clients and Groups loads endlessly.

### ISSUE THREAD

**Issue by AbhilashG97** [openMF/android-client#597]
**Summary:** 

The progress bar in Datatables of Clients and Groups loads endlessly. This issue is similar to https://github.com/openMF/android-client/issues/583. 

**Steps to reproduce:** 

Step 1) Select Clients or Groups from the navigation drawer.
Step 2) Select a Client or a Group from the list.
Step 3) Tap on the menu anchored to the overflow button at the top-right corner and select "More client info" or "More group info".
Step 4) Select a Datatable from the list.
Step 5) Go back to Datatables list. 

**Expected behavior:** 

The progress bar shouldn't load endlessly.

**Observed behavior:** 

The progress bar loads endlessly.

**Device and Android version:** 

Device : Motorola Moto G 1st Generation [XT1033] [Falcon]
ROM : CyanogenMod 13.0 Snapshot build

**Screenshots:** 

![screenshot_20170318-120800](https://cloud.githubusercontent.com/assets/20839661/24069692/d5060354-0bd3-11e7-97dc-3460b2e4be98.png)

![screenshot_20170318-120910](https://cloud.githubusercontent.com/assets/20839661/24069693/d507bdfc-0bd3-11e7-9d77-53caf203fb7d.png)

**Comment by AbhilashG97** [comment]
I would to like on work this issue.

**Comment by AbhilashG97** [comment]
I have rectified the issue, please review my pull request. 
Pull request - https://github.com/openMF/android-client/pull/629

**Comment by tarun0** [comment]
Fixed in https://github.com/openMF/android-client/pull/629
