### ISSUE TITLE
Questions in the survey are not being properly displayed.

### ISSUE THREAD

**Issue by AbhilashG97** [openMF/android-client#598]
**Summary:** 

Questions in the survey are not being properly is displayed. It is being partially cropped from the top.

**Steps to reproduce:** 

Step 1) Tap on Clients from the navigation drawer.
Step 2) Select a Client from the Client list.
Step 3) Tap on the menu anchored to the overflow button at the top-right corner and select Survey.
Step 4) Select a survey.

**Expected behavior:** 

The questions shouldn't be partially cropped from the top.

**Observed behavior:** 

The questions are partially cropped from the top.

**Device and Android version:** 

Device : Motorola Moto G 1st Generation [XT1033] [Falcon]
ROM : CyanogenMod 13.0 Snapshot build

**Screenshots:** 

The first line of the text is slightly cropped from the top.

![screenshot_20170318-125604](https://cloud.githubusercontent.com/assets/20839661/24070015/73acb0c4-0bda-11e7-80ef-5cd588523b34.png)

Here also the first line of the text is slightly cropped from the top.

![screenshot_20170318-125609](https://cloud.githubusercontent.com/assets/20839661/24070014/73ab86c2-0bda-11e7-8a9c-9915d5214c99.png)

**Comment by AbhilashG97** [comment]
I would like to work on this issue.

**Comment by therajanmaurya** [comment]
Go ahead 👍

**Comment by mayank-kgp** [comment]
@therajanmaurya @AbhilashG97 It is working fine on my phone. Can you please check again?

**Comment by AbhilashG97** [comment]
@mayank-kgp, the issue was resolved in [#600](https://github.com/openMF/android-client/pull/600).
