### ISSUE TITLE
Feature Choose from gallery option in profile photo of the client 

### ISSUE THREAD

**Issue by sunysaurav** [openMF/android-client#604]
**Summary:** 

The profile photo of the client can be updated choose from gallery option.

**Steps to reproduce:** 

Add option below take new photo and through file picker we can select image.
![screenshot_20170318-235920](https://cloud.githubusercontent.com/assets/10153038/24074873/6d319e32-0c37-11e7-8a7f-58cb5d0ad9ca.png)

**Comment by AkshGautam** [comment]
@therajanmaurya @tarun0  I would like to work on this.May i?

**Comment by tarun0** [comment]
I don't feel the field officer will have the images of clients on his device. He shouldn't have them anyway. If he has to take a new image, he should do that whenever he meets the clients. 

While this may seem a worthy feature for the self-service app, it doesn't make sense for the field-officer app.

**Comment by Aditya-gupta99** [comment]
The issue has already been resolved
