### ISSUE TITLE
Dialog doesn't close after it is successfully completed

### ISSUE THREAD

**Issue by aj019** [openMF/android-client#611]
**Summary:** 

The Add Charges dialog doesn't close and neither does it reset the fields after the charge is created successfully.

**Steps to reproduce:** 

1) Open app
2) Choose clients from nav bar
3) Select Any client
4) From the toolbar menu select Charges
5) Scroll through the items

**Expected behavior:** 

Either the dialog should close or the fields should reset so that the user can add another charges.

**Observed behavior:** 

There is a Toast that says "Charges created successfully" but neither does the dialog closes . Neither does it reset.  

**Device and Android version:** 

Nexus 5 API 23

**Screenshots:** 

![ezgif com-video-to-gif 2](https://cloud.githubusercontent.com/assets/7893859/24082167/fd2fe50c-0ce6-11e7-8d93-8861f80ed4e3.gif)

**Comment by chaitanyaparashar** [comment]
I would like to work on this issue

**Comment by chaitanyaparashar** [comment]
#627 please review it.

**Comment by Aditya-gupta99** [comment]
This issue has been resolved.
