### ISSUE TITLE
The Due Date field in the Charge Dialog Fragment displays both keyboard and calender to enter the date 

### ISSUE THREAD

**Issue by AbhilashG97** [openMF/android-client#614]
**Summary:** 

The Due Date field in the Charge Dialog Fragment displays both keyboard and calender to enter the date which makes it difficult to do the same.

**Steps to reproduce:** 

Step 1) Select Clients from the navigation drawer.
Step 2) Select a Client.
Step 3) Tap on the menu anchored to the overflow button at the top-right corner and select .
Step 4) Tap on "+" present at the top right corner.
Step 5) Tap on the due date field.

**Expected behavior:** 

It should display the calender to enter the date. 

**Observed behavior:** 

The dialog box displays both calender and keyboard to enter the date.

**Device and Android version:** 

Device : Motorola Moto G 1st Generation [XT1033] [Falcon]
ROM : CyanogenMod 13.0 Snapshot build

**GIF:** 

![videotogif_2017 03 19_23 11 25](https://cloud.githubusercontent.com/assets/20839661/24083285/4455c7fe-0cfa-11e7-9d5e-7d23350c9a49.gif)

**Comment by AbhilashG97** [comment]
I would like to work on this issue.

**Comment by AbhilashG97** [comment]
Please review my pull request, and kindly let me know if I have to make any further changes.

**Comment by therajanmaurya** [comment]
Fixed in https://github.com/openMF/android-client/pull/619
