### ISSUE TITLE
App Crashes while creating new client by clicking on submit ,when not connected to internet(Offline)

### ISSUE THREAD

**Issue by rohitsroch** [openMF/android-client#625]
**Summary:** 
 
The Application crashes when the user click on  submit button while creating new client.(when not connected to internet)-offline 

**Steps to reproduce:** 
Step 1) Make sure you are  offline (not connected to internet).
Step 1) Tap on Clients from the navigation drawer.
Step 2) Tap on Floating Action Button to create new client.
Step 3) Tap on submit button.

**Expected behavior:** 

The application shouldn't crash and should show a toast message same as in online mode.

**Observed behavior:** 

The Application crashes when the user click on submit button (Offline).

**Device and Android version:** 

Samsung Galaxy Core-2 Kitkat(4.4.2)
API Level 19

**GIF:**
![imageedit_1_8132851969](https://cloud.githubusercontent.com/assets/24658811/24123590/2617bc4c-0de6-11e7-97d3-4bab6b0abc7a.gif)

**Comment by rdeveloperIITR** [comment]
I would like to work on this issue :)
