### ISSUE TITLE
Overlapping of failed message icon with path tracking details in recyclerview ,while refreshing (when not connected to internet)

### ISSUE THREAD

**Issue by rdeveloperIITR** [openMF/android-client#641]
**Summary:** 

In pathTrackActivity ,Overlapping of failed message icon occurs with path tracking details content of recylerview ,when not connected to internet.

**Steps to reproduce:** 

Step 1) Make sure you are connected to internet.
Step 1) Tap on Path Track  from the navigation drawer (it will show path tracking details in recylerview)
Step 2) Now disconnect to internet
Step 3) Refresh by using swipeRefreshLayout on swiping from top to down
Step 4) Overlapping of failed message icon occurs with recylerview content

**Expected behavior:** 

On refresh by using swipeRefreshLayout, only failed message icon should be shown without any recylerview content.

**Observed behavior:** 

On refresh by using swipeRefreshLayout, overlapping of failed message icon occurs with path tracking details content of recylerview, when not connected to internet.

**Device and Android version:** 

Samsung Galaxy Core-2 Kitkat(4.4.2)
API Level 19

**GIF:** 

![video25](https://cloud.githubusercontent.com/assets/24658811/24528620/fea11e56-15c4-11e7-94d2-86f801e1977e.gif)

**Comment by rdeveloperIITR** [comment]
I would like to work on this issue :)

**Comment by therajanmaurya** [comment]
Continue here #702
