### ISSUE TITLE
No required field message when uploading document

### ISSUE THREAD

**Issue by aj019** [openMF/android-client#646]
**Summary:** 

In the Upload document dialog when the fields are empty and the user clicks on Upload button then the app should display required field error but instead nothing happens.

**Steps to reproduce:** 

Open the app
Go to Navbar and select Clients
Select Client
From the Toolbar menu select Document
In the toolbar menu select '+' icon
Click on upload button

**Expected behavior:** 

The app should display a message that the fields are empty 

**Observed behavior:** 

On clicking the upload button nothing happens.

**Device and Android version:** 

Nexus 5 API 23

**Screenshots:** 

In this GIF i am actually clicking on the upload button but since nothing happens you don't see anything in the gif below.

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/7893859/24550649/a9eefeaa-163c-11e7-86ca-4957e319b530.gif)

**Comment by aj019** [comment]
I would like to work on this

**Comment by aj019** [comment]
@therajanmaurya So i looked at the code and the reason there is no action on clicking the button is because it is disabled till a document is uploaded but according to me the Message that the Name and desc is required should come before the document is uploaded.

So there are two options
1) Enable the button and display required field error messages.
2) Change colour of Upload button on being disble so that atleast the user know the button is disabled.

What would you suggest. I prefer the first one.

**Comment by iml-v** [comment]
@tarun0 I would like to work on this issue #646.

**Comment by nb2998** [comment]
@iml-v Are you working on this issue?

**Comment by nb2998** [comment]
@tarun0 @therajanmaurya I would like to work on this issue as nobody seems to be working on this.

**Comment by tarun0** [comment]
@iml-v If you are working or have worked on it, comment here. @nb2998 You may work if he/she doesn't reply within next 4 days.

**Comment by iml-v** [comment]
@tarun0  Sorry for late reply ,my exams were ongoing so I was busy @nb2998 I haven't started yet you can work on this .
