### ISSUE TITLE
Created identifier not visible after creation

### ISSUE THREAD

**Issue by aj019** [openMF/android-client#648]
**Summary:** 

When the user creates an identifier a Toast message appears saying that "Identifier created successfully but the created identifier is not visible to the user.

**Steps to reproduce:** 

Open the app
Go to Navbar and select Clients
Select Client with 0 identifiers
From the Toolbar menu select Identifiers
In the toolbar menu select '+' icon
Fill the details 
Click on Create Identifier

**Expected behavior:** 

The identifier created should be visible to the user immediately.

**Observed behavior:** 

On clicking Create Identifier a Toast message appears saying that "Identifier created successfully but the created identifier is not visible to the user.

**Device and Android version:** 

Nexus 5 API 23

**Screenshots:** 
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/7893859/24551028/763efbd0-163e-11e7-8a88-6c8c6d0d3d1c.gif)

**Comment by aj019** [comment]
I would like to work on this issue

**Comment by mayank-kgp** [comment]
@aj019 Are you still working on it?

**Comment by therajanmaurya** [comment]
fix in #769
