### ISSUE TITLE
Wrong Toolbar title in Survey List

### ISSUE THREAD

**Issue by aj019** [openMF/android-client#652]
**Summary:** 

The toolbar in surveys should have a title "Survey List" 

**Steps to reproduce:** 

Open app
From navbar select Clients
Select any Client
From the toolbar menu select Survey

**Expected behavior:** 

The toolbar in survey list should have a title "Survey List" 

**Observed behavior:** 

The toolbar title says "Client - Client Name"

**Device and Android version:** 

Nexus 5 API 23

**Screenshots:** 

<img width="246" alt="screen shot 2017-04-01 at 2 24 29 pm" src="https://cloud.githubusercontent.com/assets/7893859/24577198/f87fe746-16e6-11e7-8c41-b049d926fbde.png">

**Comment by aj019** [comment]
I am working on this issue

**Comment by mayank-kgp** [comment]
@therajanmaurya @puneetkohli521 @tarun0 What should be the correct title?

**Comment by tarun0** [comment]
In my opinion, it can be something like `Client <LastName> - Surveys`.

**Comment by Prem0707** [comment]
@therajanmaurya Is it necessary to correct this one as suggested by @tarun0 ? If yes, can i work on this?

**Comment by Prem0707** [comment]
@tarun0 @luckyman20 @therajanmaurya can i work on this? Thanks

**Comment by imRishN** [comment]
@Prem0707 are you working on this?
If not, @tarun0 @therajanmaurya @luckyman20 I would like to work on this.

**Comment by luckyman20** [comment]
@aj019 Are you working on this? As you commented first on this issue to work

**Comment by Prem0707** [comment]
@imRishN I am waiting for the mentor approval for this issue since @aj019 was already working on this ( as said by him). @luckyman20 It has been a long time since when @aj019 was working on this ( almost a year ). Now, If @aj019 is not working on this, I would like to work on this. Thanks
