### ISSUE TITLE
Identifier item still visible after deleting it

### ISSUE THREAD

**Issue by aj019** [openMF/android-client#658]
**Summary:** 

When there is only one identifier left and user deletes it we get a message saying "Identifier deleted successfully" but the identifier item is still visible.

**Steps to reproduce:** 

OPen app
Select Clients from Navbar
Select Client with only one identifier
From toolbar menu select Identifiers
Delete the identifier

**Expected behavior:** 

On deleting the identifier the identifier shouldn't be visible .

**Observed behavior:** 

The identifier is still visible on deleting it.

**Device and Android version:** 

Nexus 5 API 23

**Screenshots:** 

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/7893859/24690917/c811f612-19ed-11e7-92d4-939023257691.gif)

**Comment by therajanmaurya** [comment]
Go ahead

**Comment by mayank-kgp** [comment]
@aj019 I would like to add one more point. If you add an identifier, it is not visible after adding.
Are you still working on it?
If not, I would like to work on it.
@therajanmaurya pinged.
