### ISSUE TITLE
Snackbar with no text is displayed when the user loses Internet connectivity in the Add Savings Account Fragment  

### ISSUE THREAD

**Issue by AbhilashG97** [openMF/android-client#661]
**Summary:** 

Snackbar with no text is displayed when the user loses Internet connectivity in the Add Savings Account Fragment. The user should instead get a suitable message stating the loss of Internet connectivity.  

**Steps to reproduce:** 

Step 1) Open the app.
Step 2) Tap on the Clients fragment from the navigation drawer.
Step 3) Select a Client.
Step 4) Tap on the menu and select Add Savings Account.
Step 5) Disable data connection.
Step 6) Tap on Submit.

**Expected behavior:** 

The user should get a suitable message stating the loss of Internet connectivity.

**Observed behavior:** 

The user sees a blank message in the Snackbar.

**Device and Android version:** 

Device : Motorola Moto G 1st Generation [XT1033] [Falcon]
ROM : CyanogenMod 13.0 Snapshot build

**GIF:** 

![videotogif_2017 04 06_11 45 11](https://cloud.githubusercontent.com/assets/20839661/24740483/1328570a-1abf-11e7-90e2-fc066dd82407.gif)

**Comment by AbhilashG97** [comment]
I would like to work on this issue.

**Comment by AbhilashG97** [comment]
I have made the required changes, please review my pull request and kindly let me know if I have to make any further changes.
Pull request - https://github.com/openMF/android-client/pull/669

**Comment by therajanmaurya** [comment]
fix in #669
