### ISSUE TITLE
Amount field in Savings Account Transaction Fragment accepts zero (0) as amount

### ISSUE THREAD

**Issue by AbhilashG97** [openMF/android-client#663]
**Summary:** 

Savings Account Transaction Fragment accepts zero (0) in the "Amount" field. The field displays a error message when the field is blank but doesn't show any error message when user enters zero in the "Amount" field. 

**Steps to reproduce:** 

Step 1) Open the app.
Step 2) Tap on the Clients fragment from the navigation drawer.
Step 3) Select a Client.
Step 4) Tap on Savings Accounts and select a savings account.
Step 5) Tap on "Make Withdrawal" or "Make Deposit".
Step 6) Enter zero in the "Amount" field.
Step 6) Tap on "Review Payment".

**Expected behavior:** 

The user should get an error message stating that the "Amount" field cannot accept zero on tapping the "Review Transaction" button.

**Observed behavior:** 

Presently, on tapping the "Review Transaction" button, the user gets to see "Review Payment Details" dialog and on clicking "Process Transaction", the user is greeted with an error message stating "Transaction Failed" which is the result of entering zero in the amount field.  

**Device and Android version:** 

Device : Motorola Moto G 1st Generation [XT1033] [Falcon]
ROM : CyanogenMod 13.0 Snapshot build

**GIF:** 

![videotogif_2017 04 06_13 25 00](https://cloud.githubusercontent.com/assets/20839661/24744208/c557ddec-1ace-11e7-94a5-e5ca3492368a.gif)

**Comment by AbhilashG97** [comment]
I would like to work on this issue.

**Comment by AbhilashG97** [comment]
I have made the appropriate changes, kindly review my pull request and please let me know if I have to make any further changes.

**Comment by therajanmaurya** [comment]
fix in #664
