### ISSUE TITLE
Loan gets approved in spite of "Approved Amount" and "Transaction Amount" field being blank

### ISSUE THREAD

**Issue by AbhilashG97** [openMF/android-client#666]
**Summary:** 

Loan gets approved in spite of "Approved Amount" and "Transaction Amount" field being blank. An appropriate response like a toast message stating that the field cannot be blank would be suitable.

**Steps to reproduce:** 

Step 1) Open the app.
Step 2) Tap on the Clients fragment from the navigation drawer.
Step 3) Select a Client.
Step 4) Tap on Loan Accounts and select an account in which a loan needs to be approved.
Step 5) Tap on "Approve Loan" button.
Step 6) Leave the "Approved Amount" and "Transaction Amount" field empty.
Step 6) Tap on Submit.

**Expected behavior:** 

The loan shouldn't get approved and an appropriate error message should notify the user about the blank fields. 

**Observed behavior:** 

The loan gets approved in spite of the "Approved Amount" and "Transaction Amount" field being blank.

**Device and Android version:** 

Device : Motorola Moto G 1st Generation [XT1033] [Falcon]
ROM : CyanogenMod 13.0 Snapshot build

**GIF:** 

![videotogif_2017 04 08_18 41 23](https://cloud.githubusercontent.com/assets/20839661/24829375/dee3aac8-1c8d-11e7-9bf0-c1c40592e23e.gif)

**Comment by AbhilashG97** [comment]
I would like to work on this issue.

**Comment by AbhilashG97** [comment]
I have made appropriate changes, please review my pull request and kindly let me know if I have to make any further changes. 
Pull request - https://github.com/openMF/android-client/pull/668

**Comment by therajanmaurya** [comment]
fix in #668
