### ISSUE TITLE
Remove system generated file 

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/android-client#670]
Remove the system generated file `studio_android-client.iml`.

**Comment by tarun0** [comment]
Why is this labelled as 'Help Wanted'?

**Comment by therajanmaurya** [comment]
I want to someone to remove this file from git and send PR.

On 19-Apr-2017 5:35 PM, "Tarun Mudgal" <notifications@github.com> wrote:

Why is this labelled as 'Help Wanted'?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openMF/android-client/issues/670#issuecomment-295241375>,
or mute the thread

**Comment by AbhilashG97** [comment]
@therajanmaurya, I would like to send the PR.

**Comment by AbhilashG97** [comment]
@therajanmaurya, Here is the PR - https://github.com/openMF/android-client/pull/672. Please let me know if I have to make any further changes.
