### ISSUE TITLE
Empty toast message is displayed when the user taps the 'Save' button while there is no internet connection in the savings account approval fragment

### ISSUE THREAD

**Issue by AbhilashG97** [openMF/android-client#674]
**Summary:** 

Empty toast message is displayed when the user taps the 'Save ' button while there is no Internet connection in the savings account approval fragment. A suitable toast message stating that there is no Internet connection would be a better response.   

**Steps to reproduce:** 

Step 1) Open the app.
Step 2) Tap on Clients from the navigation drawer.
Step 3) Select a client.
Step 4) Tap on Savings Accounts and select an account that requires to approve savings.
Step 4) Tap on "Approve Savings button".
Step 5) Disable Internet connection.
Step 6) Tap on "Save" button.  

**Expected behavior:** 

We should see a toast message stating that there is no Internet connection.

**Observed behavior:** 

A blank toast message is displayed.

**Device and Android version:** 

Device : Motorola Moto G 1st Generation [XT1033] [Falcon]
ROM : CyanogenMod 13.0 Snapshot build

**GIF:** 

![videotogif_2017 04 19_21 54 55](https://cloud.githubusercontent.com/assets/20839661/25211409/c355c41c-25a2-11e7-9f81-2efe744a79c4.gif)

**Comment by AbhilashG97** [comment]
I would like to work on this issue.

**Comment by AbhilashG97** [comment]
I have made the required changes, please review my pull request and kindly let me know if I have to make any further changes. 
Pull request - https://github.com/openMF/android-client/pull/676

**Comment by therajanmaurya** [comment]
fix in #676
