### ISSUE TITLE
Unable to Create Client

### ISSUE THREAD

**Issue by santoshmath** [openMF/android-client#678]
It is throwing the error 'The parameter datatables cannot be empty. You must select at least one'. 

![d3](https://cloud.githubusercontent.com/assets/23022667/25327136/a0ac704a-28f0-11e7-98d6-e938173e0578.png)

**Comment by AbhilashG97** [comment]
May I work on this issue ?

**Comment by AbhilashG97** [comment]
The logs for the issue can be found [here](https://gist.github.com/AbhilashG97/48245a79de3557d556e86a84b33a7ab9).

**Comment by santoshmath** [comment]
@AbhilashG97 Are you able to resolve this issue?

**Comment by AbhilashG97** [comment]
@santoshmath, Unfortunately, I haven't been able to resolve this issue, but I am trying to fix it as soon as possible. From the logs I was able to understand that the issue was being caused due to sending empty parameters in datatables field of the create client POST method. An example of a correct POST method for the create client should be somewhat like this- 

**POST clients**
Content-Type: application/json Request Body:
{
	"officeId": 1,
	"firstname": "Petra",
	"lastname": "Yton",
	"externalId": "786YYH7",
	"dateFormat": "dd MMMM yyyy",
	"locale": "en",
	"active": true,
	"activationDate": "04 March 2009",
    "submittedOnDate":"04 March 2009",
    "savingsProductId" : 4,
    "datatables": [**{
        "registeredTableName": "Family Details",
        "data": {
        "locale": "en",
        "Number of members": "5",
        "Number of dependents": "3",
        "No of Children": "2",
        "Date of verification": "14 December 2016",
        "dateFormat": "dd MMMM yyyy"
        }
    },
    {
        "registeredTableName": "Residency Address",
        "data": {
        "locale": "en",
        "Address Line": "Basavana Gudi Road",
        "Street": "Gandhi Bazaar",
        "Landmark": "Aashrama",
        "COUNTRY_cd_Country": 17,
        "STATE_cd_State": "7",
        "DISTRICT_cd_District": "13",
        "Pincode": "560040"
        }
    }**]
}   
As of now, the POST method doesn't contain these parameter values (bold text) due to which we end up getting the "400 Bad Request" error message. This seems to be the root cause of the issue and I'm trying to resolve it. 
I also wouldn't mind if someone else posts a pull request with the solution for this issue, as I might end up taking some time to come up with a fix.

**Comment by AbhilashG97** [comment]
@santoshmath, Unfortunately, I haven't been to resolve this issue yet, but I am trying to resolve it as soon as possible. From what I have understood as of now is that the datatables field is being left empty which results in "400 Bad Request" error when the POST request is sent.  The correct POST request should look somewhat like this - 

Content-Type: application/json Request Body:
{
	"officeId": 1,
	"firstname": "Petra",
	"lastname": "Yton",
	"externalId": "786YYH7",
	"dateFormat": "dd MMMM yyyy",
	"locale": "en",
	"active": true,
	"activationDate": "04 March 2009",
    "submittedOnDate":"04 March 2009",
    "savingsProductId" : 4,
    "datatables": [**{
        "registeredTableName": "Family Details",
        "data": {
        "locale": "en",
        "Number of members": "5",
        "Number of dependents": "3",
        "No of Children": "2",
        "Date of verification": "14 December 2016",
        "dateFormat": "dd MMMM yyyy"
        }
    },
    {
        "registeredTableName": "Residency Address",
        "data": {
        "locale": "en",
        "Address Line": "Basavana Gudi Road",
        "Street": "Gandhi Bazaar",
        "Landmark": "Aashrama",
        "COUNTRY_cd_Country": 17,
        "STATE_cd_State": "7",
        "DISTRICT_cd_District": "13",
        "Pincode": "560040"
        }
    }**]
}
Currently, the POST request is missing the value for the datatables parameter (bold text) which results in an error. I am trying resolve this issue as soon as possible. 
Also, meanwhile if someone else desires to work on this issue and post a solution they may do so.

**Comment by santoshmath** [comment]
@AbhilashG97 ,  wait few  days. @therajanmaurya , will look into this.

**Comment by tarun0** [comment]
@santoshmath I'll work on this.
