### ISSUE TITLE
Activating Savings Account is not expecting date.

### ISSUE THREAD

**Issue by santoshmath** [openMF/android-client#679]
Through Android app, you can provide, Submit Date, Approve Date for Savings account. While Activating savings account , it won't expect any date and gets activated with just one click

**Comment by tarun0** [comment]
@santoshmath Could you please elaborate it?

**Comment by santoshmath** [comment]
@tarun0 , try to create savings account for a client using savings product in andriod app. During submit, approve it asks for date . But it doesn't ask for date while activation. But in web-app, activation date is compulsory.

**Comment by tarun0** [comment]
@santoshmath Could you please confirm if I understood it correct? In the web-app, I opened a client say, _GrahamAdrian Clark_. Clicked _Add Savings_ from the menu. But I can't find any activation date option.

![save](https://cloud.githubusercontent.com/assets/12914286/26628862/6a3d4792-461d-11e7-830e-e3a18ea1de36.jpg)

**Comment by santoshmath** [comment]
@tarun0 , first you submit it. On next page approve it providing date and on next page Activate it. When you try to activate it , it asks  for the  date. Same is not happening on app.

**Comment by tarun0** [comment]
Got you.

**Comment by mayank-kgp** [comment]
@tarun0 Are you working on it?

**Comment by tarun0** [comment]
@mayank-kgp Yes, I've sent a PR for the same.
