### ISSUE TITLE
Empty Snackbar is displyed on tapping "Submit" button in the Disburse Loan Dialog fragment in the absence of Internet connection

### ISSUE THREAD

**Issue by AbhilashG97** [openMF/android-client#680]
**Summary:** 

Empty Snackbar is displyed on tapping "Submit" button in the Disburse Loan Dialog fragment while there is no Internet connection. A suitable response would be to have a Snackbar displaying a message stating that there is no Internet connection.

**Steps to reproduce:** 

Step 1) Open the app.
Step 2) Tap on the Clients fragment from the navigation drawer.
Step 3) Select a Client.
Step 4) Tap on Loan Accounts and select an account which can disburse a loan.
Step 5) Tap on Disburse Loan.
Step 6) Disable Internet connection.
Step 6) Tap on Submit.

**Expected behavior:** 

A Snackbar stating that there is no Internet connection should be displayed.

**Observed behavior:** 

An empty Snackbar is displayed.

**Device and Android version:** 

Device : Motorola Moto G 1st Generation [XT1033] [Falcon]
ROM : CyanogenMod 13.0 Snapshot build

**GIF:** 

![videotogif_2017 04 25_18 23 44](https://cloud.githubusercontent.com/assets/20839661/25393162/61418b76-29f8-11e7-8f94-d4f0e79978d8.gif)

**Comment by AbhilashG97** [comment]
I would like to work on this issue.

**Comment by AbhilashG97** [comment]
I have made the required changes, please review my pull request and kindly let me know if I have to make any further changes.
Pull request - https://github.com/openMF/android-client/pull/681

**Comment by therajanmaurya** [comment]
fix in #681
