### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by ajinkyagadewar** [openMF/android-client#686]
**Summary:** 

For any screen relation to create, edit or delete, app is showing "Failed to fetch template". For example, for new client creation "Failed to fetch clientTemplate"

**Steps to reproduce:** 
1. Click on the Create New Client in Hamburger menu
2. Lot of fields does not come up like Gender

**Expected behavior:** 
All of the fields should load up

**Observed behavior:** 

Lot of fields does not come up like Gender

**Device and Android version:** 

Lenovo P2

**Screenshots:** 

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by ajinkyagadewar** [comment]
In the logs, I can see: Table 'mifostenant-default.m_entity_datatable_check' doesn't exist

As of now I am working on demo data of mifos.

**Comment by therajanmaurya** [comment]
@tarun0 can you please look.

**Comment by tarun0** [comment]
@therajanmaurya Sure, I'm on it.

**Comment by tarun0** [comment]
@therajanmaurya  It's working fine now.

**Comment by mayank-kgp** [comment]
@therajanmaurya @tarun0 @ajinkyagadewar It is working fine.

**Comment by Aditya-gupta99** [comment]
The issue has already been resolved
