### ISSUE TITLE
Loan Term only takes number and doesn't mention whether it's days or months or weeks

### ISSUE THREAD

**Issue by santoshmath** [openMF/android-client#692]
1. Open any client page on android app 
2. Tap on right top corner button and tap on add loan account. 
3. On next page(add loan account page), you can only mention loan term in numbers but not in days or months or years. 
> Check the screenshot

![loanterm](https://user-images.githubusercontent.com/23022667/26914632-065161b8-4c40-11e7-90b4-51db83a98f81.png)

**Comment by tarun0** [comment]
@therajanmaurya  I'll take it

**Comment by tarun0** [comment]
@santoshmath The LoanTermFrequencyType and the RepaymentFrequencyType should be the same. I've implemented it in the way that change in one dropdown will make the corresponding change in the other as well. 
Please have a look at the GIF in the PR's comment and let me know if that's an acceptable approach.
@therajanmaurya Please review the same.
