### ISSUE TITLE
New feature of 4 digit pin

### ISSUE THREAD

**Issue by mayank-kgp** [openMF/android-client#697]
**Summary:** 
I am proposing a new activity called "Quick Login Activity" for creating 4 digit pin. This pin will be used in place of the regular password for login.
The process of login will be like this - 

First, Existence of quick pin will be checked from shared preference in the SplashScreenActivity.
 
- If it doesn't exist then app will navigate to LoginActivity - 
                                                                             User will enter username and password. If it is correct then user will navigate to QuickLoginAcitivity. Here, user can enter 4 digit pin and that pin will be sent to c++ library for encryption. That library will return encrypted pin and that encrypted pin will be stored in the shared preference.

- If it exist then app will navigate to QuickLoginAcitivity. User will enter the 4 digit pin and that pin will be matched by decrypted version of shared preference pin. If it matches, user can successfully enter the app.

**Comment by tarun0** [comment]
I'm adding my opinion to it. Although logging using PIN will remove the hassle of entering username and password, won't it be better that we authenticate the user _only_ while performing sensitive tasks? For example, while creating a new loan, the Create_New_Loan activity will show up only if the user enters correct PIN.

**Comment by mayank-kgp** [comment]
@puneetkohli521 @droidchef @therajanmaurya What do you think about it?

**Comment by therajanmaurya** [comment]
@mayank-kgp your approach looks good, Go ahead 👍.

@tarun0 Yes we will implement that you are talking, Let first @mayank-kgp implement the PIN feature then we will use this feature to authenticate others.
