### ISSUE TITLE
Add offline support at center level

### ISSUE THREAD

**Issue by mayank-kgp** [openMF/android-client#711]
**Summary:** 

Add offline support at center level

**Comment by edcable** [comment]
@mayank-kgp I know that this is how it was currently in the app but can you fix the grammar on the successful completion message. It currently says "all centers have been sync".

It should read "all centers have been synced".

Thanks!

**Comment by mayank-kgp** [comment]
@edcable Thanks for pointing out mistake.
I will do it.

**Comment by edcable** [comment]
You can probably fix it in the other places too - groups and clients :)
