### ISSUE TITLE
Mifosxdroid unable to setup daily loan repayment schedule

### ISSUE THREAD

**Issue by datadve** [openMF/android-client#726]
While setting up a loan, the Mobile App by default can only set loan repayment schedule to monthly or can be toggled to yearly, so one is unable to make repayment schedule daily except from the community App/server, where modify loan and change the term and repayment frequency to daily.

The mobile Apps needs to have the option of setting up loan for daily repayment.

**Comment by therajanmaurya** [comment]
@datadve thanks for reporting, I went through the [code](https://github.com/openMF/android-client/blob/master/mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccount/LoanAccountFragment.java#L276) and found that we are adding the default value of [InterestRateFrequencyType](https://github.com/openMF/android-client/blob/master/mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccount/LoanAccountFragment.java#L721)
that's have default value 
```
 "interestRateFrequencyType": {
    "id": 3,
    "code": "interestRateFrequency.periodFrequencyType.years",
    "value": "Per year"
  }
```
Per year, So I am going to add a Spinner that will bring you an option to select repayment frequency
1. Daily
2. Monthly
3 . Yearly 

Is it sound good for you?

**Comment by datadve** [comment]
Thanks @therajanmaurya
