### ISSUE TITLE
No option to toggle password visibility 

### ISSUE THREAD

**Issue by nikit19** [openMF/android-client#760]
**Summary:** 

There should be a show password icon in the password EditText.

**Steps to reproduce:** 

Just open the app.You will see the login screen.

**Expected behavior:** 

I expected a show password icon in the password EditText to toggle password visibility.

**Observed behavior:** 

There is no show password icon in the login activity

**Device and Android version:** 

This problem was encountered on Moto G4+ and the android version is 7.0.It is the stock version from the manufacturer.

**Screenshots:** 
Before
![screenshot_20170813-140552](https://user-images.githubusercontent.com/20878145/29248311-935d5186-8032-11e7-9491-c4a688f238ae.png)

After
![screenshot_20170813-140641](https://user-images.githubusercontent.com/20878145/29248315-a09bb144-8032-11e7-914a-9c578100ef3a.png)

**Comment by therajanmaurya** [comment]
Hi @nikit19, Welcome to the community. Thanks for reporting the issue. If you wanna fix the issue go ahead, we are no longer supporting this layout and want to change the whole layout, check out this issue #748.

Feel free to send PR 🙂

**Comment by nikit19** [comment]
Hi @therajanmaurya ,I hope my PR fixes issue #748 and this one.
Thank you.
