### ISSUE TITLE
Issues in client identifiers

### ISSUE THREAD

**Issue by mayank-kgp** [openMF/android-client#768]
**Summary:** 

There are 3 issues in client identifiers which need to be resolved.
1. This is already reported. Please see #648 
2. If there is only one item in identifier list, then it is visible even after removing it. Please see the GIF -
![issue2](https://user-images.githubusercontent.com/11210887/29399144-a83bb15e-8345-11e7-957e-583d15f3c249.gif)

3. If there is no item in identifier list, then the message is shown that "There is no identifier to show". But this error is visible even after a new identifier is added. Please see the GIF - 
![issue3](https://user-images.githubusercontent.com/11210887/29399218-f678567e-8345-11e7-9583-c1f5a5f0a7d2.gif)   

**Steps to reproduce:** 

Open the app
Go to Navbar and select Clients
Select Client
From the Toolbar menu select Identifiers

**Comment by tarun0** [comment]
#743 Addresses this too. :)
