### ISSUE TITLE
Client Name is displayed as null if Client Type is "ENTITY"

### ISSUE THREAD

**Issue by Ippezrobert** [openMF/android-client#774]
![image](https://user-images.githubusercontent.com/13125234/29664391-14f0deb8-88d8-11e7-8a29-c26c7aca1cbe.png)

**Comment by srv-twry** [comment]
@edcable Can i work on it if it's available ?

**Comment by Prem0707** [comment]
@therajanmaurya I would like to work on this issue. It would be great if you can assign it to me. Thanks :)

**Comment by therajanmaurya** [comment]
@Prem0707 Yeah sure go ahead and send PR.

**Comment by AkshGautam** [comment]
@Prem0707 are you still working on it?

**Comment by Prem0707** [comment]
Yes,I am. I am little stuck with code base.

**Comment by AkshGautam** [comment]
@Prem0707 if you feel stuck you can ask for help over gitter channel.if you have stopped working on this then @tarun0 @therajanmaurya  I would like to do this.

**Comment by Prem0707** [comment]
@akshGautam I am already in halfway of PR, most probably I will send it by Sunday evening. I will let you know if I wouldn't be able to resolve this issue. Thanks :)

**Comment by AkshGautam** [comment]
@Prem0707 Glad to hear this. You can take your time if you are close to solving it.If you feel stuck, we can solve it together. Take your time, No hurry.

**Comment by Prem0707** [comment]
@therajanmaurya @tarun0 @luckyman20 I can see some of the entries as null but i am unable to reproduce it by myself openMF/android-client#774
It would be great if can get any leads regarding that. Thanks

**Comment by AkshGautam** [comment]
@tarun0 @therajanmaurya  I would like to try this task.

**Comment by Prem0707** [comment]
@luckyman20 I am not able to resolve the issue inspite of spending so much time on it, @AkshGautam if you want work on it Please comment once for mentor approval. Thanks

**Comment by AkshGautam** [comment]
@tarun0 @therajanmaurya  I would like to try this task.
