### ISSUE TITLE
No status Indicator for Group and Client Listing

### ISSUE THREAD

**Issue by fboniphace** [openMF/android-client#777]
Hello Devs.
I've noticed in the App there is no status Indicator for Group and Client Listing showing their status like Active/Pending or Closed like on Centres listing.
Thanks

**Comment by luckyman000786** [comment]
@naman14 @therajanmaurya  Can I work on this issue ?

**Comment by sashank27** [comment]
@fboniphace @edcable could you please elaborate more on the issue?

**Comment by apoorvinfo** [comment]
@fboniphace  Can you tell me on which basis we will decide about the status of groups and clients?

**Comment by AkshGautam** [comment]
@therajanmaurya @tarun0  I would like to work on this. #865  is more descriptive for this issue.
