### ISSUE TITLE
Log out button not working

### ISSUE THREAD

**Issue by AkshGautam** [openMF/android-client#787]
**Summary:** 
Log out button not working as expected
**Steps to reproduce:** 
Click the log out button from the options menu.
**Expected behavior:** 

App should log out.

**Observed behavior:** 

App not logging out,same screen reappears after entering password.

**Video Link**

[video](https://drive.google.com/file/d/1stqY66hnuECYqA4yxS-ha9XUeWGq1HZP/view?usp=sharing)

If someone else could acknowledge the behaviour shown by the app,I would like to give it a try to debug this. Thanks

**Comment by AkshGautam** [comment]
@therajanmaurya @edcable @dilpreet96  can someone acknowledge about the same behaviour?

**Comment by tarun0** [comment]
It seems that the user can still log in using the Passcode even after clicking Logout button. A better flow would be to make it mandatory for the user to log in using password after clicking on the 'Logout' from the options menu.

@AkshGautam You may work on it.

**Comment by AkshGautam** [comment]
@tarun0 this task is done. I have made the required changes, User now has to enter 4 pin passcode confirming to logout, upon logout he is redirected to the login page for new session.Should I make a PR or anything else need to be done?

**Comment by tarun0** [comment]
Why is the user required to provide the PIN to Logout? 

Yes, you should send PR when you feel you have fixed the issue. Also, add a GIF to show the changes so that it may be easier for the reviewers to have the glimpse of the fix.

You'll be given feedback on the PR itself.

**Comment by AkshGautam** [comment]
@tarun0 That's what i thought there is no need of PIN to logout but prior to working on the logout button the application asked PIN during logout. I was not sure whether to remove that or not.If you feel having asking PIN is not necessary,i would make changes. Please confirm should i remove the PIN before logout option or not? Thanks

**Comment by tarun0** [comment]
What you perceived as a feature is actually a bug. It most probably is the reason why the bug arose; i.e. when one logs out, the home activity is finished which leads to popping the most recent activity (the passcode activity) from the backstack. 

You have to make sure that the Passcode Activity doesn't exist in backstack once it opens the Home screen (Dashboard activity) and that the passcode is removed when one clicks Log Out. That way, when the user will log out, he'll not be shown the passcode activity and he'll be left with no other option than to log in again using username and password.

**Comment by AkshGautam** [comment]
@tarun0 This is the [https://drive.google.com/file/d/1ERdPi-Q11OcErnnep5SHycU1wHuUB2p3/view?usp=sharing](GIF) to the app after making changes.I will make a PR now.

**Comment by AkshGautam** [comment]
PR #790
