### ISSUE TITLE
invalid toast message in GenerateCollectionSheet

### ISSUE THREAD

**Issue by himanshu112** [openMF/android-client#791]
**Summary:** 

**Steps to reproduce:** 
1.Go to collection sheet from navigation menu.
2. Select office from dropdown menu.
3. Select Center.

**Expected behavior:** 

Toast message displayed "Please select a Group"

**Observed behavior:** 

a toast message containing no message

**Device and Android version:** 

Redmi 3S
MIUI Version 8.5.4.0
**Screenshots:** 

![screenshot_2018-01-17-23-53-37-037_com mifos mifosxdroid](https://user-images.githubusercontent.com/34041978/35060441-57b1d7ec-fbb6-11e7-95af-b0bd237a482f.png)

**Comment by himanshu112** [comment]
@therajanmaurya  @tarun0 can I take up the issue?

**Comment by AkshGautam** [comment]
@himanshu112 are you still working on this?

**Comment by himanshu112** [comment]
@AkshGautam  I have solved the issue on my local machine
