### ISSUE TITLE
Adding check for DOB while creating new Client

### ISSUE THREAD

**Issue by miPlodder** [openMF/android-client#792]
**Steps to reproduce:** 

1. Swipe right to open Navigation Drawer
2. Click on Clients
3. Click on '+'
4. Now, we can fill the form with today's Date as **DOB.**

**Expected behavior:** 

Prevent addition of new Client and show a message that '_**Client should be atleast 18 years to apply for loan**_' when Submit Button is pressed.

**Observed behavior:** 

Adds the new Client to Database.

**Device and Android version:** 

All devices

**Screenshots:** 

![_1](https://user-images.githubusercontent.com/22195621/35062600-c6d42a06-fbea-11e7-9b63-0e9f97e30fea.png)

**Can I start to work on this issue ?**

**Comment by sashank27** [comment]
@tarun0 @therajanmaurya may I work on the issue?

**Comment by tarun0** [comment]
While submitting the current date is certainly incorrect, can you please mention the source where you found the 18 years age limit?

**Comment by miPlodder** [comment]
I don't have any source for 18 years age limit, but 18 years is age for mature bank account in many countries and without bank account we cannot provide loan.

We can even use any age restriction @tarun0 @therajanmaurya .

**Comment by therajanmaurya** [comment]
No this is the wrong assumption, Anybuddy can have a bank account and It's totally independent to DOB.

I am closing this issue, I don't think we need any further discussion. @miPlodder Thanks for raising the question.
