### ISSUE TITLE
Center is not getting activated

### ISSUE THREAD

**Issue by himanshu112** [openMF/android-client#798]
**Summary:** 
When you try to activate the inactive center, you will get a toast message saying "Client activated Successfully" and then you will also be displayed "Center inactive" as toast message. 

**Steps to reproduce:** 
1. Click on center from the navigation drawer.
2. Select an inactive center (marked as red).
3. Click on activate center.
4. Choose a date and click activate.

**Expected behavior:** 
Toast message should be displayed saying center activated successfully.
Once the center is activated ,button activate center should disappear.
And the center should turn to green from red.

**Device and Android version:** 

Model: Redmi 3S
MIUI 8.5.4.0

**Screenshot**
![screenshot_2018-01-19-17-17-31-254_com mifos mifosxdroid](https://user-images.githubusercontent.com/34041978/35149882-b442104e-fd0f-11e7-850b-33b547623cc8.png)

**Comment by ManognaMutyala** [comment]
I would like to work on this issue!!

**Comment by AkshGautam** [comment]
@ManognaMutyala you can ask @tarun0 @therajanmaurya  regarding this. Thanks

**Comment by santoshconflux** [comment]
This issue is not reproducible. Closing it.
