### ISSUE TITLE
Adding new notes to client

### ISSUE THREAD

**Issue by himanshu112** [openMF/android-client#799]
**Summary:** 

Able to view notes that are already added to the client but unable to add new notes.

**Steps to reproduce:** 

1. Click client from navigation.
2. Select a client.
3. From the menu option select notes.

**Expected behavior:** 

Option to add new notes.

Can I work on this?

**Comment by AkshGautam** [comment]
@himanshu112 if you are not working on this @therajanmaurya @tarun0 I would like to do this.

**Comment by AkshGautam** [comment]
@himanshu112  #601 is same as this one.

**Comment by tarun0** [comment]
@himanshu112 Do you wish to work on this? If you don't reply within next 5 days, it'll be assigned to @AkshGautam 

And please do NOT make new issues for the already listed.
