### ISSUE TITLE
GroupListAdapter.java line 35

### ISSUE THREAD

**Issue by ishan1604** [openMF/android-client#80]
#### in com.mifos.mifosxdroid.adapters.GroupListAdapter.<init>

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://crashlytics.com/openmf/android/apps/com.mifos.mifosxdroid/issues/543eb8d3e3de5099ba0eb84b](https://crashlytics.com/openmf/android/apps/com.mifos.mifosxdroid/issues/543eb8d3e3de5099ba0eb84b)

**Comment by tdjogi010** [comment]
@ishan1604  I would like to look into this issue. It would be great if you can add me to the organisation on crashlytics.
