### ISSUE TITLE
App crashes when the screen is tilted to landscape mode

### ISSUE THREAD

**Issue by AbhilashG97** [openMF/android-client#802]
**Summary:** 

App crashes when the screen is tilted to landscape in Individual Collection Sheet

**Steps to reproduce:** 

1. Open the app
1. Tap on the hamburger menu and select ```Individual Collection Sheet```
1. Tilt the screen to landscape mode

**Expected behavior:** 

The app shouldn't crash.

**Observed behavior:** 

The app crashes when the screen is tilted to landscape mode.

**Device and Android version:** 

Device : Xiaomi Mi A1 [tissot]
ROM : Stock Android [Oreo 8.0.0]

**Logs:**

The logs for the app crash can be found [here](https://gist.github.com/AbhilashG97/0d532168563ec4a3c4f3f356fb6e580d)

**GIF:** 

![videotogif_2018 01 20_19 20 28](https://user-images.githubusercontent.com/20839661/35185604-7c482c86-fe2d-11e7-9158-988eb4950442.gif)

**Comment by AbhilashG97** [comment]
I would like to work on this issue.

**Comment by tarun0** [comment]
Fixed in https://github.com/openMF/android-client/pull/821
