### ISSUE TITLE
Invalid Toast Message on Activating group/client/center

### ISSUE THREAD

**Issue by AkshGautam** [openMF/android-client#810]
**Summary:** 

Invalid Toast message of "Client Created successfully" is presented on group activation

**Steps to reproduce:** 

1)Run the app
2)Activate inactive group

**Expected behavior:** 

The Toast message should be "Group created succesfully"

**Observed behavior:** 

Invalid toast message

**Device and Android version:** 

Android Version 5.0.2,API 21

**Screenshots:** 

![20180123_233110](https://user-images.githubusercontent.com/19329788/35292446-8529fe5e-0096-11e8-97cf-370c05a72070.gif)

**Comment by AkshGautam** [comment]
@therajanmaurya  Sending a PR.

**Comment by tarun0** [comment]
Fixed in https://github.com/openMF/android-client/pull/812
