### ISSUE TITLE
Unsorted Drop Downs across activities

### ISSUE THREAD

**Issue by AkshGautam** [openMF/android-client#814]
**Summary:** 

The fields in drop downs across all activities are unsorted.In case the drop down contains a large number of entries,the search may become cumbersome.

**Steps to reproduce:** 

For instance 
1) Run the app
2) Create Center
3) Select office drop down

**Expected behavior:** 

Lexicographically sorted entries for easier lookup.

**Observed behavior:** 

Unsorted entries make search difficult.

**Device and Android version:** 

Android 5.0.2, API 21

**Screenshots:** 
![20180125_153252](https://user-images.githubusercontent.com/19329788/35384474-6a209446-01eb-11e8-9797-5fc141fffc4a.gif)

**Comment by AkshGautam** [comment]
@therajanmaurya may i work on this?

**Comment by apoorvinfo** [comment]
@tarun0 @therajanmaurya may I work on this?

**Comment by AkshGautam** [comment]
@apoorvinfo  I have already solved this on my machine. Please ask the person before working on it. I was waiting for the acknowledgment from the repo owners

**Comment by tarun0** [comment]
Fixed in https://github.com/openMF/android-client/pull/820
