### ISSUE TITLE
Empty snackbar message in Collection sheet.

### ISSUE THREAD

**Issue by AkshGautam** [openMF/android-client#816]
**Summary:** 

Empty snack bar message in Collection sheet with No internet connection.

**Steps to reproduce:** 

1)Run the app
2)Select Collection Sheet from side menu

**Expected behavior:** 

A snackbar message which shows "failed to fetch office" since internet connection is not available.

**Observed behavior:** 

Empty snackbar

**Device and Android version:** 

Android 5.0.2,API 21

**Screenshots:** 

![20180129_225028](https://user-images.githubusercontent.com/19329788/35524538-e3c49af4-0547-11e8-805f-67b06800f170.gif)

**Comment by AkshGautam** [comment]
@therajanmaurya  @tarun0  may i work on this?

**Comment by laxyapahuja** [comment]
i tried recreating this error but wasn't able to. the snack bar is not empty. it shows the error already.

**Comment by laxyapahuja** [comment]
<img src="https://user-images.githubusercontent.com/31318248/70610369-77f4f300-1c29-11ea-9211-c2c14bd3d5bd.jpeg" alt="hlo" width="300"/>
