### ISSUE TITLE
Groups are not in sorted way

### ISSUE THREAD

**Issue by apoorvinfo** [openMF/android-client#819]
Summary:

The groups in group section  from the navigation bar are unsorted manner which makes it complex to search through the particular group during online mode.

Steps to reproduce:

For instance

Run the app
Open Navigation Bar
Select Groups
Expected behavior:

Lexicographically sorted entries for easier lookup.

Observed behavior:

Unsorted entries make search difficult.

Device and Android version:

Android 5.0.2, API 23
![screenshot_20180131-143328](https://user-images.githubusercontent.com/21074243/35614553-7c0a2a9c-0695-11e8-9745-6334e0713f95.png)

**Comment by apoorvinfo** [comment]
@tarun0 @therajanmaurya I want to work in this issue!

**Comment by bensoft2k5** [comment]
Hello @apoorvinfo. Have you been assigned this task ?

**Comment by bensoft2k5** [comment]
I would love to work on this issue

**Comment by apoorvinfo** [comment]
@bensoft2k5 go on please!

**Comment by santoshconflux** [comment]
The groups are sorted from creation/activation date - From latest to oldest. Let there be a filter to choose either - sort by creation date and sort by Alphabetically.
