### ISSUE TITLE
App crashes in path tracker if location disabled

### ISSUE THREAD

**Issue by nb2998** [openMF/android-client#828]
**Summary:** 

App crashes if path tracking is enabled while access to current location is disabled.

**Steps to reproduce:** 
Disable access to current location
Open app -> Nav Drawer -> Path tracker -> Click on the button in top right corner to start tracking

**Expected behavior:** 

User should be asked to enable location access.

**Screenshots:** 

![path-tracker-crash](https://user-images.githubusercontent.com/25134501/35805079-76a441fa-0aa0-11e8-99d9-42ee5d9b944a.gif)

**Would you like to work on this?**
Yes

**Comment by robustTechie** [comment]
I will work on this issue.

**Comment by robustTechie** [comment]
I found this issue doesn't exist now. Thankyou for your contribution :)
