### ISSUE TITLE
Dashboard activity is rendered on entering password while on different activity before passlock.

### ISSUE THREAD

**Issue by AkshGautam** [openMF/android-client#834]
**Summary:** 

Currently when the application loses focus and the passcode activity is rendered on resume, The activity to which the activity is redirected is Dashboard activity.

**Steps to reproduce:** 

1)Run the app
2)Go to activities other than the dashboard.
3)Let the app loose focus by waiting sometime
4)enter the passocde.

**Expected behavior:** 

The activity that should be rendered after entering password should be the one on which the field officer was working prior to lock. The field officer might be in middle of some important work and he might minimize the application for some other use. When he comes back to app  the same activity should be rendered with no data lose.

**Observed behavior:** 

Dashboard activity is rendered and the previous state of application is entirely lost. The field officer might loose the already filled details in a form if such thing happens.

**Device and Android version:** 

Android 5.0.2,API 21

I am working on this.

**Comment by AkshGautam** [comment]
@therajanmaurya @tarun0  I am working on this

**Comment by Aditya-gupta99** [comment]
This issue has been resolved.
