### ISSUE TITLE
Set Pinpoint activity disappear instantly after clicking on icon. 

### ISSUE THREAD

**Issue by iml-v** [openMF/android-client#839]
**Summary:** 

When we click on icon for setting new pinpoint location, it opens Map but instantly Map activity closes ,so user is not able to set location according to his/her .

**Steps to reproduce:** 

open the app .Open Navbar and click on Clients and choose any client and choose Pinpoint Location from menu  and click on top right corner icon for setting new location .

**Expected behavior:** 

User should be able to set new location according to his/her .

**Observed behavior:** 

New Location set activity closes instantly after clicking on icon .

**Device and Android version:** 

Android 7.0 ,API 24

**Screenshots:** 
![vable to _20180207_231549 1](https://user-images.githubusercontent.com/30701209/35932210-20b67a1a-0c5d-11e8-98f0-5d63a912fe46.gif)

**Comment by iml-v** [comment]
@therajanmaurya @tarun0 I am working on this .

**Comment by nb2998** [comment]
@iml-v Are you working on this?

@tarun0 @luckyman20 This is the logcat I am getting on catching the error. Is it anyway related to the settings in the Google Developer Console?
`E/Google Maps Android API: Authorization failure.  Please see https://developers.google.com/maps/documentation/android-api/start for how to correctly set up the map.
03-17 22:52:14.796 16859-16983/com.mifos.mifosxdroid E/Google Maps Android API: In the Google Developer Console (https://console.developers.google.com)
                                                                                Ensure that the "Google Maps Android API v2" is enabled.
                                                                                Ensure that the following Android Key exists:
                                                                                	API Key: _____
                                                                                	Android Application (<cert_fingerprint>;<package_name>): 4F:61:79:47:BE:DD:6A:C8:46:3E:0D:2C:DE:69:96:D0:B5:48:5F:DB;`

**Comment by iml-v** [comment]
@nb2998 i can work on this .

**Comment by nb2998** [comment]
@tarun0 @therajanmaurya The PlacePicker intent builder returns with result code 2 which seems to be an issue with API key ([Same issue](https://github.com/googlesamples/android-play-places/issues/13)).

**Comment by luckyman20** [comment]
@nb2998 Have you find the solution for it?

**Comment by nb2998** [comment]
@luckyman20 
A common solution that I found on stackoverflow is - Ensure Google Places API for Android and not just Places API in the Developer Console is enabled. ("Places API for Android" will not show up under APIs & Auth/APIs because it isn’t a popular API (yet)).

**Comment by luckyman20** [comment]
@nb2998 Have you tried the other solution for it? If yes, it worked or not

**Comment by tarun0** [comment]
@nb2998 Can you try to replace the present key with the one from your own account (create one if you don't have)? It seems to be some key related issue and the keys usually can't be disclosed publicly. Update here when you're done.

**Comment by nb2998** [comment]
@tarun0 Yes, it's working on replacing it with a newly generated key.

**Comment by roya90** [comment]
Hey, I checked all of the above-mentioned solutions and neither work. Any new solution?
