### ISSUE TITLE
Improper message in different sections on no internet connection.

### ISSUE THREAD

**Issue by ivary43** [openMF/android-client#846]
**Summary:** 

Improper message in different sections on no internet connection.

**Steps to reproduce:** 

Open Client ,Groups etc in absence of internet connection.

**Expected behavior:** 

Message there is 'Click to refresh' but there is nothing to click so actually the message should be swipe to refresh.

**Observed behavior:**
 
Improper message ' Click to refresh' .

**Device and Android version:** 
Device: Moto g-3.
Version -6.0.1.

**Comment by ivary43** [comment]
@tarun0 , @therajanmaurya I would like to work on this issue.

**Comment by tarun0** [comment]
Closed as requested
