### ISSUE TITLE
App crashing when creating client in offline mode.

### ISSUE THREAD

**Issue by AkshGautam** [openMF/android-client#847]
**Summary:** 

App crashing when hitting submit  button on creating client.

**Steps to reproduce:** 

1)Run the app
2)Create client
3)Hit submit when offline

**Expected behavior:** 

App not crashing and presenting a toast

**Observed behavior:** 

App crashing.

**Device and Android version:** 

Android 5.0.2,API 21

**Screenshots:** 
![20180208_141030](https://user-images.githubusercontent.com/19329788/35963362-7fb6fab2-0cda-11e8-8af9-3e8bb769c81c.gif)
I am working on this.

**Comment by AkshGautam** [comment]
@therajanmaurya @tarun0  I am working on this

**Comment by AkshGautam** [comment]
@therajanmaurya  looks like I figured out the reason for the crash and I have solved that in #823  .You may close this issue. PR #825 would solve this as well.

**Comment by ivary43** [comment]
@AkshGautam  i already reported the issue in issue  #845, go through the whole issue.

**Comment by AkshGautam** [comment]
@ivary43  I have already solved the crash problem few days back,while solving some other issue.You can further add the message.The crash is occuring when the drop downs are not inflated and we hit submit button.I solved the inflation issue which handled the crash case as well. You may add the message. Thats why i said in my above comment to close  this issue regarding crash.
