### ISSUE TITLE
Restricting the user to move ahead from passcode activity is internet is not connected.

### ISSUE THREAD

**Issue by AkshGautam** [openMF/android-client#848]
**Summary:** 

Taking the idea from mifos mobile app the user is not allowed to move to further activities from passcode if the internet is not connected.

**Steps to reproduce:** 

How can we reproduce the issue?

1)run the app
2)enter passcode without internet

**Expected behavior:** 

A snackbar and restricting user to move further if internet is absent.

**Observed behavior:** 

User is able to move further without internet connection.

**Device and Android version:** 

Android 5.0.2,API 21

I am working on this.

**Comment by AkshGautam** [comment]
@therajanmaurya @tarun0  I am working on this

**Comment by tarun0** [comment]
@AkshGautam Passcode is saved offline only. He can use the offline-functionalities when there is no internet. If you deny the user access to the offline features, then implementing them in the first place doesn't make any sense!

**Comment by AkshGautam** [comment]
@tarun0 sure I agree!
