### ISSUE TITLE
Creating center without internet connection leads to empty toast.

### ISSUE THREAD

**Issue by AkshGautam** [openMF/android-client#852]
**Summary:** 

Creating center without internet connection leads to empty toast.

**Steps to reproduce:** 

1)Run the app
2)go offline
3)create center
toast--failed to fetch offices
4)Enter name
5)hit submit

**Expected behavior:** 

A snackbar with no internet connection on hitting submit

**Observed behavior:** 

An empty toast

**Device and Android version:** 

Android 5.0.2,API 21

**Screenshots:** 

![20180208_162007](https://user-images.githubusercontent.com/19329788/35969498-08e896f8-0ced-11e8-8e10-02fd12c3ebf2.gif)
I am working on this.

**Comment by AkshGautam** [comment]
@therajanmaurya @tarun0  I am working on this.

**Comment by ivary43** [comment]
@AkshGautam  you reported same type of issue in #816, i think it will be better to fix this type of issue in one Issue.What's your view on this?

**Comment by AkshGautam** [comment]
@ivary43 I will try to solve them in one PR.

**Comment by AkshGautam** [comment]
@ivary43 one PR is solving them all.

**Comment by AkshGautam** [comment]
@ivary43 One PR references them all.

**Comment by tarun0** [comment]
@AkshGautam Don't address more than one issue in a single PR. If the issues are very related, only a single issue should be created for all those.

**Comment by tarun0** [comment]
No. Send three PR for the three issues. They are similar but correspond to different screens/feature. So, let them be so and send different PR for the different issues.

**Comment by AkshGautam** [comment]
Alright, I would do that but since I have changed the MFErrorParser class itself so that will solve all such network-related empty toasts at once.So if one of the PR gets merged rest two would be redundant.
