### ISSUE TITLE
Using two steps to verify the passcode when setting the passcode.

### ISSUE THREAD

**Issue by ivary43** [openMF/android-client#854]
**Summary:** 

Using two steps to verify the passcode when setting the passcode. This is general while setting a password or passcode we use two steps to set the passcode: Enter and re-enter to verify the passcode so that the user doesn't commit any mistake while setting the passcode.

**Steps to reproduce:** 

Try logging in and setting the passcode.

**Expected behavior:** 

Two steps should be there 

- Enter the passcode.
- Re-enter to verify the passcode.

**Comment by ivary43** [comment]
@therajanmaurya, @tarun0  I would like to work on this issue.

**Comment by tarun0** [comment]
@ivary43  You may work on it.

**Comment by Aditya-gupta99** [comment]
The issue has already been resolved
