### ISSUE TITLE
Large irrelevant spacing in Client charges recyclerview.

### ISSUE THREAD

**Issue by ivary43** [openMF/android-client#862]
**Summary:** 
Large irrelevant spacing in Client charges recyclerview.

**Steps to reproduce:** 

Clients->Pick a client->Charges ->Scroll through the page.

**Expected behavior:** 

There shouldn't be so large space between two items in the recyclerview. 

**Observed behavior:** 

The space between two items was too large.

**Device and Android version:** 
Moto G-3(6.0.1).

**Screenshots:** 
![20180209_044616](https://user-images.githubusercontent.com/24601454/36003658-fa74d25e-0d54-11e8-962f-23b90c023b7a.gif)

**Comment by ivary43** [comment]
@therajanmaurya  , @tarun0  i would like to work on this issue.

**Comment by iml-v** [comment]
Yeah @ivary43  #857 #609  these issues are same as yours.

**Comment by tarun0** [comment]
@ivary43 The previous issue was mere 2 item below when you posted this one. You would not even need to search in order to determine that there is already an existing issue. Don't be that negligent.

**Comment by ivary43** [comment]
@tarun0  sorry  i get your point ,i myself try to not make a duplicate issue many times but somehow I didn't notice.Sorry for the inconvenience.
