### ISSUE TITLE
Zero value is getting accepted as Nominal annual interest and many other fields add savings account.

### ISSUE THREAD

**Issue by ivary43** [openMF/android-client#863]
**Summary:** 
Zero value is getting accepted as Nominal annual interest and many other fields add savings account.

**Steps to reproduce:** 

Clients->Pick a client->Add savings account->enter 0 in Nominal interset or any other important field.

**Expected behavior:** 

The value above mentioned should be greater than 0.

**Observed behavior:** 

Zero value was accepted.

**Device and Android version:** 
Moto G-3(6.0.1).

**Screenshots:** 

![20180209_045836](https://user-images.githubusercontent.com/24601454/36004104-f91a8140-0d56-11e8-9404-990473188e32.gif)

**Comment by ivary43** [comment]
@tarun0 , @therajanmaurya  i would like to work on this issue.

**Comment by AkshGautam** [comment]
@ivary43  Nominal interest rate is something which is negotiated by the two parties or is it fixed by the institution. According to me, Nominal Interest rate can be zero as well as some parties might negotiate at no interest but rather as a charity/borrow to the assignee. @therajanmaurya  @tarun0  what do you think?

**Comment by tarun0** [comment]
If the server doesn't respond with any error while submitting zero, then it isn't an invalid case.

**Comment by ivary43** [comment]
@tarun0  what should i do because two more fields 'enforce minimum required balance' accept 0 value, So should i check on app side for these kinds of error.

**Comment by tarun0** [comment]
I didn't get you. What's wrong if some field accepts 0 value unless it's prohibited by the server?

**Comment by ivary43** [comment]
@tarun0 I thought that we are checking on our side first that those values are valid are not and then sending to the server.

**Comment by tarun0** [comment]
It could have been fine had the server responded with some error but it's fine for the server. So, it can't be considered issue/bug. Closing the Issue.
