### ISSUE TITLE
Using Indicator to show whether client/center is activated like groups.

### ISSUE THREAD

**Issue by AkshGautam** [openMF/android-client#865]
**Summary:** 

Currently, there is not an indicator in list view to show whether the client/center is activated or not.

**Steps to reproduce:** 

1)Run the app
2)Clients

**Expected behavior:** 

Indicator where red means not activated and green means activated.

**Observed behavior:** 

No indicator in list view like centers

**Device and Android version:** 

Android 5.0.2,API 21

**Screenshots:** 
This is what the UI indicator should look.

![screenshot_2018-02-09-08-54-03](https://user-images.githubusercontent.com/19329788/36010606-4a5ac6fc-0d78-11e8-8217-7fb429f7a4d0.png)

**Comment by AkshGautam** [comment]
@therajanmaurya @tarun0  what do you think? I would like to work on this if you feel its relevant.

**Comment by luckyman20** [comment]
@AkshGautam The issue is already opened #777

**Comment by AkshGautam** [comment]
@luckyman20  Yeah I just saw that.I guess this issue is more descriptive since most people were not able to understand what the issue was in # 777. Should I start working on it?

**Comment by luckyman20** [comment]
@AkshGautam You can add the description in that issue by commenting

**Comment by AkshGautam** [comment]
@luckyman20 That issue was a while back and I did not notice it has been already created.otherwise i would have done that

**Comment by tarun0** [comment]
@luckyman20 is right. You should add the details in the existing issue only, especially when you've seen it. Please add the description in that issue.
