### ISSUE TITLE
Progress bar overshadowing Navigation drawer.

### ISSUE THREAD

**Issue by AkshGautam** [openMF/android-client#866]
**Summary:** 

Progress bar is currently overshadowing navigation drawer.According to my perception of UX, this should not happen and nav drawer should overshadow the progress bar when the drawer is opened. Currently this gives users the impression of something loading in navbar but actually, the progress bar is intended for the fragment below nav drawer.

**Screenshots:** 

![20180209_094124](https://user-images.githubusercontent.com/19329788/36011595-675ca31e-0d7e-11e8-88b2-a8b0452e295c.gif)

I would like to take up this task.

**Comment by AkshGautam** [comment]
@therajanmaurya @tarun0  What do you think? I would like to take work on this if this is relevant UI change.

**Comment by tarun0** [comment]
Yes, you can work on it.
