### ISSUE TITLE
Wrong labelling on navigation bar in Client Document list.

### ISSUE THREAD

**Issue by ivary43** [openMF/android-client#876]
**Summary:** 
Wrong labelling on navigation bar in Client Document list.

**Steps to reproduce:** 

Clients->pick a client ->Documents.

**Expected behavior:** 

The navigation bar should be labelled with Documents.

**Observed behavior:** 

The navigation bar was labelled with Client's name initials,

**Device and Android version:** 

Device: Moto G-3.
Version:6.0.1.

**Screenshots:** 
![screenshot_20180211-041234](https://user-images.githubusercontent.com/24601454/36067592-e63912ae-0ee5-11e8-9f0c-10871d56ff28.png)

**Comment by ivary43** [comment]
@therajanmaurya , @tarun0  i would like to work on this issue.

**Comment by Aditya-gupta99** [comment]
This issue has been already resolved.
