### ISSUE TITLE
Forever loading progress bar in client's image section on no internet connection.

### ISSUE THREAD

**Issue by ivary43** [openMF/android-client#877]
**Summary:** 
Forever loading progress bar in client's image section on no internet connection.

**Steps to reproduce:** 
Clients-> Turn off internet ->Pick a client..

**Expected behavior:** 

The image section should show error icon or default image there in absence of internet.

**Observed behavior:** 

There was a forever loading progress bar.

**Device and Android version:** 

Moto-G3(6.0.1)

**Screenshots:** 

![20180211_041456](https://user-images.githubusercontent.com/24601454/36067639-d418cd5c-0ee6-11e8-940b-8301a0e62da9.gif)

**Comment by ivary43** [comment]
@therajanmaurya , @tarun0 i want to work on this issue.

**Comment by ivary43** [comment]
@therajanmaurya  this is a part of issue #475. So should i fix both of them in one PR.

**Comment by tarun0** [comment]
@ivary43 Work on #475 only. This screen should not be shown to the user (details there in on of the comments by Rajan). Closing this.
