### ISSUE TITLE
Swipe refresh layout and progree bar appear on the same time when PathTrackingActivity started.

### ISSUE THREAD

**Issue by zjmeow** [openMF/android-client#879]
**Summary:** 

Swipe refresh layout and progree bar appear on the same time when PathTrackingActivity started.

**Steps to reproduce:** 

opening drawerlayout→Path Tracker

**Expected behavior:** 

The swipe refresh layout should not show.

**Device and Android version:** 

Leovo P1 (6.0.1)

**Screenshots:** 

![screenshot_20180211-194900-708](https://user-images.githubusercontent.com/25023887/36073056-13f024ce-0f65-11e8-95d4-69626f3c5b57.jpg)

**Comment by StonyMoon** [comment]
@tarun0 @therajanmaurya I would like to work on this issue.

**Comment by tarun0** [comment]
@StonyMoon  Add a GIF/video. It's working fine on my phone, though.

**Comment by StonyMoon** [comment]
I find that it also happen in other activities but swipe refresh layout will disappear quickly.
In the PathTrackingActivity it will obviously stay a while. 

I read the code and find that it firstly call setRefreshing(true) and then cancel.
Is there something wrong or aiming to compatible with different Android versions?
Thanks for your reply!
```java
    public void showProgressbar(boolean show) {
        swipeRefreshLayout.setRefreshing(show);
        if (show && userLocations.size() == 0) {
            progressBar.setVisibility(View.VISIBLE);
            swipeRefreshLayout.setRefreshing(false);
        } else {
            progressBar.setVisibility(View.GONE);
        }
    }
```

![1](https://user-images.githubusercontent.com/25023887/36098308-6cd64404-1039-11e8-9a2b-5917c75f8cea.gif)
