### ISSUE TITLE
Improvement of UI of Create Client, Create center and Create group

### ISSUE THREAD

**Issue by prem0862** [openMF/android-client#893]
**Summary:** 

In Create centre and Create group, the activte option is not aligned properly ( as in dashboard)

**Steps to reproduce:** 

a) Overflow Menu -> Create Centre
b) Overflow Menu -> Create Group

**Expected behaviour:** 

It should be aligned as **Exact Match** of Dashboard (in my opinion) to enhance visual experience

![dashboard](https://user-images.githubusercontent.com/25509407/36268752-5f643a22-129d-11e8-977c-457ba6d6e7c8.PNG)

**Observed behaviour:** 

![create group](https://user-images.githubusercontent.com/25509407/36268809-825c9b1e-129d-11e8-8568-1c4f0916bfb4.PNG)

![create centre](https://user-images.githubusercontent.com/25509407/36268822-8ab6008e-129d-11e8-950b-6a7732c05cd3.PNG)

Textviews besides checkbox, in Create group and Create centre is currently not aligned properly ( as in Dashboard)

![dashboard](https://user-images.githubusercontent.com/25509407/36268928-da0c9df0-129d-11e8-90ab-9ffde06b1037.PNG)

**Device and Android version:** 
Android 7, API 24

**Comment by Prem0707** [comment]
@luckyman20 @tarun0  Please give you valuable suggestion on it. Thanks

**Comment by Prem0707** [comment]
This issue is also found in Create client section. @luckyman20 I am working on it

**Comment by Prem0707** [comment]
@luckyman20 @tarun0 Please review #895 Thanks:)

**Comment by Aditya-gupta99** [comment]
This issue has been already resolved.
