### ISSUE TITLE
Fourth dot in the PassCodeView is not filled when incorrect passcode is entered

### ISSUE THREAD

**Issue by AbhilashG97** [openMF/android-client#900]
**Summary:** 

Fourth dot in the ```PassCodeView``` is not filled when incorrect passcode is entered, which doesn't occur when correct pass-code is entered. 

**Steps to reproduce the issue:**

1. Setup a pass-code in the app
1. Enter an incorrect pass-code 

**Expected behaviour:** 

The fourth dot should be filled in the ```PassCodeView``` when incorrect pass-code is entered.

**Observed behaviour:** 

The fourth dot is not filled in the ```PassCodeView``` when incorrect pass-code is entered.

**Device and Android version:** 

Device : Xiaomi Mi A1 [tissot]
ROM : Stock Android [Oreo 8.0.0]

**GIF:** 

![videotogif_2018 02 20_16 29 52](https://user-images.githubusercontent.com/20839661/36421733-b4625f66-165f-11e8-894b-1034511ef4d2.gif)

**Comment by AbhilashG97** [comment]
I would like to work on this issue.

**Comment by Aditya-gupta99** [comment]
Issue has been resolved.
