### ISSUE TITLE
Enhancement- In Login Toast message

### ISSUE THREAD

**Issue by Prem0707** [openMF/android-client#904]
**Summary:** 

Nothing is wrong here but there can be enhancement with login  Toast message

**Steps to reproduce:** 

Enter User Name and Password -> log in

**Expected behaviour:** 

Currently, I giving a toast - "Welcome mifos", We can change it to "Welcome to Mifos"

**Device and Android version:** 

Nexus 5, API 24 (Android 7)

**Screenshots:** 

![ezgif com-resize](https://user-images.githubusercontent.com/25509407/36541303-79730950-1803-11e8-8ede-62b27636f14b.gif)

**Comment by Prem0707** [comment]
@luckyman20 @tarun0 does it make sense? Thanks

**Comment by luckyman20** [comment]
@Prem0707 `mifos` is the username here so I don't think so that this enhancement is relevant

**Comment by Prem0707** [comment]
@luckyman20 What I thought is if there is a new officer login through this (client)  app then we are welcoming him\her, is it not like that? and why we should give the username message to a user after they have already entered it to log in? 

If it is not like that, should i close this issue? Thanks

**Comment by luckyman20** [comment]
@Prem0707 We are welcoming the Officer through his/her username and I don't think there is any problem in that.

**Comment by Prem0707** [comment]
@luckyman I got it, I thought we are welcoming to them (Officers) in Community. Please close this issue. Thanks
