### ISSUE TITLE
Incorrect message in charges of a client

### ISSUE THREAD

**Issue by nb2998** [openMF/android-client#907]
**Summary:** 

Incorrect message stating "No charges available for this client" displayed inspite of having charges.

**Steps to reproduce:** 

* Clients
* Select a client
* Options ->Charges
* Scroll till bottom 

**Expected behaviour:** 

Incorrect message shouldn't be displayed.

**Screenshots:** 

![mifos-charges](https://user-images.githubusercontent.com/25134501/36554869-74213698-1826-11e8-8710-ea39b3ff832a.gif)

**Comment by nb2998** [comment]
@luckyman20 @tarun0 @therajanmaurya  I'm working on this.

**Comment by AbhilashG97** [comment]
This issue has been fixed. Thank you for your contribution.
