### ISSUE TITLE
Improvement of UI in client charges

### ISSUE THREAD

**Issue by himanshu112** [openMF/android-client#908]
**Summary:** 
There is a large gap between two card view

**Steps to reproduce:** 
1. Clients
2. select a client
3. Navigate to charges from menu.

**Expected behaviour:** 
The cards should be in a sequence and gap should be reduced to minimal

**Observed behavior**
the cards appear too far from each other

**Device and Android version:** 
Redmi 3S
MIUI 8
**Screenshots:** 

![screenshot_2018-02-23-00-10-30-055_com mifos mifosxdroid](https://user-images.githubusercontent.com/34041978/36558044-c20b02b4-1801-11e8-840d-e327330316bd.png)

**Comment by himanshu112** [comment]
@tarun0 @therajanmaurya can I work on the issue

**Comment by ivary43** [comment]
@himanshu112  this is a duplicate issue of #609 and pr has already been sent.Please close this issue.

**Comment by himanshu112** [comment]
oky

**Comment by himanshu112** [comment]
Leave a comment
