### ISSUE TITLE
User is allowed to enter incorrect pass-code 4 times instead of 3 times

### ISSUE THREAD

**Issue by AbhilashG97** [openMF/android-client#909]
**Summary:** 

This is a minor issue where the user is allowed to enter incorrect pass-code 4 times instead of 3 times. 

**Steps to reproduce:** 

1. Open the app
1. Setup a pass-code
1. Open the app again
1. Enter incorrect passcode

**Expected behaviour:** 

The app should only allow the user to enter incorrect pass-code 3 times.

**Observed behaviour:** 

Currently, the app allows the user to enter incorrect pass-code 4 times.

**Device and Android version:** 

Device : Xiaomi Mi A1 [tissot]
ROM : Stock Android [Oreo 8.0.0]

**GIF:** 

![videotogif_2018 02 23_08 44 20](https://user-images.githubusercontent.com/20839661/36576357-301928b6-1876-11e8-943f-4c4931efaa59.gif)

**Comment by AkshGautam** [comment]
@AbhilashG97  The toast message says that "You have entered incorrect Passcode more than 3 times." which makes the issue redundant since if the toast message is explicitly mentioning that the 4th attempt is considered failure not 3rd.

**Comment by AbhilashG97** [comment]
@AkshGautam, you're right. I failed to notice this.

**Comment by AbhilashG97** [comment]
I apologize for reporting a false issue.
