### ISSUE TITLE
Datatable list refresh persists indefinitely

### ISSUE THREAD

**Issue by nb2998** [openMF/android-client#916]
**Summary:** 

When a particular datatable is opened and user moves back to datatable list, refresh persists for an indefinite period of time.

**Steps to reproduce:** 

* Groups 
* Open a group
* Options -> More group info
* Open any item and return back

**Expected behaviour:** 

Refreshing should stop as soon as loading data is finished.

**Observed behaviour:** 

It keeps loading/refreshing.

**Screenshots:** 

![datatable-refresh](https://user-images.githubusercontent.com/25134501/36631686-8992a138-19a2-11e8-82d8-079b75dc0d45.gif)

@luckyman20 @tarun0 I would like to work on this.

**Comment by AbhilashG97** [comment]
Hello @nb2998, 

This issue has already been reported and a pull request resolving this issue has already been sent. 
Please view #597

**Comment by nb2998** [comment]
I apologise for the duplicate issue.
@AbhilashG97 Thanks for informing!
