### ISSUE TITLE
Datepicker buttons not visible

### ISSUE THREAD

**Issue by nb2998** [openMF/android-client#920]
**Summary:** 

Ok/Cancel buttons are not visible in Datepicker dialog anywhere

**Steps to reproduce:** 

Create new client -> Select date

**Expected behaviour:** 

Buttons should be visible

**Screenshots:** 

![screenshot_20180226-225231](https://user-images.githubusercontent.com/25134501/36684981-fda322fe-1b47-11e8-8e76-bdd2d2ed663c.jpg)

**Device and Android version:** 

OnePlus 5, Android 8.0.0

@tarun0 @therajanmaurya I would like to work on this.

**Comment by AkshGautam** [comment]
@nb2998 It would be convenient if you can mention the Android version,API as well since it's working fine on my device.
![screenshot_2018-02-26-23-46-44](https://user-images.githubusercontent.com/19329788/36687364-61680bd6-1b4f-11e8-9a6f-4001c1261efe.png)

**Comment by nb2998** [comment]
@AkshGautam Thanks, updated.
