### ISSUE TITLE
Screen keeps loading on creating center twice

### ISSUE THREAD

**Issue by nb2998** [openMF/android-client#927]
**Summary:** 

The screen keeps loading if create center is chosen twice from the over flow menu.

**Steps to reproduce:** 

Dashboard -> Overflow menu -> New center -> Overflow menu -> New client -> Overflow menu -> New center

**Expected behaviour:** 

New Center fragment should be visible.
User shouldn't be allowed to make request for new center again OR A new request should be made, cancelling the previous request and the appropriate screen should be visible.

**Device and Android version:** 

OnePlus 5, 8.0.0

**Screenshots:** 

![20180303_001803](https://user-images.githubusercontent.com/25134501/36916103-fc52a95e-1e78-11e8-8ca2-f4e92b6b9baa.gif)

@tarun0 @therajanmaurya I feel the overflow menu to create new client/center/group should be present on the dashboard and not in the subsequent fragments to avoid such a situation. What do you suggest?

**Comment by tarun0** [comment]
Yes, this should be fixed. Marking it open if anyone wants to work on it.

**Comment by AathmanT** [comment]
I'll work on this issue
