### ISSUE TITLE
Adding collection sheet and individual collection sheet icons.

### ISSUE THREAD

**Issue by ivary43** [openMF/android-client#934]
**Summary:** 
Currently, there is no icon for individual collection sheet and collection sheet.I think there should be an icon for both of them for UI consistency although it's a minor UI change.

**Screenshot**
![screenshot_20180316-161247](https://user-images.githubusercontent.com/24601454/37516882-a630a31a-2935-11e8-8cd9-73e088d7163c.png)

**Comment by ivary43** [comment]
@tarun0, @therajanmaurya  can I work on this minor UI change if applicable.I think maybe we can use [this](https://material.io/icons/#ic_assignment) icon.

**Comment by Aditya-gupta99** [comment]
Issue has been resolved.
