### ISSUE TITLE
App crashes on adding non integer in datatable

### ISSUE THREAD

**Issue by nb2998** [openMF/android-client#940]
**Summary:** 

App crashes when a non integer is added in a datatable while adding loan account

**Steps to reproduce:** 

Clients -> any client -> Options -> Add loan account -> Enter external id -> Submit -> Add non integer entry in datatable -> Save the datatable

**Expected behaviour:** 

App should not crash

**Screenshots:** 

![20180318_234742](https://user-images.githubusercontent.com/25134501/37571496-5902925c-2b23-11e8-803a-cfca7b9811c4.gif)

I would like to work on this @tarun0 @therajanmaurya

**Comment by GauravGangwarZomato** [comment]
Hi
@nb2998 @droidchef 
I have solved this issue. I need access to the repo to Create the corresponding PR. 
--
Regards
Gaurav Gangwar

**Comment by tarun0** [comment]
@gaurav-abes @nb2998 You seem to have fixed the issue in your forked repos. Can you send the PR if that's so?

**Comment by nb2998** [comment]
@tarun0 I already made a PR, it's here: [PR#948](https://github.com/openMF/android-client/pull/948)

**Comment by tarun0** [comment]
Appreciate the prompt reply @nb2998 This issue was not referenced which made it a tad difficult to track.

**Comment by sachin-0102** [comment]
If the issue is still open, Can I work on this?

**Comment by r1shhh1** [comment]
If the issue is still open can i work on this?
