### ISSUE TITLE
Minor gradle refactor

### ISSUE THREAD

**Issue by ivary43** [openMF/android-client#951]
**Summary:** 

In Gradle, versions of some dependency are mentioned directly but according to the convention it should be fetched from rootProject.

**Comment by ivary43** [comment]
@therajanmaurya, @tarun0  I want to work on this issue.

**Comment by tarun0** [comment]
@ivary43 It's been quite a while but can you tell which dependencies you are talking about here?

**Comment by RajaVamsi11** [comment]
@ivary43 @moksh-mahajan I am interested in working on this issue. Can I start working on this one?
@tarun0 These are examples of some dependency versions that can be added to the root project and can be fetched from there.

```
        implementation 'io.reactivex:rxandroid:1.1.0'
        implementation 'io.reactivex:rxjava:1.1.4'

        implementation 'com.facebook.stetho:stetho:1.3.1'
        implementation 'com.facebook.stetho:stetho-okhttp3:1.3.1'

        implementation 'androidx.multidex:multidex:2.0.0'
        annotationProcessor "com.github.Raizlabs.DBFlow.dbflow:dbflow-processor:3.1.1"
        annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:3.1.1"
```
 ...and many more dependencies versions can be added.
