### ISSUE TITLE
Navigation Drawer not getting updated 

### ISSUE THREAD

**Issue by AkshGautam** [openMF/android-client#953]
**Summary:** 

Navigation Drawer not getting updated

**Steps to reproduce:** 

1) Run the app
2) Go to Collection sheet
3) Click the up arrow.
4) Open navbar drawer

**Expected behaviour:** 

Selected item in navbar should be dashboard

**Observed behaviour:** 

Selected item is still collection sheet.

**Screenshots:** 

![20180327_223811](https://user-images.githubusercontent.com/19329788/37983042-da22169e-320f-11e8-983f-52b1e4bd653c.gif)

I would like to work on this.

**Comment by AkshGautam** [comment]
@therajanmaurya @tarun0  I would like to work on this.

**Comment by balaji-ramavathu** [comment]
@AkshGautam @tarun0 @therajanmaurya Hello!
Can I work on this issue?

**Comment by droidchef** [comment]
@balaji-ramavathu Yes you can work on this issue.
