### ISSUE TITLE
Action bar slides in Login activity.

### ISSUE THREAD

**Issue by AkshGautam** [openMF/android-client#968]
**Summary:** 

Action bar slides in Login activity.

**GIF**
![20180415_121128](https://user-images.githubusercontent.com/19329788/38775699-7f852456-40a6-11e8-84b1-b2675bde9730.gif)

I would like to work on this.

**Comment by AkshGautam** [comment]
@therajanmaurya I would like to work on this.

**Comment by RajaVamsi11** [comment]
@AkshGautam @therajanmaurya I would like to work on this issue. can you assign this to me?

**Comment by Siddharth-Singhs** [comment]
@AkshGautam @RajaVamsi11 As no one is working on this issue, can you assign this issue to me.

**Comment by tarun0** [comment]
@Siddharth-Singhs Thanks for testing 👍
