### ISSUE TITLE
Enhancing Collection Sheet

### ISSUE THREAD

**Issue by AkshGautam** [openMF/android-client#980]
**Summary:** 

Enhancing the overall UI and user experience of Collection Sheet

**Screenshots:** 

![screenshot_2018-05-18-16-02-26](https://user-images.githubusercontent.com/19329788/40230597-b607c62c-5ab5-11e8-8e53-84a1973acbec.png)

**Comment by tarun0** [comment]
@AkshGautam The issue is not clear. Please add details - whether it needs UI changes and the mockups are ready or UX level changes and need some discussion etc. 

If already worked upon, reference accordingly.

**Comment by Aditya-gupta99** [comment]
Issue has been resolved.
