### ISSUE TITLE
All Issues related to Login Activity 

### ISSUE THREAD

**Issue by AkshGautam** [openMF/android-client#981]
**Summary:** 

This issue contains all the Login Activity related issues:
1) #977 
2) #968 
3) #965 
4) #795 
5) #688

**Comment by AkshGautam** [comment]
@therajanmaurya  These are the issues related to login activity

**Comment by tarun0** [comment]
@AkshGautam Add some description here. Also, why was there a need to form an issue grouping other issues?

**Comment by AkshGautam** [comment]
@tarun0 I was told to do so by @therajanmaurya a long back. This was done to close the issues quickly without wasting much time to find them.
